### ISSUE TITLE
建议：自定义field的那部分文档

### ISSUE THREAD

**Issue by Wisgon** [lljj-x/vue-json-schema-form#10]
我在看[https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89field](url)的时候，尝试自己去配置一下demo，结果报没有加载“LinkImgField”这个组件的错误，我当时只是在我的父组件中import 了LinkImgField，但是没效果，我去翻查项目源代码，发现common文件夹下面有个“registerExtraElementComponent.js”文件，里面才是引入了LinkImgField这个组件，然后父组件import这个registerExtraElementComponent.js就行了，所以建议这个要在文档里面说明一下吧，没找到有如何引入LinkImgField的说明。

**Comment by lljj-x** [comment]
多谢建议，文档我看看怎么描述更清晰

这里只要是一个已注册的组件即可，可以是组件内通过 `components` 注册的，或者像我那个例子全局注册，可以结合实际场景。

---
另外这里 自定义field，可使用注册组件的组件名，或者组件选项对象 都是可以的，会通过 `createElement ` 方法处理
