### ISSUE TITLE
Error: please transfer a valid prop path to form item （elementUI）

### ISSUE THREAD

**Issue by lonelyzou** [lljj-x/vue-json-schema-form#108]
报错： Error: please transfer a valid prop path to form item
解决参考： http://www.jsphp.net/vue/show-25-447-1.html
Schema文件： 
{
    "title": "测试注册表单",
    "description": "A simple form example.",
    "type": "object",
    "properties": {
        "disable": {
            "title": "disable",
            "type": "boolean"
        },
        "rules": {
            "title": "rules",
            "items": {
                "additionalProperties": false,
                "properties": {
                    "match": {
                        "title": "match",
                        "default": [
                            {
                                "vars": [
                                    [
                                        0,
                                        ">",
                                        "server_port"
                                    ]
                                ]
                            }
                        ],
                        "items": {
                            "properties": {
                                "vars": {
                                    "title": "vars",
                                    "items": {
                                        "additionalItems": {
                                            "anyOf": [
                                                {
                                                    "type": "string"
                                                },
                                                {
                                                    "type": "number"
                                                },
                                                {
                                                    "type": "boolean"
                                                },
                                                {
                                                    "items": {
                                                        "anyOf": [
                                                            {
                                                                "maxLength": 100,
                                                                "minLength": 1,
                                                                "type": "string"
                                                            },
                                                            {
                                                                "type": "number"
                                                            },
                                                            {
                                                                "type": "boolean"
                                                            }
                                                        ]
                                                    },
                                                    "type": "array",
                                                    "uniqueItems": true
                                                }
                                            ]
                                        },
                                        "items": [
                                            {
                                                "maxLength": 100,
                                                "minLength": 1,
                                                "type": "string"
                                            },
                                            {
                                                "maxLength": 2,
                                                "minLength": 1,
                                                "type": "string"
                                            }
                                        ],
                                        "maxItems": 10,
                                        "minItems": 0,
                                        "type": "array"
                                    },
                                    "type": "array"
                                }
                            },
                            "type": "object"
                        },
                        "type": "array"
                    },
                    "weighted_upstreams": {
                        "title": "weighted_upstreams",
                        "default": [
                            {
                                "weight": 1
                            }
                        ],
                        "items": {
                            "properties": {
                                "upstream": {
                                    "title": "upstream",
                                    "additionalProperties": false,
                                    "oneOf": [
                                        {
                                            "required": [
                                                "nodes",
                                                "type"
                                            ]
                                        },
                                        {
                                            "required": [
                                                "discovery_type",
                                                "service_name",
                                                "type"
                                            ]
                                        }
                                    ],
                                    "properties": {
                                        "checks": {
                                            "title": "checks",
                                            "additionalProperties": false,
                                            "anyOf": [
                                                {
                                                    "required": [
                                                        "active"
                                                    ]
                                                },
                                                {
                                                    "required": [
                                                        "active",
                                                        "passive"
                                                    ]
                                                }
                                            ],
                                            "properties": {
                                                "active": {
                                                    "title": "active",
                                                    "properties": {
                                                        "concurrency": {
                                                            "title": "concurrency",
                                                            "default": 10,
                                                            "type": "integer"
                                                        },
                                                        "healthy": {
                                                            "title": "healthy",
                                                            "properties": {
                                                                "http_statuses": {
                                                                    "title": "http_statuses",
                                                                    "default": [
                                                                        200,
                                                                        302
                                                                    ],
                                                                    "items": {
                                                                        "maximum": 599,
                                                                        "minimum": 200,
                                                                        "type": "integer"
                                                                    },
                                                                    "minItems": 1,
                                                                    "type": "array",
                                                                    "uniqueItems": true
                                                                },
                                                                "interval": {
                                                                    "title": "interval",
                                                                    "default": 1,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                },
                                                                "successes": {
                                                                    "title": "successes",
                                                                    "default": 2,
                                                                    "maximum": 254,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                }
                                                            },
                                                            "type": "object"
                                                        },
                                                        "host": {
                                                            "title": "host",
                                                            "pattern": "^\\*?[0-9a-zA-Z-._]+$",
                                                            "type": "string"
                                                        },
                                                        "http_path": {
                                                            "title": "http_path",
                                                            "default": "/",
                                                            "type": "string"
                                                        },
                                                        "https_verify_certificate": {
                                                            "title": "https_verify_certificate",
                                                            "default": true,
                                                            "type": "boolean"
                                                        },
                                                        "port": {
                                                            "title": "port",
                                                            "maximum": 65535,
                                                            "minimum": 1,
                                                            "type": "integer"
                                                        },
                                                        "req_headers": {
                                                            "title": "req_headers",
                                                            "items": {
                                                                "type": "string",
                                                                "uniqueItems": true
                                                            },
                                                            "minItems": 1,
                                                            "type": "array"
                                                        },
                                                        "timeout": {
                                                            "title": "timeout",
                                                            "default": 1,
                                                            "type": "number"
                                                        },
                                                        "type": {
                                                            "title": "type",
                                                            "default": "http",
                                                            "enum": [
                                                                "http",
                                                                "https",
                                                                "tcp"
                                                            ],
                                                            "type": "string"
                                                        },
                                                        "unhealthy": {
                                                            "title": "unhealthy",
                                                            "properties": {
                                                                "http_failures": {
                                                                    "title": "http_failures",
                                                                    "default": 5,
                                                                    "maximum": 254,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                },
                                                                "http_statuses": {
                                                                    "title": "http_statuses",
                                                                    "default": [
                                                                        404,
                                                                        429,
                                                                        500,
                                                                        501,
                                                                        502,
                                                                        503,
                                                                        504,
                                                                        505
                                                                    ],
                                                                    "items": {
                                                                        "maximum": 599,
                                                                        "minimum": 200,
                                                                        "type": "integer"
                                                                    },
                                                                    "minItems": 1,
                                                                    "type": "array",
                                                                    "uniqueItems": true
                                                                },
                                                                "interval": {
                                                                    "title": "interval",
                                                                    "default": 1,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                },
                                                                "tcp_failures": {
                                                                    "title": "tcp_failures",
                                                                    "default": 2,
                                                                    "maximum": 254,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                },
                                                                "timeouts": {
                                                                    "title": "timeouts",
                                                                    "default": 3,
                                                                    "maximum": 254,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                }
                                                            },
                                                            "type": "object"
                                                        }
                                                    },
                                                    "type": "object"
                                                },
                                                "passive": {
                                                    "title": "passive",
                                                    "properties": {
                                                        "healthy": {
                                                            "title": "healthy",
                                                            "properties": {
                                                                "http_statuses": {
                                                                    "title": "http_statuses",
                                                                    "default": [
                                                                        200,
                                                                        201,
                                                                        202,
                                                                        203,
                                                                        204,
                                                                        205,
                                                                        206,
                                                                        207,
                                                                        208,
                                                                        226,
                                                                        300,
                                                                        301,
                                                                        302,
                                                                        303,
                                                                        304,
                                                                        305,
                                                                        306,
                                                                        307,
                                                                        308
                                                                    ],
                                                                    "items": {
                                                                        "maximum": 599,
                                                                        "minimum": 200,
                                                                        "type": "integer"
                                                                    },
                                                                    "minItems": 1,
                                                                    "type": "array",
                                                                    "uniqueItems": true
                                                                },
                                                                "successes": {
                                                                    "title": "successes",
                                                                    "default": 5,
                                                                    "maximum": 254,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                }
                                                            },
                                                            "type": "object"
                                                        },
                                                        "type": {
                                                            "title": "type",
                                                            "default": "http",
                                                            "enum": [
                                                                "http",
                                                                "https",
                                                                "tcp"
                                                            ],
                                                            "type": "string"
                                                        },
                                                        "unhealthy": {
                                                            "title": "unhealthy",
                                                            "properties": {
                                                                "http_failures": {
                                                                    "title": "http_failures",
                                                                    "default": 5,
                                                                    "maximum": 254,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                },
                                                                "http_statuses": {
                                                                    "title": "http_statuses",
                                                                    "default": [
                                                                        429,
                                                                        500,
                                                                        503
                                                                    ],
                                                                    "items": {
                                                                        "maximum": 599,
                                                                        "minimum": 200,
                                                                        "type": "integer"
                                                                    },
                                                                    "minItems": 1,
                                                                    "type": "array",
                                                                    "uniqueItems": true
                                                                },
                                                                "tcp_failures": {
                                                                    "title": "tcp_failures",
                                                                    "default": 2,
                                                                    "maximum": 254,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                },
                                                                "timeouts": {
                                                                    "title": "timeouts",
                                                                    "default": 7,
                                                                    "maximum": 254,
                                                                    "minimum": 1,
                                                                    "type": "integer"
                                                                }
                                                            },
                                                            "type": "object"
                                                        }
                                                    },
                                                    "type": "object"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "create_time": {
                                            "title": "create_time",
                                            "type": "integer"
                                        },
                                        "desc": {
                                            "title": "desc",
                                            "maxLength": 256,
                                            "type": "string"
                                        },
                                        "discovery_type": {
                                            "title": "discovery_type",
                                            "description": "discovery type",
                                            "type": "string"
                                        },
                                        "enable_websocket": {
                                            "title": "enable_websocket",
                                            "description": "enable websocket for request",
                                            "type": "boolean"
                                        },
                                        "hash_on": {
                                            "title": "hash_on",
                                            "default": "vars",
                                            "enum": [
                                                "consumer",
                                                "cookie",
                                                "header",
                                                "vars",
                                                "vars_combinations"
                                            ],
                                            "type": "string"
                                        },
                                        "id": {
                                            "title": "id",
                                            "anyOf": [
                                                {
                                                    "maxLength": 64,
                                                    "minLength": 1,
                                                    "pattern": "^[a-zA-Z0-9-_.]+$",
                                                    "type": "string"
                                                },
                                                {
                                                    "minimum": 1,
                                                    "type": "integer"
                                                }
                                            ]
                                        },
                                        "key": {
                                            "title": "key",
                                            "description": "the key of chash for dynamic load balancing",
                                            "type": "string"
                                        },
                                        "labels": {
                                            "title": "labels",
                                            "description": "key/value pairs to specify attributes",
                                            "maxProperties": 16,
                                            "patternProperties": {
                                                ".*": {
                                                    "description": "value of label",
                                                    "maxLength": 64,
                                                    "minLength": 1,
                                                    "pattern": "^\\S+$",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "name": {
                                            "title": "name",
                                            "maxLength": 100,
                                            "minLength": 1,
                                            "type": "string"
                                        },
                                        "nodes": {
                                            "title": "nodes",
                                            "anyOf": [
                                                {
                                                    "patternProperties": {
                                                        ".*": {
                                                            "description": "weight of node",
                                                            "minimum": 0,
                                                            "type": "integer"
                                                        }
                                                    },
                                                    "type": "object"
                                                },
                                                {
                                                    "items": {
                                                        "properties": {
                                                            "host": {
                                                                "title": "host",
                                                                "pattern": "^\\*?[0-9a-zA-Z-._]+$",
                                                                "type": "string"
                                                            },
                                                            "metadata": {
                                                                "title": "metadata",
                                                                "description": "metadata of node",
                                                                "type": "object"
                                                            },
                                                            "port": {
                                                                "title": "port",
                                                                "description": "port of node",
                                                                "minimum": 1,
                                                                "type": "integer"
                                                            },
                                                            "weight": {
                                                                "title": "weight",
                                                                "description": "weight of node",
                                                                "minimum": 0,
                                                                "type": "integer"
                                                            }
                                                        },
                                                        "required": [
                                                            "host",
                                                            "port",
                                                            "weight"
                                                        ],
                                                        "type": "object"
                                                    },
                                                    "type": "array"
                                                }
                                            ]
                                        },
                                        "pass_host": {
                                            "title": "pass_host",
                                            "default": "pass",
                                            "description": "mod of host passing",
                                            "enum": [
                                                "node",
                                                "pass",
                                                "rewrite"
                                            ],
                                            "type": "string"
                                        },
                                        "retries": {
                                            "title": "retries",
                                            "minimum": 0,
                                            "type": "integer"
                                        },
                                        "scheme": {
                                            "title": "scheme",
                                            "default": "http",
                                            "enum": [
                                                "grpc",
                                                "grpcs",
                                                "http",
                                                "https"
                                            ]
                                        },
                                        "service_name": {
                                            "title": "service_name",
                                            "maxLength": 256,
                                            "minLength": 1,
                                            "type": "string"
                                        },
                                        "timeout": {
                                            "title": "timeout",
                                            "properties": {
                                                "connect": {
                                                    "title": "connect",
                                                    "exclusiveMinimum": 0,
                                                    "type": "number"
                                                },
                                                "read": {
                                                    "title": "read",
                                                    "exclusiveMinimum": 0,
                                                    "type": "number"
                                                },
                                                "send": {
                                                    "title": "send",
                                                    "exclusiveMinimum": 0,
                                                    "type": "number"
                                                }
                                            },
                                            "required": [
                                                "connect",
                                                "read",
                                                "send"
                                            ],
                                            "type": "object"
                                        },
                                        "type": {
                                            "title": "type",
                                            "description": "algorithms of load balancing",
                                            "enum": [
                                                "chash",
                                                "ewma",
                                                "least_conn",
                                                "roundrobin"
                                            ],
                                            "type": "string"
                                        },
                                        "update_time": {
                                            "title": "update_time",
                                            "type": "integer"
                                        },
                                        "upstream_host": {
                                            "title": "upstream_host",
                                            "pattern": "^\\*?[0-9a-zA-Z-._]+$",
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "upstream_id": {
                                    "title": "upstream_id",
                                    "anyOf": [
                                        {
                                            "maxLength": 64,
                                            "minLength": 1,
                                            "pattern": "^[a-zA-Z0-9-_.]+$",
                                            "type": "string"
                                        },
                                        {
                                            "minimum": 1,
                                            "type": "integer"
                                        }
                                    ]
                                },
                                "weight": {
                                    "title": "weight",
                                    "default": 1,
                                    "description": "used to split traffic between differentupstreams for plugin configuration",
                                    "minimum": 0,
                                    "type": "integer"
                                }
                            },
                            "type": "object"
                        },
                        "maxItems": 20,
                        "minItems": 1,
                        "type": "array"
                    }
                },
                "type": "object"
            },
            "type": "array"
        }
    }
}

**Comment by lljj-x** [comment]
问题是因为生成的数据结构对`upstream`  这类配置会直接 生成 undefined，后续节点找不到值了 。

下个版本修复下
