### ISSUE TITLE
自定义表单控件field绑定到formData根节点

### ISSUE THREAD

**Issue by alicksnake22** [lljj-x/vue-json-schema-form#11]
假设一个自定义省市区表单控件要绑定3个变量，分别是省市区，如果做才可以绑定省市区到formData的根节点？如下结构
`{
"p":"广东省",
"c":"佛山市",
"d":"顺德区"
}`

**Comment by lljj-x** [comment]
没明白你的意思。

`v-model` 绑定formData就可以了，然后通过schema描述你的数据结构

**Comment by alicksnake22** [comment]
是要用到自定义Field的功能吗

**Comment by lljj-x** [comment]
你是想把已有的一个省市区组件和生成的表单一起使用 ？

那就是需要 [自定义Field](https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89field) 了，配置 `ui:field`

**Comment by alicksnake22** [comment]
我大概看了下demo，自定义field的数据没有绑定到formData的一级，而是帮到二级
![image](https://user-images.githubusercontent.com/14839142/93428359-ddc98600-f8f1-11ea-9d41-dbe342a80505.png)
同时问下，是否有考虑加入slot功能，这样某些时候可以快速写自定义插件

**Comment by lljj-x** [comment]
如果绑定到根节点你可以直接在根节点配置 `ui:field` 即可，不太清楚你为啥要根节点直接自定义

比如：
```js
{
    "title": "省市区",
    "type": "object",
    "ui:field": "ComponentName", // 配置在这里
    "properties": {
        "p": {
            "title": "省",
            "type": "string"
        },
        "c": {
            "title": "城市",
            "type": "string"
        },
        "d": {
            "title": "区",
            "type": "string"
        }
    }
}
```

---
slot 想不到你的场景怎样的，你可以描述下

**Comment by alicksnake22** [comment]
没有配置成功，1：properties直接绑在pcd下了，没有绑到第一层。2：属性没能成功双向绑定到省市区组件
![image](https://user-images.githubusercontent.com/14839142/93437345-70702200-f8fe-11ea-8dce-58bb87787c98.png)
![image](https://user-images.githubusercontent.com/14839142/93437395-80880180-f8fe-11ea-849a-096287a9f64f.png)

3：尽管有自定义组件，但很多时候表单控件的组合，可能是很复杂，但却一次性的，不封装的，或者说联动过于复杂不好配，这种情况可以用slot单独解决

**Comment by lljj-x** [comment]
1、这里的ui:field配置是ok的，`pcd_input` 组件内的值需要手动的同步到 `formData` 里。

类似如下：你的联级选择组件可以绑定一个计算属性 来获取或者更新 `formData` 的值

```html
<!-- 假设这里的 xx 是你的联级选择组件  -->
<xx :v-model="pcdData"></xx>
```

```js
computed: {
    // 假设这里是你自定义组件中的数据
    pcdData: {
        get() {
            // 可以通过 vueUtils.getPathVal 获取当前节点的值
            return vueUtils.getPathVal(this.rootFormData, this.curNodePath);

            // 或者直接通过 rootFormData 访问
            return this.rootFormData.pcd;
        },
        set(val) {
            // 可以通过 vueUtils.getPathVal 获取当前节点的值
            return vueUtils.setPathVal(this.rootFormData, this.curNodePath, value);

            // 或者直接通过 rootFormData 访问
            return this.rootFormData.pcd = val;
        }
    }
}
```
2、slot 这个你可以贴下代码你期望怎么配置达到什么样的效果。

我理解看起来 `slot ` 差不多是 `ui:field` 的一个变体 ，只是 `field` 为一个组件，可能是如下形式：

```js
{
    "title": "省市区",
    "type": "object",
    "ui:field": "ComponentName", // 配置在这里
    "ui:slotName": "xxx", // 然后再配置具体的具名 slot  <template slot="xxx">xxxxx</template>
    "properties": {
        "p": {
            "title": "省",
            "type": "string"
        }
    }
}
```

联动那个实现是完全遵循  JsonSchema 规范的时候是要通过 `anyOf` 实现确实比较复杂，但是也可以直接通过`ui:fieldStyle` `ui:fieldClass` 来通过样式简单配置，uiSchema 数据的配置也是响应式的  。
