### ISSUE TITLE
vue3、ui框架antd 类型为textarea时UI依然是input框

### ISSUE THREAD

**Issue by hellheaven** [lljj-x/vue-json-schema-form#110]
properties: {
      content1: {
        type: 'string',
        title: 'foo',
        'ui:options': {
            type:'textarea'
        }
      }
}

vue3、ui框架antd
在类型为textarea时，依然是input框。不会多行显示。

**Comment by lljj-x** [comment]
你要查查 antd vue 的配置，textarea 是需要使用a-textarea组件 ，而非如上配置

**Comment by lljj-x** [comment]
是的，默认 string 是使用 antd a-input，type配置是elementUi的配置，antd 使用 a-textarea

```js
{
'ui:widget': 'a-textarea'

}
```

**Comment by hellheaven** [comment]
了解了，谢谢

**Comment by hellheaven** [comment]
已解决

**Comment by lljj-x** [comment]
可以参见这个问题，vue3 antd valueModel 可能有坑

https://github.com/lljj-x/vue-json-schema-form/issues/111#issuecomment-930817473
