### ISSUE TITLE
对array支持配置UI

### ISSUE THREAD

**Issue by chenshuichao** [lljj-x/vue-json-schema-form#117]
类似于将要进行的对object支持配置UI。
object建议配置折叠容器组件collapse；array建议配置table，动态表格组件，可以参考，alibaba/formily

**Comment by chenshuichao** [comment]
请问，这个需求，目前这么配置实现呢？

**Comment by lljj-x** [comment]
type array 配置 ui:widget

**Comment by lljj-x** [comment]
https://github.com/lljj-x/schema-form-components

这类偏业务的是希望有人来贡献代码，这边扩展方法都是类似的
