### ISSUE TITLE
if else这个schema的新特性有没有计划加上去呢

### ISSUE THREAD

**Issue by Wisgon** [lljj-x/vue-json-schema-form#12]
目前有个需求，就是两个有enum属性的select框要进行联动，第一个select框改变了值，要让第二个select的可选内容改变，我目前想到的是schema中的if else属性来实现，不知大神还有没有其他办法。

**Comment by lljj-x** [comment]
暂时应该还是不会支持 Dependencies 和 if else 有时间看看怎么处理比较合适。

就目前来看这里有两个方案：

1、通过配置 schema 属性了实现，因为schema本生也是响应式的。
```js
{
    watch: {
        'formData.select1'() {
            this.schema.xx.xx.enum = newArra;
        }
    }
}
```


2、通过 `ui:field` 把这种需要联动的复制交互单独用自己的组件处理即可

 #11 就像在这个里面类似 

---

我其实比较推荐第二种方案，最近我抽点时间把文档 `ui:field` 的配置完善下，会写两个明确的例子，会包含一个多级联动

**Comment by Wisgon** [comment]
好的，静侯佳音
