### ISSUE TITLE
Playground 和 表单Schema生成器 数据格式不统一

### ISSUE THREAD

**Issue by shirakagi** [lljj-x/vue-json-schema-form#123]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2 ui框架element  vjsf 使用版本v1.9.2

###  问题描述
通过Schema 生成器生成的表单数据在playground中缺少表单数据 formFooter，formProps等

### 如何复现
[playground分享链接](https://form.lljj.me/index.html#/demo?ui=VueElementForm&type=Test&schema=%7B%22type%22%3A%22object%22,%22required%22%3A%5B%5D,%22properties%22%3A%7B%22object_1636959908666x0%22%3A%7B%22title%22%3A%22Object%22,%22type%22%3A%22object%22,%22required%22%3A%5B%5D,%22properties%22%3A%7B%22number_1636959909902x0%22%3A%7B%22title%22%3A%22%E6%95%B0%E5%AD%97%EF%BC%88slider%EF%BC%89%22,%22type%22%3A%22number%22,%22ui%3Awidget%22%3A%22ElSlider%22,%22multipleOf%22%3A1%7D%7D,%22ui%3Aorder%22%3A%5B%22number_1636959909902x0%22%5D%7D%7D,%22ui%3Aorder%22%3A%5B%22object_1636959908666x0%22%5D%7D&formData=%7B%22object_1636959908666x0%22%3A%7B%22number_1636959909902x0%22%3A25%7D%7D&uiSchema=%7B%7D&errorSchema=%7B%7D&formFooter=%7B%22okBtn%22%3A%22adas%22,%22cancelBtn%22%3A%22%E8%BF%99%E4%BA%9B%E6%9D%90%E8%B4%A8%22%7D&formProps=%7B%22labelWidth%22%3A%22152px%22,%22inline%22%3Afalse,%22labelPosition%22%3A%22left%22,%22inlineFooter%22%3Atrue,%22layoutColumn%22%3A2,%22labelSuffix%22%3A%22%2B%2B%2B%22%7D)

### 期望的结果
表单属性应该如何配置和读取展示
我应该采用哪种形式开发 类似于活动编辑器demo中的Schema UIschema独立文件引入 还是直接使用schema生成器生成的数据格式存入json文件进行配置和读取

**Comment by lljj-x** [comment]
schema生成器是实现配置化表单的能力，可以用来辅助生成schema或者做一些可视化的动态表单
