### ISSUE TITLE
customRule中的callback返回undefined

### ISSUE THREAD

**Issue by tocurd** [lljj-x/vue-json-schema-form#124]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2或者vue3、ui框架element antd、vjsf 使用版本说明
vue3 antd tsx
vjsf版本: @lljj/vue3-form-ant 1.9.3

###  问题描述
对错误是什么的清晰简洁的描述。
customRule 中callback是undefined

### 如何复现
可以详细介绍你的复现场景或者相关代码。
```
setup(){
    const customRule = (data) => {
        console.log(data)
    }
    return {
        customRule
    }
},
render(){
      <VueFormAny
	      ref="form"
	      customRule={(data) => this.customRule(data)}
	      modelValue={this.$props.fromData}
	      onChange={(data: { newValue: AnyObject; oldValue: AnyObject }) => {
		      nextTick(() => this.$props.onChange(data.newValue))
	      }}
	      formFooter={this.formFooter}
	      formProps={this.formProps}
	      schema={this.schema} />
}
```

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

### 期望的结果
....
正常使用callback

**Comment by lljj-x** [comment]
antd vue3 是需要使用promise，后面会更新文档

参见：
![image](https://user-images.githubusercontent.com/6283929/142759119-b1c7626b-5fe6-4d11-bafc-b3161ab68b95.png)
