### ISSUE TITLE
如何对接移动端UI组件库？比如vant

### ISSUE THREAD

**Issue by liuliang1356** [lljj-x/vue-json-schema-form#125]
vue2和ui框架对接问题

移动端H5页面如何使用vjsf, 是否需要更换移动端UI框架比如vant,   vant里没有formItem怎么搞?

**Comment by lljj-x** [comment]
不支持。

有兴趣可以尝试修改源码

**Comment by liuliang1356** [comment]
作者能提供个对接移动端UI比如vant的思路？

**Comment by lljj-x** [comment]
vant 这个我没实际使用过，只是简单看了下。
---

目前表单组件结构是 form -> field -> formItem -> widget组件 ，但vant中，formItem 就是实际的输入组件也就是 widget ，所以需要 调整Widget.js，去掉 formItem这一层，可能还会有其它细节的调整，所以就不能复用现有的 core ，需要重新fork一份。

可以自己看看
https://github.com/lljj-x/vue-json-schema-form/blob/master/packages/lib/vue2/vue2-core/src/components/Widget.js#L228

**Comment by liuliang1356** [comment]
感谢

**Comment by lizy-CZ** [comment]
> 

import createVue2Core from '@lljj/vue2-form-core';
const VueForm = createVue2Core(globalOptions);

1. 在 globalOptions 中修改对应的 移动控件名称
2. 为每个控件创建一个 field
