### ISSUE TITLE
表单使用inline的问题

### ISSUE THREAD

**Issue by alicksnake22** [lljj-x/vue-json-schema-form#13]
当一个表单用来当做搜索条件的时候，一般用inline=true，这时候怎么添加两个横向跟在表单之后的重置和保存按钮？（或者说动态添加按钮），目前插件没有按钮的表单控件。

**Comment by lljj-x** [comment]
可以通过配置[scope slot](https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#插槽-scope-slot)覆盖默认的footer
