### ISSUE TITLE
【建议】全局的UploadWidget组件，支持自定义默认文件名

### ISSUE THREAD

**Issue by liyiligang** [lljj-x/vue-json-schema-form#141]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3

###  问题描述
当 formData 中存在 UploadWidget 对应的url时，文件名是默认的 "已上传文件"，是否能加一个以url为参数的自定义文件名的接口？

### 如何复现
`       if (curModelValue) {
                return [{
                    name: '已上传文件',
                    url: curModelValue
                }];
            }
`

### 期望的结果
`       if (curModelValue) {
                return [{
                    name: func(curModelValue),
                    url: curModelValue
                }];
            }
`

**Comment by lljj-x** [comment]
现在应该是可以的。

这里是优先使用外部接口传入的 fileList ，否则才会默认一个 `已上传文件`

```js
this.$attrs.fileList || [{ name: '已上传文件', url: curModelValue }]
```
