### ISSUE TITLE
动态渲染select数据示例渲染成input

### ISSUE THREAD

**Issue by zhen-clam** [lljj-x/vue-json-schema-form#142]
### vue和ui框架
vue2，ui框架element 使用版本说明

###  问题描述
根据官网示例动态渲染select下拉数据，select下拉变成input框并且options无法渲染

### 如何复现
![image](https://user-images.githubusercontent.com/60591959/143542147-effc0adc-a678-4215-9503-9143c237d957.png)
动态数据渲染select下拉框数据

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等
https://codepen.io/pen/

### 期望的结果
动态渲染select下拉框数据

**Comment by lljj-x** [comment]
感谢反馈，vue在运行时编译HTML template不能使用驼峰，后续文档会更新

----

调整如下即可

![image](https://user-images.githubusercontent.com/6283929/143666063-39cfd964-b249-48c6-a06b-ca354433b038.png)
