### ISSUE TITLE
vue2-form-core 取消注册全局组件

### ISSUE THREAD

**Issue by Luizzzzzzz** [lljj-x/vue-json-schema-form#143]
https://github.com/lljj-x/vue-json-schema-form/blob/e93294f097c0be4191ca383dc53d83d23652d055/packages/lib/vue2/vue2-core/src/index.js#L30-L32

请问此处为什么要注册为全局组件？我尝试注释此处后，依旧可以渲染。
全局组件名称可能会导致不必要的冲突。

**Comment by lljj-x** [comment]
这里是为了外部自定义 widget 可以直接调用内置的这些widget。

注释后可以渲染是因为内部是使用组件引用去渲染并不依赖注册组件。

---

命名冲突的问题可以考虑过通过 use install添加个prefix配置，不过优先级不高，目前的命名相对来说很难冲突
