### ISSUE TITLE
期待能支持AJV的$data扩展

### ISSUE THREAD

**Issue by wanjidong** [lljj-x/vue-json-schema-form#144]
期待能支持AJV的扩展，如样样例代码，可以实现一些两个字段关联验证的功能，样例代码如下
const Ajv = require("ajv")
const ajv = new Ajv({$data: true})

const schema = {
  properties: {
    username : {
      type : "string",
      title : "用户名"
    },
    password: {
      type: "string",
      title : "密码"
    },
    confirmPassword: {
      const: {"$data": "1/password"},
      title : "确认密码"
    }
  },
}

const validData = {
  username: "user",
  password : "test",
  confirmPassword : "test"
}

console.debug("schema : \n" + JSON.stringify(schema,null,4))
console.debug("\nvalid data : \n" + JSON.stringify(validData,null,4))
console.debug("\nvalid result : " + ajv.validate(schema, validData))

const invalidData = Object.assign(validData, {confirmPassword : "dddd"})
console.debug("\nvalid data : \n" + JSON.stringify(invalidData,null,4))
console.debug("\nvalid result : " + ajv.validate(schema, invalidData))

[ajv-demo.zip](https://github.com/lljj-x/vue-json-schema-form/files/7690039/ajv-demo.zip)
....

**Comment by lljj-x** [comment]
这个不打算支持了，主要是这些语法不仅仅只是数据校验还会需要更新表单渲染逻辑，ajv的扩展语法是直接基于标准语法的，比如都是使用 const 字段来，这部分是属于非标准规范，表单渲染的时候区分这部分逻辑就不太合适

原本以为只是在校验上的区别，可以通过ajv自己去抹平差异，现在看来还是不支持了。
