### ISSUE TITLE
重复渲染时，文件上传的值改变时，没有更新新值

### ISSUE THREAD

**Issue by ChainsDW** [lljj-x/vue-json-schema-form#146]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2或者vue3、ui框架element antd、vjsf 使用版本说明

###  问题描述
对错误是什么的清晰简洁的描述。

### 如何复现
可以详细介绍你的复现场景或者相关代码。

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

### 期望的结果
....
![image](https://user-images.githubusercontent.com/37797813/146157445-e463749e-71fb-49f1-915d-26278525d19d.png)
vue-json-schema-form/packages/lib/vue3/vue3-form-element/src/config/widgets/UploadWidget/index.js
35行。如果prop新值传进来，curModelValue不会更新，导致文件列表不会更新，建议改成计算属性，不过不确定会不会影响上传

**Comment by lljj-x** [comment]
这里不是一个响应式的 ，可以查考之前的 issue

**Comment by lljj-x** [comment]
后面我还是更新下吧

**Comment by ChainsDW** [comment]
我看加个v-if或者用不同的key让他强制更新是可以解决这个问题的

**Comment by lljj-x** [comment]
可以，你这样是强行触发了组件重新创建，后面我做个优化版本把
