### ISSUE TITLE
如何根据某个字段选择的值生成不同的表单

### ISSUE THREAD

**Issue by wchpeng** [lljj-x/vue-json-schema-form#147]
### vue和ui框架
vue2 element-ui

###  问题描述
1.如何根据某个字段选择的值生成不同的表单。比如有个字段：类型，select 框选择不同的类型，下方生成的表单也会相应变化
2.能不能对生成的表单导入json值，导入后的值会渲染在页面上

### 期望的结果
配置字段：类型，当选择或填写‘类型’的值时：
类型==1：下方有名字、年龄字段
类型==2：下方有地区、电话、性别...
....

**Comment by lljj-x** [comment]
你可以先看看文档 有对应的内容
