### ISSUE TITLE
请教一下ui:options onchange如何传入函数

### ISSUE THREAD

**Issue by Zachary-zm** [lljj-x/vue-json-schema-form#148]
### vue和ui框架
vue2、ui框架element

###  问题描述
请教一下ui:options onchange如何传入函数

### 如何复现
json schema不知道如何传入function

### 期望的结果
我两个下拉框，选择一个，希望联动另外一个赋值，并且无法选择

**Comment by lljj-x** [comment]
不支持纯json，只能是ui配置js语法

```js
onChange({ curVal, preVal, parentFormData, rootFormData }) {
      console.log('change:', curVal, preVal, parentFormData, rootFormData);
  }
```

**Comment by Zachary-zm** [comment]
> 不支持纯json，只能是ui配置js语法
> 
> ```js
> onChange({ curVal, preVal, parentFormData, rootFormData }) {
>       console.log('change:', curVal, preVal, parentFormData, rootFormData);
>   }
> ```

好的吧，因为我这不支持代码逻辑的修改。不知道有什么办法实现我两个下拉框，选择一个，希望联动另外一个下拉框选中赋值（文本框也行），并且无法选择

**Comment by lljj-x** [comment]
如果第一个下拉框的options是几个固定的值，可以使用anyOf语法。
如果是一些动态的options还是需要onchange，可以考虑把json schema 和uischema分开配置

**Comment by Zachary-zm** [comment]
> 的options是几个固定的值，可以使用anyOf语法。

anyOf的话是在一个属性里面操作的吧？ 我现在是想 {a: 1, b: 3}  a选择1，b自动默认选择到3。
uischema的话是不是一样不支持function的写法，我看示例里面ui schema不支持哇

**Comment by lljj-x** [comment]
anyOf ，可以搭配 const 字段，可以看看demo

支持function，使用js文件都可以function，除非你只能json

**Comment by Zachary-zm** [comment]
> anyOf ，可以搭配 const 字段，可以看看demo
> 
> 支持function，使用js文件都可以function，除非你只能json

好勒，谢谢。。目前看了一圈都不是很支持两个属性之间的联动。
是的，我只能json，因为无数的表单，如果js去控制就太特殊化了。
