### ISSUE TITLE
vu3版本，form表单中只有一个单行文本输入字段时，回车后页面会刷新

### ISSUE THREAD

**Issue by DWL716** [lljj-x/vue-json-schema-form#150]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3 、form原生表单默认事件

###  问题描述
只有一个单行文本输入字段时，回车后页面会刷新

### 如何复现
例如 jsonschema 是这种的 只有一个属性，这样ui只会渲染一个input输入框，然后将input框进行输入状态再回车页面就会刷新，并且url上面会多一个 ？符号
"properties": {
        "telephone": {
            "type": "string",
            "title": "Telephone"
        }
    }

### 期望的结果
....

**Comment by DWL716** [comment]
一些解决方案 https://stackoverflow.com/questions/1370021/why-does-forms-with-single-input-field-submit-upon-pressing-enter-key-in-input#
可以通过自定义组件，然后通过拦截jsonschema 判断有几个属性，当如果只有一个那对uischema进行修改，将只有一个属性的schema组件重新定向到自己写的ui上面

**Comment by lljj-x** [comment]
新版本会默阻止submit
