### ISSUE TITLE
有计划支持NaiveUI吗？

### ISSUE THREAD

**Issue by 551685830** [lljj-x/vue-json-schema-form#152]
有计划增加对NaiveUI的支持吗？我目前调研下来可能会选择基于NaiveUI来搭建生态，但关于自定义表单还是觉得你这个实际较好。

**Comment by lljj-x** [comment]
看了下 NaiveUI 还是比较容易支持的 ，可以支持一波，估计在春节后，三月份吧 。

**Comment by 551685830** [comment]
谢谢，非常期待！

**Comment by lljj-x** [comment]
需要使用 Naive ui 2.25.3 以上版本，详情参考 


https://github.com/TuSimple/naive-ui/issues/2486

**Comment by lljj-x** [comment]
naive ui已适配
https://form.lljj.me/v3/#/demo?ui=VueNaiveForm&type=Simple
