### ISSUE TITLE
slot参数如何传

### ISSUE THREAD

**Issue by petersam11** [lljj-x/vue-json-schema-form#153]
我自定义了个Widget , 配置了个组件, 但这个组件我要传入slot, 这时候要怎么配置呀? 文档找了很久没找到

**Comment by lljj-x** [comment]
https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#ui-schema-slots

slot 需要render函数

**Comment by hlzzd666** [comment]
> https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#ui-schema-slots
> 
> slot 需要render函数

 renderChildren(h) {
            return [
                h('span', {
                    slot: 'suffix',
                }, '后缀')
            ];
        }
我看文档是这么用的，但是我的出不来是什么原因么，有具体的使用例子么
