### ISSUE TITLE
onChange事件中enumOptions值获取

### ISSUE THREAD

**Issue by I-am-so-cute** [lljj-x/vue-json-schema-form#155]
###  问题描述
请问配置SelectWidget组件的onChange事件中，可以取到组件对应的enumOptions的值吗？如果不可以的话，请问有其他的获取渠道吗

**Comment by lljj-x** [comment]
onChange 是不能获取到的，不过 `enumOptions` 是你外面传进去的，现在又需要在外面获取感觉是不是可以直接拿到呢 。

你可以描述下你的场景

**Comment by lljj-x** [comment]
`onChange` 是所有的输入组件值改变统一触发的所有不会有这些参数，一定要的话 你可以考虑自定义一个 CustomSelectWidget  组件内部触发一个事件抛出 options 的值

**Comment by I-am-so-cute** [comment]
我找到一个办法了，直接this.uiSchema["ui:enumOptions"]，this.uiSchema能获取到当前组件的uiSchema，当然也可以获取到你其他定义的属性。

感谢回复！！

**Comment by I-am-so-cute** [comment]
使用场景：
select组件绑定只需要`label`和`value`，但是想让每一项多绑定其他属性，例如`describe`。
```
fruitDate=[
  label:'apple',
  value:'1',
  describe:'red fruit',
]
```
当select发生改变后，显示最新的水果描述
```
uiSchema: {
  fruit:{
      "ui:widget": "SelectWidget",
      "ui:options": {
          onChange({ curVal, preVal, parentFormData, rootFormData }) {
              let fruitData = this.uiSchema["ui:enumOptions"];
              var index = periodArr.findIndex((x) => x.label === curVal);
             console.log(periodArr[index].describe);
          }
      }
  }
}
```

**Comment by lljj-x** [comment]
你这样做可以解决问题，不过这个算是个骚操作吧，之所以你的 `this.uiSchema` 可以访问到组件内的值，是因为内部直接 `self.onChange` 去执行的回调。

后面有兴趣的话还是建议去自定义 widget 内部推出这个值
