### ISSUE TITLE
Anyof默认值匹配

### ISSUE THREAD

**Issue by ChandlerMing** [lljj-x/vue-json-schema-form#157]
### vue和ui框架
vue2、element 、vjsf 1.5.0

###  问题描述
计算默认值时会去掉require来匹配anyof里面的options，导致数据回填后增加了预期之外的默认值字段

### 如何复现
https://codepen.io/ChandlerMing/pen/PoOmKOz?editors=1011

### 期望的结果
使用anyof的schema数据回填后保持不变

**Comment by lljj-x** [comment]
更新最新版本配置 strict-mode 

```js
<vue-form
strict-mode
...
>

</vue-form>

**Comment by lljj-x** [comment]
https://codepen.io/ljj/pen/zYPRgYX?editors=1010

**Comment by ChandlerMing** [comment]
Get 老哥TQL~
