### ISSUE TITLE
请问支持map这种key-value形式的吗？

### ISSUE THREAD

**Issue by gujiale** [lljj-x/vue-json-schema-form#158]
我需要用到类似http协议header这种key-value的形式，请问下支持吗？ 要怎么写？
![image](https://user-images.githubusercontent.com/5484256/154286492-e8925c4e-f54c-4e68-b0ee-3fad5027c8ec.png)

### 期望的结果
....

**Comment by lljj-x** [comment]
不支持，可以考虑转换成数组，数组item为一个object 包含key value

标准规范参考这个：
https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties

**Comment by gujiale** [comment]
好的，感谢！
