### ISSUE TITLE
Number Enum(Select)控件如何设置clearable以及多选？

### ISSUE THREAD

**Issue by alicksnake22** [lljj-x/vue-json-schema-form#16]
Number Enum(Select)控件如何设置clearable以及多选？

**Comment by lljj-x** [comment]
已经解决了吗 ？

这里如果配置为多选的话应该是数组了，而不能是 Number，大致形式如下：

```js
    multiSelect: {
        type: 'array',
        title: 'A multiple choices list',
        items: {
            type: 'string',
            enum: [
                'foo',
                'bar',
                'fuzz',
                'qux'
            ]
        },
        uniqueItems: true
    }
```
https://codepen.io/ljj/pen/wvGONGv

--
但是这里多选默认是渲染为 checkbox多选，不过配置成 select会有些问题，你可以先打开这个问题 我后面会处理。

**Comment by alicksnake22** [comment]
@lljj-x 我用了ui:attrs配置了clearable和multiply发现可以

**Comment by lljj-x** [comment]
@alicksnake22  对，attrs 可以透传，新的版本我合并了 attrs 和 props，就像你写模板组件一样不用区分。
