### ISSUE TITLE
发现表单布局配置layoutColumn 好像对自定义组件不支持

### ISSUE THREAD

**Issue by Seannie** [lljj-x/vue-json-schema-form#161]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/17930221/156188778-455cd8ac-204f-4760-bbc2-003c6f148580.png">

**Comment by lljj-x** [comment]
参考这个哈 
https://github.com/lljj-x/schema-form-components

**Comment by Seannie** [comment]
感谢

**Comment by Seannie** [comment]
> > 参考这个哈 https://github.com/lljj-x/schema-form-components
> 
> 看了一下demo，好像这个tab也没有渲染到layoutColumn中定义的布局样式
