### ISSUE TITLE
可以 支持 vue2 + antdv 1.x 版本吗？

### ISSUE THREAD

**Issue by wang3690004** [lljj-x/vue-json-schema-form#165]
### vue和ui框架
vue2   ant design vue 1.8

###  问题描述
可以支持 vue2 antdv1.8 版本的配置吗

### 期望的结果
支持

**Comment by lljj-x** [comment]
不支持的哈，目前也没有适配计划了

**Comment by zhanzekun** [comment]
@lljj-x  这里不支持的原因是什么？是因为antdv1.x的版本适配起来成本过高吗？

我想采用vjsf这套方案，但是我们确实在vue2 + antdv1.x，如果成本并不是很高，我自行适配也Ok的。
想听听你的看法（我猜如果成本低，是不是你当初就顺手适配了

**Comment by wang3690004** [comment]
> @lljj-x 这里不支持的原因是什么？是因为antdv1.x的版本适配起来成本过高吗？
> 
> 我想采用vjsf这套方案，但是我们确实在vue2 + antdv1.x，如果成本并不是很高，我自行适配也Ok的。 想听听你的看法（我猜如果成本低，是不是你当初就顺手适配了

请问除了这个你有找到其他的方案吗？
感觉原作者应该不会再搞这个了，    我现在再想办法学习研究他的源码 就是core+框架适配的 看看能不能用来适配antdv1.x

**Comment by zhanzekun** [comment]
我看了一圈市面上相关的json schema form方案，支持vue2的不多

**Comment by zhanzekun** [comment]
> > @lljj-x 这里不支持的原因是什么？是因为antdv1.x的版本适配起来成本过高吗？
> > 我想采用vjsf这套方案，但是我们确实在vue2 + antdv1.x，如果成本并不是很高，我自行适配也Ok的。 想听听你的看法（我猜如果成本低，是不是你当初就顺手适配了
> 
> 请问除了这个你有找到其他的方案吗？ 感觉原作者应该不会再搞这个了， 我现在再想办法学习研究他的源码 就是core+框架适配的 看看能不能用来适配antdv1.x

如果是指vue2下的json-schema form，你可以看看阿里出的formily core + 社区适配的antdv版本
