### ISSUE TITLE
希望anyOf模块在选择组件触发onChang事件时返回anyOf所在节点的路径及所选择组件的具体值。

### ISSUE THREAD

**Issue by gyt0412** [lljj-x/vue-json-schema-form#166]
希望解决的场景：
有一个数组结构，数组中的item包含一个字段，该字段使用了anyOf协议。
现在对anyOf组件添加了监听，当选择一个anyOf选项时，触发一个逻辑。
现在是无法知道用户到底从哪个数组item中触发了对应的逻辑。

要实现的功能场景见下图：
![image](https://user-images.githubusercontent.com/12298644/161381282-25f3385b-7521-4bcd-993c-b4ba5921aa22.png)
此问题已在Q群中交流过，如果有疑问，欢迎联络QQ号：2350772202

另外现在onChange回调参数仅返回curVal，这个curVal实际上是列表对象的索引位置，如果要判断用户选择了哪个具体的组件，还需要从原始的anyOf列表中取回。如下图：
<img width="749" alt="image" src="https://user-images.githubusercontent.com/12298644/161381386-11f1e206-8746-40ea-94b3-d4981c55fb66.png">

![image](https://user-images.githubusercontent.com/12298644/161381335-e165bbf2-63ec-4a46-96cd-9ec89e9d45e0.png)
如果能直接返回所选择的具体组件的数据，会更加便利。

**Comment by lljj-x** [comment]
升级到  `1.12.1` 已经解决了

另外提示下，在 anyOf change时间中的 `parentFormData` 并不一定是option节点的上一级
