### ISSUE TITLE
element plus 按需导入时工作不正常

### ISSUE THREAD

**Issue by techzhou** [lljj-x/vue-json-schema-form#169]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3、element plus、unplugin-vue-components

###  问题描述
[element plus 按需导入](https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5
) 时，无法解析到element组件

vue3utils使用resolvecomponent，无法解析到按需的element组件，考不考虑采用import('element-plus/es/components.....')这种import方式支持下element plus 按需导入的情况

### 如何复现
无

### 期望的结果
element plus 按需导入时正常工作

**Comment by lljj-x** [comment]
vjsf 表单是需要依靠外部的全局ui组件，unplugin-vue-components 是把你在组件级别自动import。

所以你只需要对vjsf 依赖的组件做个全局注册。
```js
// elForm 也可以是异步组件
app.component('elForm', elForm)

// 或者
app.use(elForm)
```
