### ISSUE TITLE
能不能把可视化编辑jsonSchema和jsonSchema定制表单结合在一起

### ISSUE THREAD

**Issue by MHappy135246** [lljj-x/vue-json-schema-form#17]
把可视化编辑jsonSchema和jsonSchema定制表单结合在一起的时候，type的切换可以切换组件，这个时候切换对应的组件（ui-schema写在jsonSchema中），可以吗

**Comment by lljj-x** [comment]
你的意思是说 你的页面交互存在一个type的选择，然后使用不同的组件渲染吗 ？

**Comment by MHappy135246** [comment]
目的是脱离codeEditor；比如有些人不太了解jsonSchema，我们可以通过可视化编辑器http://blog.giscafer.com/sinokit/#/./components/jsonschema-editor编辑得出来一个jsonSchema但是此时我们还要在codeEditor里书写对应的ui-schema，我的意思是我可能还需要可视化编辑器来编辑出一个ui-schema是不是太麻烦了，而且可能还不容易实现

**Comment by MHappy135246** [comment]
目的是脱离codeEditor；比如有些人不太了解jsonSchema，我们可以通过[可视化编辑器](http://blog.giscafer.com/sinokit/#/./components/jsonschema-editor)编辑得出来一个jsonSchema但是此时我们还要在codeEditor里书写对应的ui-schema，我的意思是我可能还需要可视化编辑器来编辑出一个ui-schema是不是太麻烦了，而且可能还不容易实现

**Comment by lljj-x** [comment]
懂了，想要通过可视化编辑出JSON Schema和uiSchema，省去了需要先学习这些基本概念的成本 。

考虑过实现一个 类似阿里 [form render 在线编辑器](https://x-render.gitee.io/schema-generator/)，这个已经是一个很好的参考例子，有时间会去逐步实现。

**Comment by MHappy135246** [comment]
Thank you very much.Look forward to your success

**Comment by lljj-x** [comment]
目前已经实现了可视化 schema的生成，组件会逐步完善，整体的功能已经可用。

如下可尝试：
https://form.lljj.me/schema-generator.html

**Comment by MHappy135246** [comment]
感谢
