### ISSUE TITLE
arrar > items > select默认选中第一项

### ISSUE THREAD

**Issue by Aaron-9503** [lljj-x/vue-json-schema-form#171]
https://form.lljj.me/index.html#/demo?type=Test&schema=%7B%22type%22%3A%22object%22,%22required%22%3A%5B%5D,%22properties%22%3A%7B%22array_1649680259177x0%22%3A%7B%22title%22%3A%22Array%22,%22type%22%3A%22array%22,%22items%22%3A%7B%22type%22%3A%22object%22,%22required%22%3A%5B%22string_1649680693799x0%22%5D,%22properties%22%3A%7B%22string_1649680693799x0%22%3A%7B%22title%22%3A%22%E5%8D%95%E9%80%89%28Select%29%22,%22type%22%3A%22string%22,%22ui%3Awidget%22%3A%22SelectWidget%22,%22enum%22%3A%5B%221%22,%222%22,%223%22%5D,%22enumNames%22%3A%5B%22%E4%B8%80%22,%22%E4%BA%8C%22,%22%E4%B8%89%22%5D%7D,%22string_1649680658905x0%22%3A%7B%22title%22%3A%22%E8%BE%93%E5%85%A5%E6%A1%86%22,%22type%22%3A%22string%22,%22ui%3Aoptions%22%3A%7B%22placeholder%22%3A%22%E8%AF%B7%E8%BE%93%E5%85%A5%22%7D%7D%7D,%22ui%3Aorder%22%3A%5B%22string_1649680693799x0%22,%22string_1649680658905x0%22%5D%7D,%22uniqueItems%22%3Afalse,%22minItems%22%3A1%7D%7D,%22ui%3Aorder%22%3A%5B%22array_1649680259177x0%22%5D%7D&uiSchema=%7B%7D&formFooter=%7B%7D&formProps=%7B%22inline%22%3Atrue,%22labelWidth%22%3A%22392px%22,%22labelSuffix%22%3A%22%EF%BC%9A%22%7D

**Comment by lljj-x** [comment]
如果单选项是一个required的，会默认选中第一个

**Comment by lljj-x** [comment]
https://form.lljj.me/index.html#/demo?ui=VueElementForm&type=Test&schema=%7B%22type%22%3A%22object%22,%22required%22%3A%5B%5D,%22properties%22%3A%7B%22array_1649680259177x0%22%3A%7B%22title%22%3A%22Array%22,%22type%22%3A%22array%22,%22items%22%3A%7B%22type%22%3A%22object%22,%22properties%22%3A%7B%22string_1649680693799x0%22%3A%7B%22title%22%3A%22%E5%8D%95%E9%80%89%28Select%29%22,%22type%22%3A%22string%22,%22ui%3Awidget%22%3A%22SelectWidget%22,%22enum%22%3A%5B%221%22,%222%22,%223%22%5D,%22enumNames%22%3A%5B%22%E4%B8%80%22,%22%E4%BA%8C%22,%22%E4%B8%89%22%5D%7D,%22string_1649680658905x0%22%3A%7B%22title%22%3A%22%E8%BE%93%E5%85%A5%E6%A1%86%22,%22type%22%3A%22string%22,%22ui%3Aoptions%22%3A%7B%22placeholder%22%3A%22%E8%AF%B7%E8%BE%93%E5%85%A5%22%7D%7D%7D,%22ui%3Aorder%22%3A%5B%22string_1649680693799x0%22,%22string_1649680658905x0%22%5D%7D,%22uniqueItems%22%3Afalse,%22minItems%22%3A1%7D%7D,%22ui%3Aorder%22%3A%5B%22array_1649680259177x0%22%5D%7D&formData=%7B%22array_1649680259177x0%22%3A%5B%7B%7D%5D%7D&uiSchema=%7B%7D&errorSchema=%7B%7D&formFooter=%7B%7D&formProps=%7B%22labelWidth%22%3A%22392px%22,%22inline%22%3Atrue,%22labelPosition%22%3A%22top%22,%22inlineFooter%22%3Afalse,%22layoutColumn%22%3A1,%22labelSuffix%22%3A%22%EF%BC%9A%22%7D

**Comment by Aaron-9503** [comment]
有办法解决吗？如果不想要这个效果，看起来很奇怪

**Comment by lljj-x** [comment]
目前不行，后面加个参数来控制吧

**Comment by Aaron-9503** [comment]
什么时候能加上，期待呀

**Comment by lljj-x** [comment]
这周吧

**Comment by lljj-x** [comment]
`1.13.0` 支持在formProps配置`defaultSelectFirstOption`
