### ISSUE TITLE
anyOf 切换选项时，设置的同名field值并没有更新

### ISSUE THREAD

**Issue by JackZhang1988** [lljj-x/vue-json-schema-form#174]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3、ui框架antd 2.2.8

###  问题描述
anyOf 切换选项时，设置了一个隐藏的type， 示例中在切换个人资料设置方式时，userInfo中的type值并没有更新，而是始终保持在第一次设置的值

### 如何复现

https://form.lljj.me/v3/#/demo?ui=VueAntForm&type=Test&schema={%22title%22:%22%E4%BA%BA%E5%91%98%E4%BF%A1%E6%81%AF%22,%22type%22:%22object%22,%22properties%22:{%22userInfo%22:{%22title%22:%22%E4%B8%AA%E4%BA%BA%E8%B5%84%E6%96%99%E8%AE%BE%E7%BD%AE%E6%96%B9%E5%BC%8F%22,%22anyOfSelect%22:{%22ui:widget%22:%22RadioWidget%22},%22anyOf%22:[{%22title%22:%22%E9%80%9A%E8%BF%87%E7%94%A8%E6%88%B7%E5%90%8D%E8%AE%BE%E7%BD%AE%22,%22required%22:[%22firstName%22],%22properties%22:{%22type%22:{%22ui:hidden%22:true,%22type%22:%22string%22,%22default%22:%22userInfo%22},%22firstName%22:{%22type%22:%22string%22,%22title%22:%22%E5%90%8D%E5%AD%97%22,%22default%22:%22Jun%22},%22lastName%22:{%22type%22:%22string%22,%22title%22:%22%E5%A7%93%22,%22default%22:%22Liu%22}}},{%22title%22:%22%E9%80%9A%E8%BF%87%E7%94%A8%E6%88%B7id%E8%AE%BE%E7%BD%AE%22,%22properties%22:{%22type%22:{%22ui:hidden%22:true,%22type%22:%22string%22,%22default%22:%22userId%22},%22idCode%22:{%22type%22:%22string%22,%22title%22:%22ID%22,%22default%22:%2210086%22}}}]}}}&formData={%22price%22:99999.99,%22userInfo%22:{%22type%22:%22userInfo%22,%22firstName%22:%22Jun%22,%22lastName%22:%22Liu%22},%22url%22:%22https://lljj.me%22,%22projects%22:[{%22url%22:%22https://www.demo.com%22}]}&uiSchema={}&errorSchema={}&formFooter={%22formItemAttrs%22:{%22wrapperCol%22:{%22span%22:24,%22offset%22:0}}}&formProps={%22inline%22:false,%22labelPosition%22:%22top%22,%22inlineFooter%22:false,%22layoutColumn%22:1,%22labelCol%22:{%22span%22:10},%22wrapperCol%22:{%22span%22:24}}

### 期望的结果
anyOf切换不同选项时，需要更新同名的field的值
....
![image](https://user-images.githubusercontent.com/1697710/162931868-c3e0e837-8951-4dbe-86af-9e29d4cbae14.png)

**Comment by lljj-x** [comment]
```js
"type": {
      "ui:hidden": true,
      "type": "string",
      "default": "userId"
  }
```


正确形式如下 ✅
```js
"type": {
      "ui:hidden": true,
      "type": "string",
      "const": "userId",
      "default": "userId"
  }
```
