### ISSUE TITLE
ui:hidden支持函数格式，扩展ui:disabled也支持函数格式，有相关配置说明吗 

### ISSUE THREAD

**Issue by aadelina** [lljj-x/vue-json-schema-form#176]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2或者vue3、ui框架element antd、vjsf 使用版本说明

###  问题描述
对错误是什么的清晰简洁的描述。

### 如何复现
可以详细介绍你的复现场景或者相关代码。

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

### 期望的结果
....

**Comment by lljj-x** [comment]
只有 hidden 支持函数，其它的暂时不支持只能通过 表达式
