### ISSUE TITLE
VueForm使用过程中报了很多警告：没有找到 element-ui 的组件，Unknow custom elememt: <el-option>

### ISSUE THREAD

**Issue by cquptzsn** [lljj-x/vue-json-schema-form#178]
Unknown custom element: <el-form> - did you register the component correctly? For recursive components, make sure to provide the "name" option
Unknown custom element: <el-form-item> - did you register the component correctly? For recursive components, make sure to provide the "name" option
...

**Comment by lljj-x** [comment]
依赖的ui库组件 需要自己全局注册哈

**Comment by cquptzsn** [comment]
解决
