### ISSUE TITLE
大佬，按照文档的demo代码，enum、enumNames 字段无法显示，只显示了一个 radio，并没有显示3个

### ISSUE THREAD

**Issue by cquptzsn** [lljj-x/vue-json-schema-form#179]
![image](https://user-images.githubusercontent.com/61876714/164650207-9920bd7a-221f-4202-8dba-3534c2d873af.png)

![image](https://user-images.githubusercontent.com/61876714/164650277-4eb485f8-a992-47f8-b65c-2081e62a9b68.png)

**Comment by cquptzsn** [comment]
`<template>
  <div class="wrapper">
    <vue-form 
      v-model="formData" 
      :schema="schema" 
      :ui-schema="uiSchema" 
    />
  </div>
</template>

<script>
import 'element-ui/lib/theme-chalk/index.css'
import  VueForm  from '@lljj/vue-json-schema-form'
import qs from 'qs'
export default {
  components: { 
    VueForm, 
  },
  data() {
    return {
      formData: {},
      schema: {
        type: 'object',
        required: [],
        properties: {
          numberEnumRadio: {
            type: 'number',
            title: '通过组件名(重置为 Radio 渲染)',
            enum: [1, 2, 3],
            enumNames: ['Radio - 1', 'Radio - 2', 'Radio - 3']
          }
        }
      },
      uiSchema: {
        numberEnumRadio: {
            'ui:widget': 'el-radio'
        }
      }
    };
  },
};
</script>

<style scoped>
  .wrapper {
    padding: 100px;
    background-color: white;
  }
  .info-tip {
    font-size: 14px;
    color: red;
  }
  .formSchema {
    margin: 20px 0px;
  }
  .wrapper .linkurl {
    margin-top: 40px;
  }
</style>`

**Comment by cquptzsn** [comment]
[https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89widget](url)

**Comment by cquptzsn** [comment]
把 :ui-schema="uiSchema"  删掉就可以正常显示。。。

**Comment by lljj-x** [comment]
用 `RadioWidget` ，el redio 参数不太一致

```js
 numberEnumRadio: {
      'ui:widget': 'RadioWidget'
  }

```

**Comment by cquptzsn** [comment]
> 用 `RadioWidget` ，el redio 参数不太一致
> 
> ```js
>  numberEnumRadio: {
>       'ui:widget': 'RadioWidget'
>   }
> ```
大佬，我这边vue项目是用的另一个组件库 MTD，因此报了一个这样的警告，问题还是无法解决，应该怎样注册一个 RadioWidget 组件呢？是element-ui 的 radio 组件吗？
![image](https://user-images.githubusercontent.com/61876714/164954566-f7baf132-7e14-424f-b301-41571d9148aa.png)

**Comment by lljj-x** [comment]
建议先看看文档哈

**Comment by lljj-x** [comment]
自定义 widget 部分

**Comment by cquptzsn** [comment]
> 自定义 widget 部分

谢谢
