### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by KevinJJH** [lljj-x/vue-json-schema-form#18]
有些属性，在你文档上我没看拿到,例如definitions，有没有交流群，QQ之类的呢，有问题也好交流，有些属性真不清楚是啥意思,
还有自定义Widget，只能支持原生的button吗，我如果要放置一个element button，应该怎么弄呢

**Comment by lljj-x** [comment]
刚新建了一个 ，QQ群 146845780

另外这个 definitions 是JSON Schema的语法，可以用来定义一些重复的引用 。

自定义Widget 可以直接 ElButton就可以了。
