### ISSUE TITLE
vue3 使用 SchemaField 报错

### ISSUE THREAD

**Issue by Gaofancy** [lljj-x/vue-json-schema-form#180]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3、ui框架antd、vjsf 使用版本：1.12.0

###  问题描述
![image](https://user-images.githubusercontent.com/13410631/165068450-12e4fa17-bff3-497f-8f04-44d3bfcfec91.png)

<img width="739" alt="image" src="https://user-images.githubusercontent.com/13410631/165068571-41165eca-1087-43ab-95f7-c95f37c7105e.png">

**Comment by lljj-x** [comment]
对比下框架内部的参数和你传的参数
