### ISSUE TITLE
自定义 widget 无法获取 schema

### ISSUE THREAD

**Issue by lizy-CZ** [lljj-x/vue-json-schema-form#181]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2或者vue3、ui框架element antd、vjsf 使用版本说明

vue3 element-plus

###  问题描述
import {fieldProps, formUtils} from '@lljj/vue3-form-element';
const props = defineProps({
    ...fieldProps
});

自定义 widget 无法获取 schema
props.schema // {}

Field 可以
props.schema // 有值

### 如何复现
可以详细介绍你的复现场景或者相关代码。

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

### 期望的结果
widget 也能获取 props.schema

**Comment by lljj-x** [comment]
`Widget` 是一个脱离了schema场景的 **纯输入组件**，只是一个v-model，所以和schema 无关，需要的参数都应该是 props 传进来。

但看你上面在使用 fieldProps ，你应该是想自定义 Filed，使用 ui:filed

**Comment by lljj-x** [comment]
6
