### ISSUE TITLE
vue2 UploadWidget 当必填校验的时候，上传成功后warning不会取消

### ISSUE THREAD

**Issue by anlia260** [lljj-x/vue-json-schema-form#183]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2，element-ui

###  问题描述
当必填校验的时候，上传成功后warning不会自动消失，但是点击submit可以通过校验。

### 如何复现

[在这个demo当中](https://form.lljj.me/#/demo?type=Upload)，我加上
```
   required: [
      'imgUrl',
    ],
```

1. 清空默认值
2. 点击提交
3. 校验，出现必填warning
4. 上传
5. demo中的地址上传不成功，然后我本地换了一个接口测试，上传成功后，warning依然不会显示

### 期望的结果
当上传成功后，可以立即触发校验，让warn消失

**Comment by lljj-x** [comment]
这个其实是ui组件库的校验逻辑，这里是 elementUi ，所以你可以按照elementUi 的思路先处理下 

---

可以可以框架内部优化下
