### ISSUE TITLE
如何替换掉内置的 widget/field ？

### ISSUE THREAD

**Issue by lizy-CZ** [lljj-x/vue-json-schema-form#184]
由于我的 schema 没有写 "ui:widget"/"ui:field" 都是用默认的渲染，但现在想替换掉内置的 widget/field, 例如：编写一个自定义的 InputWidget，来替换掉内置的 InputWidget。

我试过
```
import { InputWidget } from '@fex/vue-schema-form';

Vue.component('InputWidget', InputWidget);
```
试图替换，但无效

**Comment by lljj-x** [comment]
不支持

---
需要的话你应该基于 base 自己构建一份

**Comment by lizy-CZ** [comment]
好的，已知悉
