### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by lljj-x** [lljj-x/vue-json-schema-form#19]
- [x] 数组ui配置支持 $index 占位符
- [x] 所有的ui配置都放开支持表达式配置
- [x] array 类型，支持直接配置 ui:widget

- [x] 默认集成一个 upload widget组件
- [x] anyOf 做切换时不在移除已输入的相同字段

- [x] 支持布局，比如一行1、2、3个，同时支持 ui:width 参数配置单个item宽度，会自动加上padding right
- [x] labelPosition 不在top时，description显示样式调整为鼠标移上去提示
- [x] 修复默认formData和schema计算值相等时可能无法同步值问题

**Comment by LinuxGod** [comment]
schema-generator 导出的schema还能导入就更完美了

**Comment by lljj-x** [comment]
@LinuxGod 
会加这个导入功能，目前也在计划内

**Comment by LinuxGod** [comment]
> @LinuxGod
> 会加这个导入功能，目前也在计划内
👍

**Comment by LinuxGod** [comment]
> @LinuxGod
> 会加这个导入功能，目前也在计划内

导入这个功能大约什么时候能上线呢?

**Comment by lljj-x** [comment]
@LinuxGod  暂定应该在下个周末

**Comment by lljj-x** [comment]
@LinuxGod  试试现在已经支持导入

https://form.lljj.me/schema-generator.html

**Comment by LinuxGod** [comment]
@lljj-x 好的，谢谢。
