### ISSUE TITLE
属性名可以支持更多格式吗？例如name.A

### ISSUE THREAD

**Issue by Gaofancy** [lljj-x/vue-json-schema-form#191]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/13410631/169989666-6f1ec219-5789-4376-91fc-9dcde969b64e.png">

例如这样的格式
`{
"name.A": "xiaoming",
"name.B": "xiaomingB",
}`

**Comment by Gaofancy** [comment]
> 不支持

大佬这个可以通过什么方法支持一下吗？最近有一个这样的需求。

**Comment by lljj-x** [comment]
框架内部做不到，你可以自己传进来之前先映射个别名 最后在转回去
