### ISSUE TITLE
vite+ vue3 +iconify 引入 vue3-form-element 失败

### ISSUE THREAD

**Issue by radiorz** [lljj-x/vue-json-schema-form#192]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3
element
vue3-form-element 1.13.0

###  问题描述
对错误是什么的清晰简洁的描述。
引入依赖就报错了。。。
### 如何复现
可以详细介绍你的复现场景或者相关代码。
详见 github.com/radiorz/frontend-demo
引入就报错了 

### 期望的结果
正常使用

**Comment by lljj-x** [comment]
可以给下最小复现 你这个代码太多了
