### ISSUE TITLE
使用 unplugin-vue-components 按需引入 elementplus 时提示找不到组件.

### ISSUE THREAD

**Issue by radiorz** [lljj-x/vue-json-schema-form#193]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3、
ui框架element
vjsf vue3-form-element 1.13.0

###  问题描述

不能够按需引入 必须全局引入
### 如何复现
参看 gitlab.com/radiorz/frontend-demo 中的 vue3-element

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

### 期望的结果
....
希望可以按需导入? 是否可以做到?!

**Comment by lljj-x** [comment]
ref: https://github.com/lljj-x/vue-json-schema-form/issues/169
