### ISSUE TITLE
英文版的可视化编辑器

### ISSUE THREAD

**Issue by oeway** [lljj-x/vue-json-schema-form#20]
hi，你好，感觉你的这个库做的很强大，想在一个更国际化的开源项目中推荐使用它来做可视化编辑界面。请问有计划提供英文版的可视化编辑器吗？包括schema-generator和活动编辑器。

**Comment by lljj-x** [comment]
其实原本在写文档的时候是尝试过英文版，但英语能力实在有限 。

所以抱歉现在的版本还没计划英文。
