### ISSUE TITLE
关于枚举enum类型在electron-vue环境中运行报错的问题

### ISSUE THREAD

**Issue by star-fork** [lljj-x/vue-json-schema-form#200]
### vue和ui框架
vue2、element、"@lljj/vue-json-schema-form": "^1.10.0",

###  enum类型的数据无法正确渲染
el-select - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> SelectWidget
el-option - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> SelectWidget

### 如何复现
1、搭建简单的electron-vue环境
2、引入element-ui和vsjf
3、生成一个测试demo
测试数据链接：https://form.lljj.me/#/demo?ui=VueElementForm&type=Test&schema=%7B%22type%22%3A%22object%22,%22title%22%3A%22Number%20fields%20%26%20widgets%22,%22properties%22%3A%7B%22numberEnum%22%3A%7B%22type%22%3A%22number%22,%22title%22%3A%22Number%20enum%20%28select%29%22,%22enum%22%3A%5B1,2,3%5D,%22enumNames%22%3A%5B%22Select%20-%201%22,%22Select%20-%202%22,%22Select%20-%203%22%5D%7D%7D%7D&formData=%7B%22numberEnum%22%3A3%7D&uiSchema=%7B%7D&errorSchema=%7B%7D&formFooter=%7B%22show%22%3Atrue%7D&formProps=%7B%22labelWidth%22%3A%22100px%22,%22inline%22%3Afalse,%22labelPosition%22%3A%22top%22,%22inlineFooter%22%3Afalse,%22layoutColumn%22%3A1%7D

### 期望的结果
支持在electron-vue中正常运行

**Comment by lljj-x** [comment]
需要全局注册 elementUi el-select组件，不清楚依赖哪些 可以全局注册 elementUi

**Comment by Chen1810** [comment]
目前是在main中全局注册elementUi的，正在尝试使用自定义组件的方式，您有时间的话可以试一下

**Comment by lljj-x** [comment]
你需要先保证全局注册成功，你可以通过是否能够正常使用elementUi来验证

**Comment by Chen1810** [comment]
嗯嗯 其他elementUi组件都是正常的

**Comment by Chen1810** [comment]
嗯嗯 其他elementUi组件都是正常的 所以我也很好奇 哈哈

**Comment by lljj-x** [comment]
神奇，可以给个复现仓库看看
