### ISSUE TITLE
inlineFooter:true无效

### ISSUE THREAD

**Issue by YujiaCheng1996** [lljj-x/vue-json-schema-form#201]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3、element plus最新版

###  问题描述
inlineFooter:true无效，分为fieldGroupWrap和formFooter_item两个div。

### 如何复现
			<vue-form
					v-model="searchFormData"
					:schema="searchFormSchema"
					:ui-schema="{
						'ui:options': {
							showTitle: false,
							showDescription: false,
						},
					}"
					:form-footer="{
						show: true,
						okBtn: '查询',
						okBtnProps: { type: 'primary', loading },
						cancelBtn: '重置',
					}"
					:form-props="{
						inline: true,
						inlineFooter: true,
						labelPosition: 'right',
						isMiniDes: true,
					}"
					@submit="onSearch"
					@cancel="onReset"
				></vue-form>

### 期望的结果
希望做搜索栏，有重置和查询2个按钮，需尽量合并到一行。希望能把formFooter_item的内容直接塞入fieldGroupWrap中

**Comment by lljj-x** [comment]
这个问题暂时解决不了，inlinefooter 只能让fieldGroupWrap和formFooter_item 一行，这里只能靠你自己发挥css水平，不动dom的情况下 放到一行
