### ISSUE TITLE
自定义的Field组件，无法在数组和Object中使用校验逻辑

### ISSUE THREAD

**Issue by Gaofancy** [lljj-x/vue-json-schema-form#204]
### vue和ui框架
vue3、ui框架antd 2.x

###  问题描述
自定义的Field组件，无法在数组和Object中使用校验逻辑。
1. 在外面可以用，但是放到数组和Object组件中时，在validator方法获取到的value是undefined
2. 可以直接用，但是无法做自定义校验

### 如何复现
1. 自定义field + rules
2. 在rules传入validator方法，validator无法正常校验

demo：
```html
<a-form-item
        :label="`${selectProps.title}：`"
        :name="curNodePath"
        :rules="[{ validator }]">
        <a-input
            type="text"
            v-model:value="value"
            @change="onchange" />
</a-form-item>
```

``` javascript
let validator = async (rule: RuleObject, value: string) => {
                
                // 针对叶子节点做校验
                const errors = schemaValidate.validateFormDataAndTransformMsg({
                    formData: value,
                    schema: props.schema,
                    customFormats: props.customFormats,
                    errorSchema: props.errorSchema,
                    required: props.required,
                    propPath: props.curNodePath,
                });

                console.log(value);   // 这里为什么是 undefined

                if (errors.length) {
                    return Promise.reject(errors[0].message);
                }
                return Promise.resolve();
            };
```
### 期望的结果
自定义的Field可以正常在其他组件中做校验

**Comment by Jenky1031** [comment]
我也是用vue3、ui框架antd 2.x，想请教一个问题，为啥使用VueForm时没有样式

**Comment by lljj-x** [comment]
antd vue formItem组件name 是数组，这种和框架无关的问题自己去查ui组件库
```
:name="curNodePath.split('.')"
```

**Comment by lljj-x** [comment]
并且这个其实更推荐自定义field内部直接调用 SchemaField 这个组件，就不需要手动来处理这些。

类似这个：
https://github.com/lljj-x/schema-form-components/blob/main/packages/lib/src/fields/TabField/index.vue#L11

**Comment by EveChee** [comment]
> 并且这个其实更推荐自定义field内部直接调用 SchemaField 这个组件，就不需要手动来处理这些。
> 
> 类似这个： https://github.com/lljj-x/schema-form-components/blob/main/packages/lib/src/fields/TabField/index.vue#L11

你推荐的这种方式确实能解决一部分问题。

**Comment by EveChee** [comment]
> 并且这个其实更推荐自定义field内部直接调用 SchemaField 这个组件，就不需要手动来处理这些。
> 
> 类似这个： https://github.com/lljj-x/schema-form-components/blob/main/packages/lib/src/fields/TabField/index.vue#L11

你推荐的这种方式可能可以解决部分问题。很感谢你。
但是在我内部校验规则比较复杂的情况下。
还是希望能够保持原有的el-form-item rules行为，也许一个组件不应该在作为其他组件的子项或者属性传入传出的时候，而导致原有行为发生改变。
