### ISSUE TITLE
How to set placeholder to empty

### ISSUE THREAD

**Issue by clabnet** [lljj-x/vue-json-schema-form#206]
I need to remove any text from placeholder when a field is empty.
How to ?
Thank's

**Comment by lljj-x** [comment]
Can upgrade the Naivi UI version，older versions set a default placeholder value

https://codesandbox.io/s/xenodochial-violet-zmlm6v?file=/src/Demo.vue

---

Or use `ui:placeholder` to override the default value

```js
{
    "title": "Test naiveUi input",
    "type": "object",
    "properties": {
        "text": {
            "type": "string",
            "ui:placeholder": ""  // Override the naiveUI default placeholder
        }
    }
}
```

**Comment by clabnet** [comment]
Thank you,

**Comment by clabnet** [comment]
@lljj-x  This work, at field level.
Unfortunately I have a form with +50 fields: 
can I use a "ui:placeholder": "" at first level (one unique), and not at field level's ? If yes, where I do add this ?
Thanks in advance.

**Comment by lljj-x** [comment]
This requires [Naive UI](https://www.naiveui.com/) support，Or upgrade to the latest version of `Naive UI`
