### ISSUE TITLE
How to add an html part into the json schema?

### ISSUE THREAD

**Issue by clabnet** [lljj-x/vue-json-schema-form#207]
Vue 3, Vite2 , Naive UI

I would add an html snippet into the schema to generate (for example) a green box with a text into the  dynamic form result.

It is possible ?? How to ? 

Thank's

**Comment by lljj-x** [comment]
You can use `ui:widget` config

ref: https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89widget
