### ISSUE TITLE
如果能够在schema中直接加入正则校验就好了

### ISSUE THREAD

**Issue by Sweet-KK** [lljj-x/vue-json-schema-form#208]
### vue和ui框架
"vue": "3.2.36","@lljj/vue3-form-element": "^1.13.1","element-plus": "^2.2.9",

###  问题描述
看了一下校验那块的内容，只想加一个正则，不管是哪个方案处理起来的难度都大大增加

### 期望的结果
如果能够在schema中直接传入校验规则就方便多了

**Comment by lljj-x** [comment]
参考JSON Schema 规范
https://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions

这里[一个简单的正则例子](https://form.lljj.me/#/demo?ui=VueElementForm&type=Test&schema=%7B%22type%22%3A%22object%22,%22properties%22%3A%7B%22test%22%3A%7B%22type%22%3A%22string%22,%22pattern%22%3A%22%5E%28%5C%5C%28%5B0-9%5D%7B3%7D%5C%5C%29%29%3F%5B0-9%5D%7B3%7D-%5B0-9%5D%7B4%7D%24%22%7D%7D%7D&formData=%7B%7D&uiSchema=%7B%7D&errorSchema=%7B%7D&formFooter=%7B%22show%22%3Atrue%7D&formProps=%7B%22labelWidth%22%3A%22100px%22,%22inline%22%3Afalse,%22labelPosition%22%3A%22top%22,%22inlineFooter%22%3Afalse,%22layoutColumn%22%3A1%7D)
