### ISSUE TITLE
Schema生成器界面，拖拽‘布局组件’Array到中间（form区域），控制台报错

### ISSUE THREAD

**Issue by MHappy135246** [lljj-x/vue-json-schema-form#21]
Schema生成器界面，拖拽‘布局组件’Array到中间（form区域），控制台报错：index.js?cf23:61 error: type array，值必须为 array 类型，为什么呢？谢谢

**Comment by lljj-x** [comment]
![image](https://user-images.githubusercontent.com/6283929/99935805-8259bf80-2d9c-11eb-9f58-61940e4f8e18.png)

这里是没关系的，因为默认拖进来array类型没有初始化值，程序内部就提示了这个，实际会默认空数组 ，这个场景下可以忽略

**Comment by MHappy135246** [comment]
收到，谢谢。
