### ISSUE TITLE
Adding widget color the validation error : should match the format "color"

### ISSUE THREAD

**Issue by clabnet** [lljj-x/vue-json-schema-form#212]
Hi, 
Vue 3, Naive,  adding this schema to obtain a color picker : 
```
   "topbar_color": {
            "title": "Top bar color",
            "type": "string",
            "format": "color",
            "modes": [
              "hex"
            ],
            "default": "#151ce6"
          }
```
changing the color, I have always this validation error : 
`  must match format "color" `

Here a sample 
https://form.lljj.me/v3/#/demo?type=Test&schema={%22type%22:%22object%22,%22required%22:[],%22properties%22:{%22color_string_1659818310177x0%22:{%22title%22:%22%E9%A2%9C%E8%89%B2%E9%80%89%E6%8B%A9%E5%99%A8%22,%22type%22:%22string%22,%22format%22:%22color%22}},%22ui:order%22:[%22color_string_1659818310177x0%22]}&uiSchema={}&formFooter={%22show%22:false}&formProps={%22inline%22:false,%22labelPosition%22:%22top%22,%22inlineFooter%22:false,%22layoutColumn%22:1,%22labelSuffix%22:%22%EF%BC%9A%22,%22labelWidth%22:%22100px%22}&ui=VueNaiveForm&formData={}&errorSchema={}

Where is defined the format color ? How to solve this ?

Thanks

**Comment by lljj-x** [comment]
This is now the validation rule and does not support `rgba`，It will be fixed in the next version
https://github.com/lljj-x/vue-json-schema-form/blob/master/packages/lib/utils/schema/validate.js#L35

---
You can temporarily skip validation

```js
"topbarColor": {
      "title": "Top bar color",
      "type": "string",
      "ui:widget": "ColorWidget"
  }
```

**Comment by lljj-x** [comment]
Upgrade to `1.14.0`  version
