### ISSUE TITLE
How to show an image or icon ?

### ISSUE THREAD

**Issue by clabnet** [lljj-x/vue-json-schema-form#215]
Hi, 
I watched [your documentation](https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#demo-%E5%9B%BE%E7%89%87%E9%93%BE%E6%8E%A5%E9%85%8D%E7%BD%AE) 
Unfortunately it is not clear for me how to show an image or icon into a vue json schema form. 
I have add this snippet to my schema : 
```
 "properties": {
      "ImgItem": {
        "type": "object",
        "properties": {
          "imgUrl": {
            "title": "Image url",
            "type": "string",
            "format": "uri"
          },
          "imgLink": {
            "title": "Image link",
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "imgUrl",
          "imgLink"
        ]
      },
```
but the result are two text fields imgUrl and imgLink.

Thank you in advance

**Comment by lljj-x** [comment]
Custom widgets can be used.

Reference: https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89widget
