### ISSUE TITLE
How to reset an entire form with +100 fields ?

### ISSUE THREAD

**Issue by clabnet** [lljj-x/vue-json-schema-form#217]
I have a form with +100 fields.

Whats is the best practice to reset each field to default value ?

Thank's

**Comment by lljj-x** [comment]
Update the `formData` value
```js
{
  data() {
   return {
      formData: this.getDefaultValue()
    }
  },
  methods: {
    resetVal() {
      this.formData = this.getDefaultValue()
    }
  }
}
```

Or use the reset method of the ui component library `this.$$uiFormRef?.resetFields()`
