### ISSUE TITLE
Can I populate the enum entries of a select box with dynamic data returned from db?

### ISSUE THREAD

**Issue by clabnet** [lljj-x/vue-json-schema-form#221]
Hi, 

I have a big form with 100+ fields, with many select box.
indeed to populate items statically via enum entries from schema,
can I add items to select box dynamically from db? 

thanks in advance

**Comment by lljj-x** [comment]
You can use `ui:enumOptions` to dynamically update options, or update the schema `enum`

https://codepen.io/ljj/pen/zYjmobw

**Comment by clabnet** [comment]
Thanks, but I can populate also the data from db whitin the '@form-mounted' event.
