### ISSUE TITLE
当类型为array且是必填项时检测失效 

### ISSUE THREAD

**Issue by wuwuxi** [lljj-x/vue-json-schema-form#223]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3+antd

###  问题描述
当类型为array且是必填项时检测失效 

### 如何复现
{
              "title": "测试专用页",
              "type": "object",
              "description": "已经输入了",
              "required": [
                "listOfStrings",
              ],

              "properties": {
                "listOfStrings": {
                  "type": "array",
                  "title": "A list of strings",
                  "items": {
                    "title": "Input string",
                    "type": "string",
                    "default": ""
                  }
                },
              }
            }

### 期望的结果
能检测数组是否为空

**Comment by lljj-x** [comment]
require 不能校验数组长度，使用 minItems
https://json-schema.org/understanding-json-schema/reference/array.html#length

**Comment by wuwuxi** [comment]
感谢已解决
