### ISSUE TITLE
请问怎么把数组格式的description做气泡展示

### ISSUE THREAD

**Issue by wuwuxi** [lljj-x/vue-json-schema-form#225]
![25J)TSV~PF5P%Y%I`LD2SRN](https://user-images.githubusercontent.com/27846587/191918859-70716416-712a-45c2-9a77-0510ecb7b4e9.png)

**Comment by wuwuxi** [comment]
![image](https://user-images.githubusercontent.com/27846587/191919445-079b35e9-44ed-485c-a4e8-9a4066f68ee4.png)
这样配置 没有达到想要的结果

**Comment by lljj-x** [comment]
这个不支持，只能是 formItem的 label可以起泡。

object ，array 的description 不支持

**Comment by wuwuxi** [comment]
好的，谢谢

**Comment by shurong2199** [comment]
> 

请问只有 title 在输入框两侧时，description 才能起泡吗？
 title 在输入框上方时，如何设置 description 起泡呢？
不想 description 直接显示为文本在 title 下方 -- 在多列布局时 description 会占据高度，使得表单参差不齐
