### ISSUE TITLE
请问schema-generator 表单生成器页面，左侧的拖拽插件，怎么加入自己自定义的？

### ISSUE THREAD

**Issue by danstart** [lljj-x/vue-json-schema-form#226]
下载了咱的前端代码，放入到自己的项目中，目前的schema-generator生成器左侧我要添加一个组件，就是类似于tduck（如下图1）项目的左侧的横向填空拖拽效果
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/23281075/192681378-06cdfc49-031e-45c1-b8fa-ae8369ed82c3.png">

我本地写的简单的vue页面 呈现效果图如下：
<img width="635" alt="image" src="https://user-images.githubusercontent.com/23281075/192681657-de6c7bc3-27ef-4391-90e7-2d5ebef50aa6.png">

请问，有什么方法把我写的这个简易的填空，结合到咱的schema-generator里，在左侧拖拽菜单上加进来我自定义的这个插件使用呢？我看了咱们的官网，没有找到方案，请大神赐教

**Comment by lljj-x** [comment]
这部分没有直接的配置项。需要参见源码，按对应格式添加 vue组件和配置的form schema

**Comment by monstereat** [comment]
> 下载了咱的前端代码，放入到自己的项目中，目前的schema-generator生成器左侧我要添加一个组件，就是类似于tduck（如下图1）项目的左侧的横向填空拖拽效果 <img alt="image" width="1426" src="https://user-images.githubusercontent.com/23281075/192681378-06cdfc49-031e-45c1-b8fa-ae8369ed82c3.png">
> 
> 我本地写的简单的vue页面 呈现效果图如下： <img alt="image" width="635" src="https://user-images.githubusercontent.com/23281075/192681657-de6c7bc3-27ef-4391-90e7-2d5ebef50aa6.png">
> 
> 请问，有什么方法把我写的这个简易的填空，结合到咱的schema-generator里，在左侧拖拽菜单上加进来我自定义的这个插件使用呢？我看了咱们的官网，没有找到方案，请大神赐教

哥解决了么，有参考示例？
