### ISSUE TITLE
Textarea doesn't work in Vue3 + Antdv . 

### ISSUE THREAD

**Issue by piaolingmiding** [lljj-x/vue-json-schema-form#228]
Textarea works in Vue3+Elementplus

**Comment by lljj-x** [comment]
ui:widget `TextAreaWidget` ，antd input 不支持配置type 
https://antdv.com/components/input#components-input-demo-textarea

```js
    "firstName": {
        "type": "string",
        "title": "First name",
        "ui:widget": "TextAreaWidget"
    }
```

**Comment by piaolingmiding** [comment]
Great! It works like a charm!
In the playground, you can add it to the example for textarea                
"textarea": {
                    "type": "string",
                    "title": "textarea",
                    "ui:widget": "TextAreaWidget"
                },
