### ISSUE TITLE
界面上动态加减对象

### ISSUE THREAD

**Issue by zzh34634** [lljj-x/vue-json-schema-form#229]
### vue和ui框架
vue3、ui框架element

请问一下，如果我想在界面上像数组操作那样动态添加删除特定Object, 类似map，比数组多了个自定义的key，用自定义组件能实现嘛，还是说要修改库

**Comment by lljj-x** [comment]
可以通过自定义 filed ，对需要动态删减属性的对象配置

这是个类似的问题 #96
