### ISSUE TITLE
两个jsonSchema之间可以互相‘引用’或者如何建立联系

### ISSUE THREAD

**Issue by MHappy135246** [lljj-x/vue-json-schema-form#23]
你好，两个jsonSchema之间可以互相‘引用’或者如何建立联系？比如一个表单有字段a、b，另一个表单有字段a,b,c,d这个时候后者可以直接去引用包含前者吗，还是说我这个想法太荒谬？

**Comment by lljj-x** [comment]
这个官方 JSONSchema 确实是支持跨文件引用的，不过现在不支持这种方式，**只支持在文件内引用**。
![image](https://user-images.githubusercontent.com/6283929/101594574-e337f780-3a2c-11eb-8352-ef3f78f1d30b.png)

JSON Schema 文档：https://json-schema.org/understanding-json-schema/structuring.html#reuse

目前相对标准Schema不支持的部分：https://vue-json-schema-form.lljj.me/zh/guide/todo.html

---
并且目前也**不计划支持 $ref的跨文件调用**，因为现在整个schema解析都是同步执行的，加载文件这里的调整会比较大。

所以需要使用者自己解决，你这里可以同时去读取两个JSON文件合并好参数在传给组件。大致这个思路

**Comment by MHappy135246** [comment]
已阅，谢谢
