### ISSUE TITLE
array type cannot get "index" from ui:fieldProps

### ISSUE THREAD

**Issue by MikeMiller3** [lljj-x/vue-json-schema-form#232]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3、ui框架antd

###  问题描述
array类型，ui:fieldProps中拿不到数组元素的 index，导致无法进行校验等

### 期望的结果
array类型，ui:fieldProps中能拿到数组元素的 index

**Comment by lljj-x** [comment]
目前是不能获取到index，考虑field的通用性，不在array下面就不会有index

**Comment by lljj-x** [comment]
可以详细描述下你必要 index 的场景

**Comment by MikeMiller3** [comment]
> 可以详细描述下你必要 index 的场景

数组用于描述一个优惠券列表，每个优惠券都有对应的图片url、图片的高度，其中：
- ImageUrl，表示图片url：是一个自定义field，实现了向服务器进行图片上传返回一个url的功能。
- ImageHeight，表示图片的高度：是另一个自定义field，监听传入的图片url变化，获取url对应图片的高度，高度可手动修改。

- 在非数组场景下（例如object），在ImageHeight中，可以通过{{parentFormData.url}}将图片url传入fieldProps
- 表单项在数组中时，无法使用parentFormData，拿不到对应的图片url，无法在ImageHeight中自动设置图片默认高度

**Comment by lljj-x** [comment]
> 表单项在数组中时，无法使用parentFormData，拿不到对应的图片url，无法在ImageHeight中自动设置图片默认高度

这个数字是可以的 不清楚你的具体场景，可以给复现仓库

**Comment by MikeMiller3** [comment]
> 

数组里是可以使用，但是数组里用到了自定义Field，在自定义Field好像用不了parentFormData

**Comment by lljj-x** [comment]
> 数组里是可以使用，但是数组里用到了自定义Field，在自定义Field好像用不了parentFormData

自定义Field的话这个值可以自己算一下，表达式和事件中直接用是因为内部在widget中帮你算了，自定义了Filed 相当于自定义了widget的父组件，所以没了。

通过formUtils提供的方法可以计算，伪代码如下
```js
import { formUtils } from '@lljj/vue-json-schema-form';

{
  parentFormData: formUtils.getPathVal(this.rootFormData, this.curNodePath, 1),
  rootFormData: this.rootFormData
}

```
