### ISSUE TITLE
按需引入antdv，组件为什么不能展示

### ISSUE THREAD

**Issue by built9** [lljj-x/vue-json-schema-form#233]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
antd vue3 vite unplugin-vue-components

###  问题描述
按需引入antdv，组件不能展示，会报a-form If this is a native custom element

### 期望的结果
应该怎么做呢？只能全局引入吗？

**Comment by lljj-x** [comment]
参考这个： #169

**Comment by yhzhang5210** [comment]
引入组件后，只显示保存和取消，其它控件不显示。
