### ISSUE TITLE
schema数据格式解析逻辑开源么

### ISSUE THREAD

**Issue by ytblackTea** [lljj-x/vue-json-schema-form#236]
项目里面的schema解析逻辑被压缩了，能看到源码么

**Comment by muyiwei** [comment]
packages/lib 里面

**Comment by ytblackTea** [comment]
![image](https://user-images.githubusercontent.com/27613376/200855764-4cdc81da-ad0d-404d-9acc-85b902bdbb64.png)
这里么

**Comment by lljj-x** [comment]
src 目录下
