### ISSUE TITLE
多语言支持I18N的问题？

### ISSUE THREAD

**Issue by FEsujian** [lljj-x/vue-json-schema-form#237]
![image](https://user-images.githubusercontent.com/33425635/200992843-d4ff21c9-9394-43dc-b68e-7516fbecc029.png)
![image](https://user-images.githubusercontent.com/33425635/200993020-ae9a2cfc-d836-4520-b047-78feda8e89cc.png)

请问下schema的title如何配置i18n？

**Comment by lljj-x** [comment]
一样的 title 是一个翻译方法的返回值

**Comment by FEsujian** [comment]
你好，我说的是json的key怎么给呢？

**Comment by FEsujian** [comment]
userName是一个propertites，但是schema的root 的title不知道怎么设置key了

**Comment by FEsujian** [comment]
还有一个问题，就是切换语言之后，title不会自动切换，刷新一下页面才可以，这个要怎么处理呢？

**Comment by lljj-x** [comment]
这个也是需要你的translate方法支持响应式
