### ISSUE TITLE
Using UploadWidget on json schema with Vue3 and NaiveUI

### ISSUE THREAD

**Issue by clabnet** [lljj-x/vue-json-schema-form#239]
Hi, 
I would use `@before-upload` event of naive-ui [Upload](https://www.naiveui.com/en-US/os-theme/components/upload) component. The  json schema is :
```
    "imgUrl": {
      "title": "Upload",
      "type": "string",
      "ui:action": "http://localhost:5000/uploadfile",
      "ui:widget": "UploadWidget",
      "ui:list-type": "image-card",
      "ui:btnText": "Browse",
      `ui:onBeforeUpload`  << not work
      `ui:beforeUpload`   << not work 
      `ui:@beforeUpload`   << not work 
      `ui::beforeUpload`   << not work 
   }
```
How to add the call to naive-ui event on json schema ?
Thank's

**Comment by lljj-x** [comment]
Try this

```js
"ui:on-before-upload": "doSomething"
```

**Comment by clabnet** [comment]
Thanks, but it seems not working.
The event seems not passed or hooked to/from upload.js component (the internal upload lib used from upload component naive)

**Comment by lljj-x** [comment]
Provide a minimal reappearance link ？

**Comment by BossHogg97** [comment]
Hi, i'm a collegue of @clabnet. 
I solved the problem using `"ui:widget": "uploadWidget"` and inside the custom component i add the Naive event handle the image upload.
