### ISSUE TITLE
如何展示图片

### ISSUE THREAD

**Issue by Lelestorm** [lljj-x/vue-json-schema-form#241]
### vue和ui框架
vue3、ui框架element plus、vjsf 最新版

###  问题描述
如何展示图片

### 期望的结果
![image](https://user-images.githubusercontent.com/15667387/202641939-f20f48a8-e86e-418d-bea1-a3ba0c387321.png)

**Comment by Lelestorm** [comment]
已解决

**Comment by shinchanZ** [comment]
你好，请问如何解决的，手动封装加了个组件吗 @Lelestorm
