### ISSUE TITLE
当属性值为空对象的时候无法生成表单

### ISSUE THREAD

**Issue by life2022** [lljj-x/vue-json-schema-form#243]
配置的Schema：
`{
    "properties": {
        "headers": {
            "minProperties": 1,
            "description": "new headers for request",
            "type": "object",
            "title": "headers",
        }
       
}`
FormData：
{
    "headers": {},
}

### vue和ui框架
vue3、Antdv

### 如何复现
[问题预览](https://form.lljj.me/v3/#/demo?ui=VueElementForm&type=Test&schema={%22title%22:%22%E6%B5%8B%E8%AF%95%E4%B8%93%E7%94%A8%E9%A1%B5%22,%22type%22:%22object%22,%22description%22:%22%E8%BE%93%E5%85%A5%E4%BD%A0%E7%9A%84Schema%EF%BC%8C%E9%A1%B6%E9%83%A8%E5%88%86%E4%BA%AB%E6%8C%89%E9%92%AE%E5%8D%B3%E5%8F%AF%E5%BF%AB%E9%80%9F%E7%94%9F%E6%88%90%E9%93%BE%E6%8E%A5%22,%22properties%22:{%22headers%22:%20{%20%22minProperties%22:%201,%20%22description%22:%20%22new%20headers%20for%20request%22,%20%22type%22:%20%22object%22,%20%22title%22:%20%22headers%22%20}}}&formData={}&uiSchema={}&errorSchema={}&formFooter={%22show%22:true}&formProps={%22inline%22:false,%22labelPosition%22:%22top%22,%22inlineFooter%22:false,%22layoutColumn%22:1,%22labelWidth%22:%22100px%22})

### 期望的结果
空对象的时候可否给予一个按钮进行添加属性名与属性值

**Comment by lljj-x** [comment]
这个不支持，需要自己定义

参考：#96
