### ISSUE TITLE
如何获取表单的当前校验状态

### ISSUE THREAD

**Issue by 47547615** [lljj-x/vue-json-schema-form#244]
### vue和ui框架
vue3 3.2.39、elmentPlus 2.2.17

###  问题描述
我想在表单输入的时候，获取表单的当前校验状态，我该怎么操作呢。
比如表单有10个字段，在其中1个输入框输入时，只要有任意1个输入框发生校验错误，整个表单校验状态就是 false,  我该通过什么方式去获取整个表单的状态。

### 期望的结果
期望有相关的API能支持获取状态。

**Comment by lljj-x** [comment]
可以拿到formRef 去调用对应ui表单库的 validate 方法

**Comment by lljj-x** [comment]
[#on-form-mounted](https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#on-form-mounted) 这个是可以拿到 formRef
