### ISSUE TITLE
vue3 antd 使用schema生成器不显示表单

### ISSUE THREAD

**Issue by peterzheng1** [lljj-x/vue-json-schema-form#248]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3 antd

###  问题描述
拖拽组件，中间不展示表单

### 如何复现
![image](https://user-images.githubusercontent.com/43431817/205828722-21349efa-9f3c-45f3-8d73-e2fcf409e4b4.png)
打印出rootFormData为空
![image](https://user-images.githubusercontent.com/43431817/205829127-3d2b6363-943f-4a53-b03d-c2fb9094e490.png)

### 期望的结果
![image](https://user-images.githubusercontent.com/43431817/205829293-ada12cef-ed0e-4808-9ea9-38e4820db57f.png)

**Comment by lljj-x** [comment]
这个要自己调试下了 ，生成器的代码主要是一个参考
