### ISSUE TITLE
关于左右布局时无法修改描述信息位置的问题

### ISSUE THREAD

**Issue by ylinH-git** [lljj-x/vue-json-schema-form#253]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3+element-plus，不过根据代码应该是框架和组件无关的逻辑问题

###  问题描述
我这边有个需求，就是左右结构，但是描述信息需要完全展示出来，而不使用tooltip
但是发现修改isMiniDes并不会生效

### 如何复现
这边就不通过demo复现了吧，直接看看代码
```javascript
    HELPERS: {
        // 是否mini显示 description
        isMiniDes(formProps) {
            return formProps && ['left', 'right'].includes(formProps.labelPosition);
        }
    }
```
```javascript
    const isMiniDes = props.formProps && props.formProps.isMiniDes;
    const miniDesModel = isMiniDes || props.globalOptions.HELPERS.isMiniDes(props.formProps);
```
根据上面两段代码，左右的结构的时候是只能显示小图标模式的，不支持切换
### 期望的结果
希望无论是左右结构还是上下结构都能支持描述信息模式的切换，
另外提个小feature，看看是否能支持一下描述信息更灵活的一些配置项。目前小图标模式的icon和浮窗的宽度都是固定的。
谢谢

**Comment by lljj-x** [comment]
1. formProps.isMiniDes 配置这个可以不在左右结构下
2. 这种个性化的是建议自定义一个widget包装一下来处理你需要的个性化描述

**Comment by ylinH-git** [comment]
1. 这个是什么意思，是说其实是可以支持的，只是我配置错了嘛？因为我貌似改这个值在左右结构下确实没有生效
2. 谢谢，这个方案我可以试一下，不过这个感觉可能不是widget可以解决的吧～因为需要是当表单的label是左右结构的时候希望所有的formitem的描述信息都可以不使用miniDes的模式。

效果如下
![image](https://user-images.githubusercontent.com/69850810/207758321-4cd6d0c9-dd78-4917-9153-32f172960fbf.png)

**Comment by lljj-x** [comment]
1.  我理解反了 你想要的是反过来 现在不支持 
2. wiget 可以单独扩展一个你的字段，这样比较简单。比如：ui:cusDescription，这样是针对单个input场景的。或者自定义field，这个建议可以直接贡献代码，改动差不多

**Comment by ylinH-git** [comment]
哈哈，好的，才看到，不好意思，那我过两天提个代码
