### ISSUE TITLE
Change language for error displaying

### ISSUE THREAD

**Issue by BossHogg97** [lljj-x/vue-json-schema-form#254]
Hi, i'm working with Vue3 and NaiveUI. I'd like to know how to display this kind of error message in english (or if it's possible in other languages)

Thanks in advance! This component is very powerful, goodjob!
![chineseErrorLanguage](https://user-images.githubusercontent.com/49211261/207910851-4b6aa85d-018f-46f5-9f7f-ce1eecc145fe.png)

**Comment by lljj-x** [comment]
Error message i18n use [ajv-i18n](https://github.com/ajv-validator/ajv-i18n)

Link this:

```js
import localizeEn from 'ajv-i18n/localize/en';
import { i18n } from '@lljj/vue3-form-naive';

// Set en local
i18n.useLocal(localizeEn);
```

**Comment by BossHogg97** [comment]
Thanks!
