### ISSUE TITLE
UploadWidget 似乎不可用了，甚至会导致整个浏览器的无响应

### ISSUE THREAD

**Issue by nekomeowww** [lljj-x/vue-json-schema-form#259]
### vue和ui框架

直接使用在 [全局Widget组件 | Vue JSON Schema Form](https://vue-json-schema-form.lljj.me/zh/guide/components.html#uploadwidget) 文档中提供的 [Playground upload 组件](https://form.lljj.me/#/demo?type=Upload) 来进行的复现，vue2 和 vue3 均可复现。

###  问题描述

点击 [Playground upload 组件](https://form.lljj.me/#/demo?type=Upload) 的「上传按钮文案配置」和「点击上传」都能够触发这个问题。

在以下 Vue 版本中均能稳定复现该问题：

1. Vue 2
2. Vue 3

在以下版本浏览器中均能稳定复现该问题：

1. Google Chrome 108.0.5359.124（正式版本） (arm64)
3. Microsoft Edge 108.0.1462.54 (正式版本) (arm64)
4. Safari 16.1 (18614.2.9.1.12)  

问题体现在：

1. 在首次打开该页面点击按钮后导致浏览器卡死
6. 卡死等待一段时间恢复后按钮完全失效的问题

然而控制台中没有任何报错，暂时无法提供更深层次的错误内容。

### 如何复现

点击 [Playground upload 组件](https://form.lljj.me/#/demo?type=Upload) 的「上传按钮文案配置」和「点击上传」都能够触发这个问题，vue2 和 vue3 均可复现。

### 期望的结果

点击后能像过去那样打开文件选择器并允许用户进行文件选择后上传文件。

**Comment by lljj-x** [comment]
我这里ok，版本一致的，只是我是inter u 。
版本 108.0.5359.124（正式版本） (x86_64)

看起来像是你电脑的问题，可以看看是不是所有的文件选择都会卡死，比如下面这个上传文件是否可用
https://element.eleme.cn/#/zh-CN/component/upload

**Comment by nekomeowww** [comment]
> 我这里ok，版本一致的，只是我是intel u 。 版本 108.0.5359.124（正式版本） (x86_64)
> 
> 看起来像是你电脑的问题，可以看看是不是所有的文件选择都会卡死，比如下面这个上传文件是否可用 https://element.eleme.cn/#/zh-CN/component/upload

感谢解答。我试了一下你提供的 Element Plus 的上传组件，发现也有同样的问题，重启浏览器之后也还是一样，我重启电脑之后就莫名其妙的恢复了。看起来可能是某种 macOS Bug？

既然功能已经恢复了，我就把 Issue 关闭了。感谢你花时间为我解答！
