### ISSUE TITLE
如果自定义type为array组件，如何$emit()向父组件更新数据

### ISSUE THREAD

**Issue by hallwong** [lljj-x/vue-json-schema-form#26]
如果自定义type为array组件，如何利用$emit('eventName')向父组件更新数据。这个事件名称在文档里查不到。

**Comment by lljj-x** [comment]
你是指 type: array ，配置了 ui:widget ？  widget 都是v-model的形式，$emit('input', value);

**Comment by hallwong** [comment]
type: array ，配置了 ui:widget 对但是我实际测试 input 并不能更新数据，这个组件做的是数组的相关操作。需要把预期的数组更新。



在 2020-12-21 14:29:09，"Liu" <notifications@github.com> 写道：

你是指 type: array ，配置了 ui:widget ？ widget 都是v-model的形式，$emit('input', value);

**Comment by lljj-x** [comment]
你可以提供下codepon或类似代码演示。

如果ui:widget，需要v-model双向绑定值，实际就是  value props，和 emit('input', newValue) 更新数据

**Comment by hallwong** [comment]
这是json
`"schema": {
                "type": "object",
                "required": [],
                "properties": {
                    //模板选择
                    "dataSource": {
                        "type": "array",
                        "title": "显示内容（至少选中两个）",
                        "items": {
                            "type": "string",
                            "enum": [
                                "1",
                                "2",
                                "3",
                                "4"
                            ],
                            "enumNames": [
                                "为你推荐",
                                "新品上架",
                                "热销商品",
                                "聚划算"
                            ]
                        },
                        "default":[],
                        "uniqueItems": true
                    },
                    "fontWeight": {
                        "title": "文本样式",
                        "type": "string",
                        "ui:widget": "RadioWidget",
                        "default": "normal",
                        "enum": [
                            "normal",
                            "bold"
                        ],
                        "enumNames": [
                            "常规",
                            "加粗"
                        ]
                    }
                },
                "ui:order": [
                    "dataSource",
                    "fontWeight"
                ]
            },
            "uiSchema": {
                "dataSource": {
                    // 'ui:widget': 'RadioWidget'
                    'ui:widget': () => import('@/components/themeEditor/componentsProperties/pageActive-CheckDataType')
                }
            },
            "formFooter": {
                "show": false
            },
            "formProps": {
                // "labelPosition": "left",
                "labelWidth": "100px",
                "labelSuffix": "："
            }`

这是自定义组件的代码
`<template>
  <div class="style-options-select">
    
    <el-checkbox-group v-model="form.checkedArray" @change="handleCheckedChange">
      
      <div v-for="(item,index) in dataOptions" class="check-item">
        <el-checkbox
            :label="item.value"
            :key="index">
          {{ item.label }}
        </el-checkbox>
      </div>
    </el-checkbox-group>
  </div>
</template>

<script>
export default {
  name: "pageActive-CheckDataType",
  props: ['value'],
  // watch: {
  //   value(val) {
  //
  //   }
  // },
  data() {
    return {
      form: {
        checkedArray: []
      },
      tempType: '',
      dataOptions: [
        {
          image: '',
          label: '为你推荐',
          value: '1'
        },
        {
          image: '',
          label: '新品上架',
          value: '2'
        },
        {
          image: '',
          label: '热销商品',
          value: '3'
        },
      ]
    }
  },
  mounted() {
    this.form.checkedArray = this.value.split(',');
  },
  methods: {
    handleCheckedChange(item) {
      this.$emit('input', this.form.checkedArray.toString())
    }
  }
}
</script>

<style scoped lang="scss">
.style-options-select {
  .check-item {
    display: block;
    background-color: #ffffff;
    padding: 0 5px;
    margin-bottom: 3px;

    label {
      display: block;
    }
  }
}
</style>
`

**Comment by hallwong** [comment]
实际测试只有type为string的自定义widget 可以用$emit( input )更新

**Comment by lljj-x** [comment]
你这里 emit 出去的字符串，是为了测试你说的字符串对吗 ？ 你提供一个 在线 https://codepen.io/ 代码演示吧

--

内部组件数组的同步值也是类似，比如 多选框，多文件上传都是这样方式，也可以参考下。

**Comment by hallwong** [comment]
好的。如果实在不能更新数组枚举，我就只能改变方式，用字符串模式。谢谢你的回复。

**Comment by lljj-x** [comment]
不客气，最终还是不行可以带上 在线代码演示。

**Comment by hallwong** [comment]
晚些我会我会截图说明。
