### ISSUE TITLE
配置 description 显示为 tooltip

### ISSUE THREAD

**Issue by shurong2199** [lljj-x/vue-json-schema-form#265]
### vue和ui框架
vue3、element plus

###  问题描述
多列布局，title 位置设置为 top 时，description 显示为文本，造成组件无法水平对齐

### 期望的结果
期望在 title 位置设置为 top 时，description 可以展示为 tooltip，而不是直接显示在 title 下方

**Comment by lljj-x** [comment]
和这边是一个类似的问题 #225

现在可以配置 [form-props isMiniDes](https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#form-props) 来配置是否显示为tooltip的样式。

但应该是不支持 array object 类型的配置 ，这个会上下显示

**Comment by shurong2199** [comment]
![image](https://user-images.githubusercontent.com/12151849/217771414-6ecdbc29-24fd-4304-af9d-58749e4724af.png)
