### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by Mike-Guan** [lljj-x/vue-json-schema-form#266]
WARNING  Compiled with 1 warning                                                                                        4:40:30 PM

 warning  in ./node_modules/@lljj/vue-json-schema-form/dist/vueJsonSchemaForm.esm.min.js

export 'default' (imported as 'e') was not found in 'vue' 

NOT sure how to solve this.

**Comment by shurong2199** [comment]
可能原因是装错了依赖：
如果环境是 vue3 + element-plus，应该装 @lljj/vue3-form-element。
如果装成了 @lljj/vue-json-schema-form，引起以上报错。
