### ISSUE TITLE
同类表单控件公共属性批量设置

### ISSUE THREAD

**Issue by shurong2199** [lljj-x/vue-json-schema-form#267]
### vue和ui框架
vue3、ElementPlus

###  问题描述
目前在做一个字段量较大的表单，想要统一设置所有输入框的maxLength 都为 50。
在每个字下都设置 "maxLength": 50 是可以实现，但是产生了大量的重复配置

### 期望的结果
有一处公共配置，可以控制同类控件的属性

请问，是否有类设置项

**Comment by lljj-x** [comment]
没有的。

`maxLength` 这个是属于数据层面的，校验只能在JSONschema的 配置上 maxLength

可能是换个思路 你生成schema的时候来默认所有的 string maxLength 都是 50

**Comment by shurong2199** [comment]
好的，感谢。也可以遍历一下 schema，遇到 string 就追加 maxLength 属性
