### ISSUE TITLE
如何设置 popover 主题为 dark

### ISSUE THREAD

**Issue by shurong-wang** [lljj-x/vue-json-schema-form#269]
### vue和ui框架
vue3、ElementPlus

###  问题描述
目前 description 的 popover 默认是 light 主题，想要设置为 dark

### 期望的结果
是否有类似设置可以实现
```
{
  "ui:options": {
    "popover": {
      "effect": "dark",
      "placement": "top-start"
    }
  }
}
```

**Comment by lljj-x** [comment]
目前不行，下个版本加个配置。

目前只能通过自定义field来实现

**Comment by shurong2199** [comment]
> > 目前不行，下个版本加个配置。
> > 目前只能通过自定义field来实现
> 
> 期待下个版本加上

**Comment by shurong2199** [comment]
popover 会生成在 body 下，覆盖样式还比较困难。期待更新~

**Comment by lljj-x** [comment]
五一更新

**Comment by lljj-x** [comment]
最新版支持按表单配置 formProps.popover ，单个item还不支持 ，理解应该一个表单是一致的所以暂不支持

```javascript
// formProps.popover
{
  "effect": "dark",
  "placement": "top-start"
}

```
