### ISSUE TITLE
如何配置表单控件的间距

### ISSUE THREAD

**Issue by shurong2199** [lljj-x/vue-json-schema-form#270]
### vue和ui框架
vue3、ElementPlus

###  问题描述
UI 设计表单控件的视频间距、垂直间距都非常大。  `formProps: { layoutColumn: 3 }` 展示的间距都很紧凑

### 期望的结果
请问如何配置表单控件的左右间距、上下间距

**Comment by lljj-x** [comment]
这个你可以直接覆盖全局样式的

**Comment by shurong2199** [comment]
好的，感谢
