### ISSUE TITLE
多选数组不支持设置默认值嘛

### ISSUE THREAD

**Issue by yangliguo7** [lljj-x/vue-json-schema-form#271]
```
{
  "schema": {
    "type": "object",
    "required": [],
    "properties": {
      "array_1677151659800x0": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "type": "string",
          "enum": [
            "1",
            "2",
            "3"
          ],
          "enumNames": [
            "一",
            "二",
            "三"
          ]
        },
        "title": "多选(Select)",
        "ui:widget": "SelectWidget"
      }
    },
    "ui:order": [
      "array_1677151659800x0"
    ]
  },
  "uiSchema": {},
  "formFooter": {
    "show": false
  },
  "formProps": {
    "labelWidth": "100px",
    "labelSuffix": "："
  }
}
```

设置default 没用

**Comment by lljj-x** [comment]
![image](https://user-images.githubusercontent.com/6283929/221553746-d6c0deb1-02ee-441e-8e0a-54967b2173c4.png)
ze'li这里面加上default 是可以的

**Comment by yangliguo7** [comment]
设置并没有作用 

```
{
  "schema": {
    "type": "object",
    "required": [],
    "properties": {
      "array_1677151659800x0": {
"default": ["1","2"],
        "type": "array",
        "uniqueItems": true,
        "items": {
          "type": "string",
          "enum": [
            "1",
            "2",
            "3"
          ],
          "enumNames": [
            "一",
            "二",
            "三"
          ]
        },
        "title": "多选(Select)",
        "ui:widget": "SelectWidget"
      }
    },
    "ui:order": [
      "array_1677151659800x0"
    ]
  },
  "uiSchema": {},
  "formFooter": {
    "show": false
  },
  "formProps": {
    "labelWidth": "100px",
    "labelSuffix": "："
  }
}
```

单独纯文本标签是可以生效的

@lljj-x

**Comment by lljj-x** [comment]
用的你的schema也没问题 [playground](https://form.lljj.me/#/demo?ui=VueElementForm&type=Test&schema=%7B%22type%22%3A%22object%22,%22required%22%3A%5B%5D,%22properties%22%3A%7B%22array_1677151659800x0%22%3A%7B%22default%22%3A%5B%221%22,%222%22%5D,%22type%22%3A%22array%22,%22uniqueItems%22%3Atrue,%22items%22%3A%7B%22type%22%3A%22string%22,%22enum%22%3A%5B%221%22,%222%22,%223%22%5D,%22enumNames%22%3A%5B%22%E4%B8%80%22,%22%E4%BA%8C%22,%22%E4%B8%89%22%5D%7D,%22title%22%3A%22%E5%A4%9A%E9%80%89%28Select%29%22,%22ui%3Awidget%22%3A%22SelectWidget%22%7D%7D,%22ui%3Aorder%22%3A%5B%22array_1677151659800x0%22%5D%7D&formData=%7B%22array_1677151659800x0%22%3A%5B%221%22,%222%22%5D%7D&uiSchema=%7B%7D&errorSchema=%7B%7D&formFooter=%7B%22show%22%3Atrue%7D&formProps=%7B%22labelWidth%22%3A%22100px%22,%22inline%22%3Afalse,%22labelPosition%22%3A%22top%22,%22inlineFooter%22%3Afalse,%22layoutColumn%22%3A1%7D)

**Comment by yangliguo7** [comment]
是的，然而在 https://form.lljj.me/schema-generator.html#/index 这里去导入schema 却不表现出默认值

感谢回复
