### ISSUE TITLE
请问大佬，datepicker如何支持限定可选择的日期

### ISSUE THREAD

**Issue by wjianjie** [lljj-x/vue-json-schema-form#275]
vue和ui框架
vue2、ElementUI

问题描述
对于日期选择器来说，这个是很平常的需求，但是element-ui是要配置函数还实现的，json-schema如何支持

**Comment by lljj-x** [comment]
有两个办法：

1. 通过js传递ElementUi要求的function形式参数，如果之前使用的纯json这个方案就不合适了。

2. 自定义一个widget包装下datePicker，自定义需要的区间参数，组件内处理成element要求的function形式

**Comment by wjianjie** [comment]
感谢大佬，第2点我后来看了一下已经在准备弄了，第1点我再请教一下，我也是最近开始了解json schema，使用大佬开发的这个库，纯JSON之外的方案是指哪个？

**Comment by lljj-x** [comment]
1.  js代码里面写参数，只是不能是个存的json了
```js
{
type: 'string',
'ui:elementUiDateRange': (opts)=> {
  return xxx
}
}
```

**Comment by wjianjie** [comment]
感谢大佬，我也去看过formily的一些功能，他们是自己写表达式，然后把表达式作为字符串存在json里，个人觉得这样的解决办法不太好，还是按需封装widget更好一些吧，再次感谢

**Comment by lljj-x** [comment]
是的，有这个考虑觉得 写函数字符串在json里面 体验太奇怪了 ，也不会计划支持这部分
