### ISSUE TITLE
请问有支持响应式布局吗？

### ISSUE THREAD

**Issue by luchanan** [lljj-x/vue-json-schema-form#277]
请问有没有像bootstrap那个的响应式布局的参数吗？xs, sm....适应不同的屏幕。

另外还有个问题现在列数只能设置整个表单，如果第一行要独占一行，但是宽度是50%，右边要保持空的，第二行有两个input， 各保持50%宽度。现在是不是没有办法呢？

**Comment by lljj-x** [comment]
1. 是没有的 ，适配的组件库都是在桌面端的，移动懂体验其实不会好。 目前也只是支持对应ui组件库的size参数透传。
2. 这个暂时配置应该是不行的，除非第一行和第二行是两个单独的 object ，或者就是需要自定义field 来支持你想要的布局形式

因为目前是数据优先，form结构会优先和数据结构来一致。如果需要的是ui优先的配置，其实不推荐这个
