### ISSUE TITLE
description栏无法正确的显示<ul>标签

### ISSUE THREAD

**Issue by Jaden-47** [lljj-x/vue-json-schema-form#279]
### vue和ui框架
vue3、ui框架element plus、vjsf: "@lljj/vue3-form-element": "^1.14.2"

###  问题描述
在playground的ui:schema（表达式）例子中，给任一object的description赋值时无法正确显示```<ul>```标签。虽然```<ol>```可以正常使用。
![image](https://user-images.githubusercontent.com/77352220/225550431-030a1ac7-799f-445f-a6a6-d33c6cd673a8.png)
![image](https://user-images.githubusercontent.com/77352220/225550544-ce921205-a9d1-4ccf-95d3-7cb532e1b371.png)

### 如何复现
在schema中，给任一object赋予属性```“description”:"<ul><li>项目1</li><li>项目2</li></ul>"```

### 期望的结果
```“description”:"<ul><li>项目1</li><li>项目2</li></ul>"```能正确显示格式

**Comment by Jaden-47** [comment]
似乎是ul标签的list-style-type和padding-left属性被修改了，导致显示不出来。正确设置如下
```
<ul style="list-style-type:disc; padding-left:20px;"></ul>

**Comment by lljj-x** [comment]
可以看下是哪里的css覆盖了，可以自己css处理下

**Comment by Jaden-47** [comment]
> 可以看下是哪里的css覆盖了，可以自己css处理下

![image](https://user-images.githubusercontent.com/77352220/226814711-c91a3d8a-f4e8-4e91-9bb0-4f53a8cb9e58.png)
被这个组件的css给覆盖了

**Comment by Jaden-47** [comment]
> 可以看下是哪里的css覆盖了，可以自己css处理下

不好意思，本地的vue3 + element plus的版本是没问题的。只有playground有问题
