### ISSUE TITLE
可以单个运行，实现单个打包了吗？

### ISSUE THREAD

**Issue by MHappy135246** [lljj-x/vue-json-schema-form#28]
# 只运行 Playground
yarn run demo:dev --dir=index可以这样单个运行，可以单个打包发布？

**Comment by lljj-x** [comment]
这个只是 demo 页的运行，demo页内是多entry ，指定 --dir 就是查找目录固定webpack entry 配置。

demo:build 、 demo:dev 命令都支持 dir 参数
