### ISSUE TITLE
Render label with html syntax inside

### ISSUE THREAD

**Issue by BossHogg97** [lljj-x/vue-json-schema-form#281]
Hi, i'm working with vue3 and Naive UI.
I need to render a label with html inside containing superscript and subscript. Is there a way to solve this problem?

This is the actual result:
![image](https://user-images.githubusercontent.com/49211261/226671446-d93a9e70-feb8-4de5-97b0-f121b37f6249.png)

Thanks

**Comment by lljj-x** [comment]
Not supported now

`description` can use html code

**Comment by BossHogg97** [comment]
In `description` field i can directly use the html code and is converted into subscript or superscript string?
Thanks

**Comment by BossHogg97** [comment]
Hi, i found a possible solution for my problem. Instead of use HTML to render subscript i use unicode and is working ;)
