### ISSUE TITLE
Make object/array foldable

### ISSUE THREAD

**Issue by darianstlex** [lljj-x/vue-json-schema-form#283]
Would be nice to be able to fold OBJECT/ARRAY node, in case of many props/children

### vue和ui框架
vue3, element-plus

**Comment by lljj-x** [comment]
可以通过使用自定义field  `ui:field` 来实现

参考这种tab的例子
https://github.com/lljj-x/schema-form-components

**Comment by darianstlex** [comment]
Thanks, going to try
