### ISSUE TITLE
建议在hidden起效时，清空对应属性值

### ISSUE THREAD

**Issue by ok958726** [lljj-x/vue-json-schema-form#286]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2 、ui框架element 

###  问题描述
通过hidden实现联动时，对应的属性值不清空或删除。
不像通过anyOf联动时，可以动态删除属性。但是anyOf用起来会有固定布局和样式，且没有hidden的function用起来方便
### 如何复现
官网示例
https://form.lljj.me/#/demo?ui=VueElementForm&type=uiSchema-ui-hidden%28%E8%81%94%E5%8A%A8%29
先填把显示更多打开，填写输入框值，然后把显示更多关闭，输入框值没清空或删除

### 期望的结果
可以通过配置，设定是否删除已经隐藏项目的属性值。

**Comment by lljj-x** [comment]
这种不会支持

ui控制的只是ui层面的显示隐藏

schema控制数据结构

**Comment by ok958726** [comment]
> 这种不会支持
> 
> 
> 
> ui控制的只是ui层面的显示隐藏
> 
> 
> 
> schema控制数据结构

那请问要实现隐藏ui 时，也清除该值，是不是自己手动清除，或者使用anyof ？

**Comment by lljj-x** [comment]
对，可以anyone ，或者自己配置回调 判断清空数据逻辑
