### ISSUE TITLE
anyof 如何在选项值都不满足的情况下，默认不进行选择？

### ISSUE THREAD

**Issue by theharveyz** [lljj-x/vue-json-schema-form#287]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3  antd
###  问题描述
anyof 如何在选项值都不满足的情况下，默认不进行选择，而不是选第1个？

**Comment by lljj-x** [comment]
现在不能配置，对表单来说提交的时候必须需要anyof 一个option

不过你可以通过加一个兜底的anyOf条件来实现
