### ISSUE TITLE
项目拉下来了依赖下了运行项目会出现如下报错是不是因为node.js的版本太高

### ISSUE THREAD

**Issue by hzf123456789** [lljj-x/vue-json-schema-form#290]
Node.js v18.16.0
error command failed with exit code 1
info visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
error command failed
exit code:1
command:c:\program files\nodejs\node.exe
arguments:c:\users\admin\appdata\roaming\npm\node_modules\yarn\lib\cli.js dev
directory:c:\users\admin\desktop\vue-json-schema-form\packages\demo\demo-v2

**Comment by lljj-x** [comment]
可能是，试试node12 , yarn 1.2x
