### ISSUE TITLE
vue3-form-core 在vite项目中引用报错

### ISSUE THREAD

**Issue by azoth1991** [lljj-x/vue-json-schema-form#292]
vite.config.ts 
```
  plugins: [vue(), babel({
    exclude: /node_modules\/(?!(@lljj)\/).*/,
    extensions: ['.js', '.vue'],
  }),],

```

<img width="567" alt="image" src="https://user-images.githubusercontent.com/10417344/234578247-d0bec21a-c5f2-4521-bfde-23550a1e3a1d.png">

**Comment by lljj-x** [comment]
.vue 后缀问题，配置下 extensions 支持 .vue

**Comment by lljj-x** [comment]
补充了后缀 可以试试最新版

**Comment by mice33** [comment]
```
✘ [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

    node_modules/@lljj/vjsf-utils/vueUtils.js:5:7:
      5 │ import Vue from 'vue';
```

也是 vite 项目, 引入的 vue3-form-core, 报错信息如上

@lljj-x

**Comment by mice33** [comment]
> ```
> ✘ [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
> 
>     node_modules/@lljj/vjsf-utils/vueUtils.js:5:7:
>       5 │ import Vue from 'vue';
> ```
> 
> 也是 vite 项目, 引入的 vue3-form-core, 报错信息如上
> 
> @lljj-x

查到问题了, 在 vjsf-utils/vue3Utils.js 和 vjsf-utils/formUtils.js 中引用了 vueUtils.js，vueUtils.js 中引入了 Vue2..
把 vueUtils.js 中的 `nodePath2ClassName, isRootNodePath, computedCurPath, getPathVal, path2prop` 单独剥离出一个 vue 公共工具 js 就行了
没找到 vjsf-utils 仓库位置, 只能等作者修复了

**Comment by lljj-x** [comment]
@mice33  对 很有道理，可以贡献就更好了 

不过你的使用方式是基于源码导入的吗 ？vue3 utils build之后vue2的导入部分应该是会被rollup shake掉

**Comment by mice33** [comment]
@lljj-x 没找到 vjsf-utils 仓库位置。。

嗯对，要基于 vant 写一个只能源码导入了

**Comment by lljj-x** [comment]
@lljj/vjsf-utils 在这个下面 ，可以按你说的抽出来会更合适

**Comment by lljj-x** [comment]
https://github.com/lljj-x/vue-json-schema-form/blob/master/packages/lib/utils/vue3Utils.js
