### ISSUE TITLE
当下拉组件设置为允许添加时，对于添加的选项不应校验失败：`应当是预设定的枚举值之一`

### ISSUE THREAD

**Issue by wll8** [lljj-x/vue-json-schema-form#298]
当下拉组件设置为允许添加时，对于添加的选项不应校验失败：`应当是预设定的枚举值之一`

组件库属性参考: [创建新的选项](https://element-plus.org/zh-CN/component/select.html#%E5%88%9B%E5%BB%BA%E6%96%B0%E7%9A%84%E9%80%89%E9%A1%B9)

### vue和ui框架
- @lljj/vue3-form-element@1.17.0

###  问题描述
当下拉组件设置为允许添加时，对于添加的选项不应校验失败：`应当是预设定的枚举值之一`

### 如何复现
使用一个 element-plus 下拉单选组件，并设置允许添加属性：

``` txt
"ui:options": {
    "filterable": true,
    "allowCreate": true
},
```

[playground](https://form.lljj.me/v3/#/demo?ui=VueElementForm&type=Test&schema={%22type%22:%22object%22,%22properties%22:{%22%E5%88%86%E7%B1%BB%22:{%22title%22:%22%E5%88%86%E7%B1%BB%22,%22type%22:%22string%22,%22ui:widget%22:%22SelectWidget%22,%22enum%22:[%22%E5%B1%85%E5%AE%B6%E7%89%A9%E4%B8%9A%22,%22%E4%BC%99%E9%A3%9F%E9%A4%90%E9%A5%AE%22,%22%E4%BC%91%E9%97%B2%E5%A8%B1%E4%B9%90%22,%22%E8%A1%8C%E8%BD%A6%E4%BA%A4%E9%80%9A%22,%22%E7%BE%8E%E5%AE%B9%E6%8A%A4%E8%82%A4%22,%22%E8%A1%A3%E6%9C%8D%E9%A5%B0%E5%93%81%22,%22%E9%80%9A%E8%AE%AF%E4%BA%A4%E6%B5%81%22,%22%E5%AD%A6%E4%B9%A0%E8%BF%9B%E4%BF%AE%22,%22%E5%8C%BB%E7%96%97%E4%BF%9D%E9%9A%9C%22,%22%E5%85%B6%E4%BB%96%22],%22ui:options%22:{%22filterable%22:true,%22allowCreate%22:true},%22enumNames%22:[%22%E5%B1%85%E5%AE%B6%E7%89%A9%E4%B8%9A%22,%22%E4%BC%99%E9%A3%9F%E9%A4%90%E9%A5%AE%22,%22%E4%BC%91%E9%97%B2%E5%A8%B1%E4%B9%90%22,%22%E8%A1%8C%E8%BD%A6%E4%BA%A4%E9%80%9A%22,%22%E7%BE%8E%E5%AE%B9%E6%8A%A4%E8%82%A4%22,%22%E8%A1%A3%E6%9C%8D%E9%A5%B0%E5%93%81%22,%22%E9%80%9A%E8%AE%AF%E4%BA%A4%E6%B5%81%22,%22%E5%AD%A6%E4%B9%A0%E8%BF%9B%E4%BF%AE%22,%22%E5%8C%BB%E7%96%97%E4%BF%9D%E9%9A%9C%22,%22%E5%85%B6%E4%BB%96%22]}},%22ui:order%22:[%22%E5%88%86%E7%B1%BB%22]}&formData={%22%E6%94%B6%E6%94%AF%22:%22%22,%22%E5%88%86%E7%B1%BB%22:%22asfasf%22}&uiSchema={}&errorSchema={}&formFooter={%22show%22:false}&formProps={%22inline%22:false,%22labelPosition%22:%22right%22,%22inlineFooter%22:false,%22layoutColumn%22:1,%22labelSuffix%22:%22:+%22,%22defaultSelectFirstOption%22:false,%22labelWidth%22:%2260px%22})

### 期望的结果
- `必须为预置选项` 这是否与实际业务相关? 应由用户自己去定义? 或者是否有快捷的方式关闭此特性?
- 有没有什么方式在配置中覆盖此行为?

**Comment by lljj-x** [comment]
这种属于打破schema规范的，就直接用ui配置

https://vue-json-schema-form.lljj.me/zh/guide/faq.html#select%E7%AD%9B%E9%80%89%E6%A1%86%E7%9A%84%E5%80%BC%E5%8F%AF%E4%BB%A5%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E5%90%97

**Comment by wll8** [comment]
`这种属于打破schema规范的` 的意思是说动态增加 enum 在 json schema 中是不允许的是吗？

如果确实如此，那么是否有选项忽略此行为？毕竟要自己实现逻辑来支持本来就有此功能的组件选项，习惯上有一些难受。

**Comment by lljj-x** [comment]
我印象中是jsonSchema 是没有这种语法，你可以再查查看。

数据都是需要先符合schema定义的结构，所以这个忽略还是一样  要先json Schema支持
