### ISSUE TITLE
report bug for array model in vue3

### ISSUE THREAD

**Issue by binahub** [lljj-x/vue-json-schema-form#299]
please check this url, the model is array of objects but the form doesnt render form, but in vue2 same sample renders correctly....

https://form.lljj.me/v3/#/demo?ui=VueElementForm&type=Simple&schema={%22definitions%22:{},%22$schema%22:%22http://json-schema.org/draft-07/schema%23%22,%22$id%22:%22https://example.com/object1683538070.json%22,%22title%22:%22Root%22,%22type%22:%22object%22,%22required%22:[%22list%22],%22properties%22:{%22list%22:{%22$id%22:%22%23root/list%22,%22title%22:%22List%22,%22type%22:%22array%22,%22default%22:[],%22items%22:{%22$id%22:%22%23root/list/items%22,%22title%22:%22Items%22,%22type%22:%22object%22,%22required%22:[%22id%22,%22bannerImage%22,%22link%22,%22name%22,%22type%22],%22properties%22:{%22id%22:{%22$id%22:%22%23root/list/items/id%22,%22title%22:%22Id%22,%22type%22:%22integer%22,%22examples%22:[0],%22default%22:0},%22bannerImage%22:{%22$id%22:%22%23root/list/items/bannerImage%22,%22title%22:%22Bannerimage%22,%22type%22:%22string%22,%22default%22:%22%22,%22examples%22:[%22https://clubpics.s3.ir-thr-at1.arvanstorage.ir/baner-taraland.jpg%22],%22pattern%22:%22^.*$%22},%22link%22:{%22$id%22:%22%23root/list/items/link%22,%22title%22:%22Link%22,%22type%22:%22string%22,%22default%22:%22%22,%22examples%22:[%22https://b2n.ir/t38932%22],%22pattern%22:%22^.*$%22},%22name%22:{%22$id%22:%22%23root/list/items/name%22,%22title%22:%22Name%22,%22type%22:%22string%22,%22default%22:%22%22,%22examples%22:[%22%D8%A8%D9%86%D8%B1%22],%22pattern%22:%22^.*$%22},%22type%22:{%22$id%22:%22%23root/list/items/type%22,%22title%22:%22Type%22,%22type%22:%22string%22,%22default%22:%22%22,%22examples%22:[%22main%22],%22pattern%22:%22^.*$%22}}}}}}&formData=[{%22id%22:0,%22bannerImage%22:%22https://clubpics.s3.ir-thr-at1.arvanstorage.ir/baner-taraland.jpg%22,%22link%22:%22https://b2n.ir/t38932%22,%22name%22:%22%D8%A8%D9%86%D8%B1%22,%22type%22:%22main%22},{%22id%22:1,%22bannerImage%22:%22https://clubpics.s3.ir-thr-at1.arvanstorage.ir/banner-offline.png%22,%22link%22:%22%22,%22name%22:%22%D8%A8%D9%86%D8%B1+%D9%BE%D8%B0%DB%8C%D8%B1%D9%86%D8%AF%DA%AF%D8%A7%D9%86+%D8%AD%D8%B6%D9%88%D8%B1%DB%8C%22,%22type%22:%22offline%22},{%22id%22:2,%22bannerImage%22:%22string%22,%22link%22:%22string%22,%22name%22:%22string%22,%22type%22:%22online%22}]&uiSchema={}&errorSchema={}&formFooter={%22formItemAttrs%22:{%22wrapperCol%22:{%22span%22:24,%22offset%22:0}}}&formProps={%22inline%22:false,%22labelPosition%22:%22top%22,%22inlineFooter%22:false,%22layoutColumn%22:1,%22labelCol%22:{%22span%22:6},%22wrapperCol%22:{%22span%22:16},%22labelWidth%22:%22100px%22}

**Comment by lljj-x** [comment]
感谢反馈 这周会修复

**Comment by lljj-x** [comment]
formdata is an object, not array

[preview link](https://form.lljj.me/#/demo?ui=VueElementForm&type=Test&schema=%7B%22definitions%22%3A%7B%7D,%22%24schema%22%3A%22http%3A%2F%2Fjson-schema.org%2Fdraft-07%2Fschema%23%22,%22%24id%22%3A%22https%3A%2F%2Fexample.com%2Fobject1683538070.json%22,%22title%22%3A%22Root%22,%22type%22%3A%22object%22,%22required%22%3A%5B%22list%22%5D,%22properties%22%3A%7B%22list%22%3A%7B%22%24id%22%3A%22%23root%2Flist%22,%22title%22%3A%22List%22,%22type%22%3A%22array%22,%22default%22%3A%5B%5D,%22items%22%3A%7B%22%24id%22%3A%22%23root%2Flist%2Fitems%22,%22title%22%3A%22Items%22,%22type%22%3A%22object%22,%22required%22%3A%5B%22id%22,%22bannerImage%22,%22link%22,%22name%22,%22type%22%5D,%22properties%22%3A%7B%22id%22%3A%7B%22%24id%22%3A%22%23root%2Flist%2Fitems%2Fid%22,%22title%22%3A%22Id%22,%22type%22%3A%22integer%22,%22examples%22%3A%5B0%5D,%22default%22%3A0%7D,%22bannerImage%22%3A%7B%22%24id%22%3A%22%23root%2Flist%2Fitems%2FbannerImage%22,%22title%22%3A%22Bannerimage%22,%22type%22%3A%22string%22,%22default%22%3A%22%22,%22examples%22%3A%5B%22https%3A%2F%2Fclubpics.s3.ir-thr-at1.arvanstorage.ir%2Fbaner-taraland.jpg%22%5D,%22pattern%22%3A%22%5E.%2a%24%22%7D,%22link%22%3A%7B%22%24id%22%3A%22%23root%2Flist%2Fitems%2Flink%22,%22title%22%3A%22Link%22,%22type%22%3A%22string%22,%22default%22%3A%22%22,%22examples%22%3A%5B%22https%3A%2F%2Fb2n.ir%2Ft38932%22%5D,%22pattern%22%3A%22%5E.%2a%24%22%7D,%22name%22%3A%7B%22%24id%22%3A%22%23root%2Flist%2Fitems%2Fname%22,%22title%22%3A%22Name%22,%22type%22%3A%22string%22,%22default%22%3A%22%22,%22examples%22%3A%5B%22%D8%A8%D9%86%D8%B1%22%5D,%22pattern%22%3A%22%5E.%2a%24%22%7D,%22type%22%3A%7B%22%24id%22%3A%22%23root%2Flist%2Fitems%2Ftype%22,%22title%22%3A%22Type%22,%22type%22%3A%22string%22,%22default%22%3A%22%22,%22examples%22%3A%5B%22main%22%5D,%22pattern%22%3A%22%5E.%2a%24%22%7D%7D%7D%7D%7D%7D&formData=%7B%22list%22%3A%5B%7B%22id%22%3A0,%22bannerImage%22%3A%22https%3A%2F%2Fclubpics.s3.ir-thr-at1.arvanstorage.ir%2Fbaner-taraland.jpg%22,%22link%22%3A%22https%3A%2F%2Fb2n.ir%2Ft38932%22,%22name%22%3A%22%D8%A8%D9%86%D8%B1%22,%22type%22%3A%22main%22%7D,%7B%22id%22%3A1,%22bannerImage%22%3A%22https%3A%2F%2Fclubpics.s3.ir-thr-at1.arvanstorage.ir%2Fbanner-offline.png%22,%22link%22%3A%22%22,%22name%22%3A%22%D8%A8%D9%86%D8%B1%20%D9%BE%D8%B0%DB%8C%D8%B1%D9%86%D8%AF%DA%AF%D8%A7%D9%86%20%D8%AD%D8%B6%D9%88%D8%B1%DB%8C%22,%22type%22%3A%22offline%22%7D,%7B%22id%22%3A2,%22bannerImage%22%3A%22string%22,%22link%22%3A%22string%22,%22name%22%3A%22string%22,%22type%22%3A%22online%22%7D%5D%7D&uiSchema=%7B%7D&errorSchema=%7B%7D&formFooter=%7B%22formItemAttrs%22%3A%7B%22wrapperCol%22%3A%7B%22span%22%3A24,%22offset%22%3A0%7D%7D%7D&formProps=%7B%22labelWidth%22%3A%22100px%22,%22inline%22%3Afalse,%22labelPosition%22%3A%22top%22,%22inlineFooter%22%3Afalse,%22layoutColumn%22%3A1,%22labelCol%22%3A%7B%22span%22%3A6%7D,%22wrapperCol%22%3A%7B%22span%22%3A16%7D%7D)
