### ISSUE TITLE
configTools的数据清理

### ISSUE THREAD

**Issue by 0606tcm** [lljj-x/vue-json-schema-form#30]
可以将editor的中const components = getComponentsAndInitToolsConfig(configTools);
在其他位置进行数据初始化，放在editor的变量中进行初始化，存在点问题，不好新手理解

**Comment by lljj-x** [comment]
我考虑了下，config 中存放的只是工具栏相关的配置文件，Editor 中使用到这些配置的时候会去初始化，这样不知是否更好理解。

如果你有觉得更清晰的模块划分 非常欢迎发起 pull request
