### ISSUE TITLE
anyof联动时选项的值不会变化，无论怎么选提交的都是默认值

### ISSUE THREAD

**Issue by brucesq** [lljj-x/vue-json-schema-form#300]
https://vue-json-schema-form.lljj.me/zh/guide/data-linkage.html#anyof-%E5%AE%9E%E7%8E%B0%E6%95%B0%E6%8D%AE%E8%81%94%E5%8A%A8
这个链接中的第一个例子，无论怎么选提交的结果userInfo.type的值一直是userInfo
{
  "price": 99999.99,
  "userInfo": {
    "type": "userInfo",
    "firstName": "Jun",
    "lastName": "Liu"
  },
  "url": "https://lljj.me",
  "projects": [
    {
      "url": "https://www.demo.com"
    }
  ],
  "age": 18
}

**Comment by lljj-x** [comment]
感谢反馈 这周会修复

**Comment by lljj-x** [comment]
文档demo已更新
