### ISSUE TITLE
大佬，请问如何适配其他UI组件库，比如uni-ui等移动端

### ISSUE THREAD

**Issue by peterzheng1** [lljj-x/vue-json-schema-form#302]
希望能够适配移动端UI组件，可以告诉从何做起吗？感谢大佬！

**Comment by lljj-x** [comment]
可以参考已有的ui适配，都是基于core来的

**Comment by peterzheng1** [comment]
我翻看了您的
![image](https://github.com/lljj-x/vue-json-schema-form/assets/43431817/8f34840d-809f-4d81-b70d-3cb5b573d31e)
并且查看了https://github.com/lljj-x/vue-json-schema-form/tree/master/packages/lib/vue3/vue3-form-ant
不太明白，可以简单说下步骤吗

**Comment by lljj-x** [comment]
简单理解就是配置下 globalOptions 里面WIDGET_MAP 、COMPONENT_MAP、HELPERS 这些配置的mapping 

因为没类型所以需要自己看下之前具体配置，


`WIDGET_MAP`   按类型默认渲染的Widget组件，渲染对应数据类型的格式，组件都要实现 v-model 

`COMPONENT_MAP` 表单自身相关的组件，form formItem button popover，然后组件默认渲染的props slot不一致需要转换到你自己ui库的即可。默认格式是elementUi的参数格式

`HELPERS` 这里面只有一个判断显示description格式需不需要mini格式
