### ISSUE TITLE
vue3-form-element使用vue3组合式写法没有实现双向数据绑定

### ISSUE THREAD

**Issue by FishPinex** [lljj-x/vue-json-schema-form#303]
### vue和ui框架
使用的@lljj/vue3-form-element

###  问题描述
vue-form组件的v-model的绑定值在vue3组合式语法中没有双向数据绑定，改用选项式语法实现了双向数据绑定
![image](https://github.com/lljj-x/vue-json-schema-form/assets/100849646/3dd3595c-5ed2-466d-b75e-6a6986fc98da)

### 如何复现
创建一个vue-form组件实例，采用组合式语法，打印表单值，数据没有被变更

### 期望的结果
现在不确定是我一个人的问题吗，还是本身就不支持组合式写法呢

**Comment by lljj-x** [comment]
v-modal配置 reactive   -> ref
