### ISSUE TITLE
vue3 antDv中textarea不生效，显示的是input输入框

### ISSUE THREAD

**Issue by OneDayPhotography** [lljj-x/vue-json-schema-form#306]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3、antd、vjsf版本v1.17.1

###  问题描述
使用type配置为textarea，显示的是input输入框

### 如何复现
- 只在vue3的antdv出现
- 官网Playground 中demo，选择vue3、antdv，bio 的type设定为textarea类型，但仍然显示的是input输入框

### 期望的结果
textarea多行的文本输入控件

**Comment by lljj-x** [comment]
#274 参考这个
