### ISSUE TITLE
help to show custom element

### ISSUE THREAD

**Issue by binahub** [lljj-x/vue-json-schema-form#308]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
Vue 3 , elementPlus

###  问题描述
i want to get jsonSchema if has some specifc format that its not in default like (my-date-time) not (date-time), render my own component, can you please help me with this? 

thanks

**Comment by binahub** [comment]
i mean i have custom date picker package, i want to if i get for example "myDatePicker" format from jsonSchema, it renders that datePicker form another package or component, plz help


thanks

**Comment by lljj-x** [comment]
Custom format is not supported, but you can use your components through `ui:widget`

```js
{
    "title": "测试专用页",
    "type": "object",
    "properties": {
        "selectWidgetOptions": {
            "title": "Custom date picker",
            "type": "string",
            "ui:widget": myDatePicker,
            "ui:youoption1": "1",
            "ui:youoption2": "2",
        }
    }
}

```

`myDatePicker` component must suport v-model

vue v-model https://vuejs.org/guide/components/v-model.html
 
> Future versions are planned to support configuration through `format`.
