### ISSUE TITLE
按需引入antdv，组件为什么不能展示

### ISSUE THREAD

**Issue by yhzhang5210** [lljj-x/vue-json-schema-form#312]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2或者vue3、ui框架element antd、vjsf 使用版本说明
vue3-form-ant
###  问题描述
对错误是什么的清晰简洁的描述。
无任何报错，仅显示保存和取消，查看内容发现页面元素已加载，css样式没有加载进来
### 如何复现
可以详细介绍你的复现场景或者相关代码。

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

### 期望的结果
....

**Comment by lljj-x** [comment]
需要注册下相关组件，按控制台提示缺少的组件注册

https://github.com/lljj-x/vue-json-schema-form/issues/169#issuecomment-1094141802
