### ISSUE TITLE
同样的Schema在vue2版本可以正常使用，在vue3版本不可以

### ISSUE THREAD

**Issue by Yelingxiao** [lljj-x/vue-json-schema-form#321]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3 antd
###  问题描述
对错误是什么的清晰简洁的描述。

### 如何复现
浏览器报TypeError: p.pushArray.map is not a function

### 期望的结果
....

**Comment by lljj-x** [comment]
发现复现demo
