### ISSUE TITLE
下拉框提示 应当是预设值定的枚举值之一

### ISSUE THREAD

**Issue by turning1998** [lljj-x/vue-json-schema-form#322]
### vue和ui框架
"vue": "^3.2.33",  
 "ant-design-vue": "^3.2.15",  
 "@lljj/vue3-form-ant": "^1.17.1",
    "@lljj/vue3-form-core": "^1.17.1",

###  问题描述
下拉框的 enum enumName ，是后面push进去的，会提示应当是预设值定的枚举值之一

### 如何复现
![1692930833852](https://github.com/lljj-x/vue-json-schema-form/assets/47552222/952d7eb3-15bb-4c8b-bfef-c6c5266c2347)

### 期望的结果
删除提示或者其他解决办法

**Comment by lljj-x** [comment]
这种就不要用schema的规则来，可以直接用 ui:options 配置

参考这个方法
https://vue-json-schema-form.lljj.me/zh/guide/faq.html#select%E7%AD%9B%E9%80%89%E6%A1%86%E7%9A%84%E5%80%BC%E5%8F%AF%E4%BB%A5%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E5%90%97
