### ISSUE TITLE
vue2+element 下拉框 单选框等无法渲染，设置enum和'ui:enumOptions'都无法正确展示

### ISSUE THREAD

**Issue by angellala** [lljj-x/vue-json-schema-form#326]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2 + element

###  问题描述
对错误是什么的清晰简洁的描述。

### 如何复现
配置如下：
schema: {
        type: 'object',
        properties: {
          stringRadio: {
            title: '单选(Radio)',
            type: 'string',
            'ui:widget': 'RadioWidget',
            'ui:enumOptions': [
              { value: '1', label: '一' },
              { value: '2', label: '二' },
              { value: '3', label: '三' }
            ],
            'ui:options': {
              width: '33.333%'
            }
          },
          stringSelect: {
            title: '单选(Select)',
            type: 'string',
            'ui:widget': 'SelectWidget',
            enum: [
              '1',
              '2',
              '3'
            ],
            enumNames: [
              '一',
              '二',
              '三'
            ],
            'ui:options': {
              width: '33.333%'
            }
          }
        }
      }

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等
![image](https://github.com/lljj-x/vue-json-schema-form/assets/24931840/e5c5beb3-79a5-4ae2-b0bb-6c6342be2ea5)
![image](https://github.com/lljj-x/vue-json-schema-form/assets/24931840/2f7a73bf-158f-4be8-942e-86f58a772d35)

### 期望的结果
....

**Comment by angellala** [comment]
输入框等其他控件可正常展示，配置选项相关的都无法正常渲染

**Comment by lljj-x** [comment]
先注册相关组件库，element ui 类似一下 

Vue.use(ElementUi)

**Comment by angellala** [comment]
项目中使用的就是elementUi,已经全局注册了，还是不可以呢
![image](https://github.com/lljj-x/vue-json-schema-form/assets/24931840/19c7dee2-8cf8-46f1-af86-742066ed0332)

**Comment by lljj-x** [comment]
你window的全局vue是哪来的 ？

现在是你项目内有两份vue实例，一个全局window ，一个npm包里面的 ，配置下external vue都用你的window下的

**Comment by angellala** [comment]
非常感谢，可以了

**Comment by angellala** [comment]
已解决！
