### ISSUE TITLE
select 下拉框怎么绑定值为对象

### ISSUE THREAD

**Issue by angellala** [lljj-x/vue-json-schema-form#327]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2+elementui

###  问题描述
select 的值绑定为object，直接设置type为'object'报错了

### 如何复现
SelectWidget

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

stringSelect: {
            title: '单选(Select)',
            type: 'string',
            'ui:widget': 'SelectWidget',
            enum: [
              '1',
              '2',
              '3'
            ],
            enumNames: [
              '一',
              '二',
              '三'
            ]
          }

### 期望的结果
....

**Comment by lljj-x** [comment]
默认数据结构不行  需要自定义 field

**Comment by angellala** [comment]
好的，使用自定义field是可以的。以为表单上有很多数据联动，页面数据监听后，需要触发自定义field 里的请求，请问父组件支持调用field里的方法嘛？

**Comment by lljj-x** [comment]
现在不能直接ref来调用field组件，不过可以  'ui:fieldProps' 来传递参数给到你自定义的field，所以实际你可以传出来你的组件实例

**Comment by angellala** [comment]
通过自定义field已解决，非常感谢！
