### ISSUE TITLE
customrule 自定义校验 成功我希望就校验成功，但是如果schema校验失败会即使自动义校验成功也会校验失败。希望自定义校验结果最高

### ISSUE THREAD

**Issue by zhangchuanbo** [lljj-x/vue-json-schema-form#328]
### vue和ui框架
vue3 ui框架 element-plus

###  问题描述
customrule 自定义校验 成功我希望就校验成功，但是如果schema校验失败会即使自动义校验成功也会校验失败。希望自定义校验结果最高

### 如何复现
可以直接使用的数据校验尝试

### 期望的结果

customrule 自定义校验 成功我希望就校验成功，校验失败就失败，但是如果schema校验失败会即使自动义校验成功也会校验失败。希望自定义校验结果最高

**Comment by lljj-x** [comment]
customrule 其实现在是 extra rules 的意思，如果有冲突的规则在schema里面别配置对应的规则可以解决 ？

**Comment by zhangchuanbo** [comment]
主要是数组的校验，比如第一个数组，我需要默认展示一个，minitems为1，但是我又想他不是必填项目

**Comment by lljj-x** [comment]
required别配置就不会必填吧

**Comment by zhangchuanbo** [comment]
err:required配置了，但是required没配置

**Comment by lljj-x** [comment]
schema 可以贴出来看看
