### ISSUE TITLE
怎么把生成的页面 做成一个单独的html 来显示？

### ISSUE THREAD

**Issue by CL545740896** [lljj-x/vue-json-schema-form#33]
求一个demo 教程

**Comment by lljj-x** [comment]
目前这个编辑只是帮你生成json数据，并不直接生成html。

---
需要显示可以遍历保存的json，重新渲染对应的组件库即可。

伪代码如下：
> 需要保证 name 能正确映射到对应组件
```html
<template>
<div class="list">
   <component v-for="item in jsonData" :is="item.name" :formData="item.value"></component>
</div>
</template>
```

```js
const jsonData = [{
  name: 'name1',
  value: {...}
}]

const View = {
  data() {
  return {
    jsonData,
  }
}

```

**Comment by CL545740896** [comment]
如何根据json 遍历加载组件？

**Comment by CL545740896** [comment]
> 如何根据json 遍历加载组件？


  | warn
-- | --

**Comment by CL545740896** [comment]
vue.js:634 [Vue warn]: Unknown custom element: <MText> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Main> at src/pages/vue-editor/views/editor/Main.vue
       <App> at src/pages/vue-editor/App.vue
         <Root>

**Comment by lljj-x** [comment]
1、首先你要注册你组件库的组件
2、遍历你的json 数据，渲染对应组件，template 需要使用 component is 来实现，或者写render 函数，可以去查 vue 官方文档
