### ISSUE TITLE
配置 description，可以支持自定义icon嘛？

### ISSUE THREAD

**Issue by angellala** [lljj-x/vue-json-schema-form#331]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2 + ui框架element 

###  问题描述
配置 description，目前的提示icon和项目中已有的icon风格不符，请问支持自定义嘛？

### 如何复现
可以详细介绍你的复现场景或者相关代码。

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

### 期望的结果
....

**Comment by lljj-x** [comment]
似乎不行  内置的，不能覆盖配置

**Comment by angellala** [comment]
好的，谢谢
