### ISSUE TITLE
自定义field组件，如何通过$emit()调用父组件方法

### ISSUE THREAD

**Issue by angellala** [lljj-x/vue-json-schema-form#335]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2 + elementUi

###  问题描述
自定义field组件中 有一些按钮操作，按钮的点击事件需要调用父组件的方法 触发请求。是否支持$emit()以及父组件的方法如何传递到自定义field中

### 如何复现

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

**Comment by lljj-x** [comment]
schema是可以自由搭配的 所以不会有通过父子了交互。只能通过给 field 加props传递进来

**Comment by angellala** [comment]
是给 field 加props，传递父组件的方法过来嘛？还是说传递一个标识，field修改标识，父组件监听从而触发？

**Comment by lljj-x** [comment]
按你这个描述 似乎只能是给父组件传props，监听变化重新请求数据

**Comment by angellala** [comment]
好的，了解了
