### ISSUE TITLE
希望能给活动编辑增加富文本组件

### ISSUE THREAD

**Issue by CL545740896** [lljj-x/vue-json-schema-form#34]
https://www.npmjs.com/package/vue-editor-interline 这个组件还不错~

**Comment by lljj-x** [comment]
这个你只需要在tools里面加上一个新的组件，在你的视图组件导入这个即可，富文本保存数据就需要结合你现有的项目提供接口做数据保存。

---
方法大致如上，这个编辑器只实现了最基础的数据配置，后续不在更新。

目前主要是做schema表单的后续迭代，所以这里需要你自己处理。
