### ISSUE TITLE
布局配置:formProps属性不生效

### ISSUE THREAD

**Issue by AlexanderJi** [lljj-x/vue-json-schema-form#340]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue2或者vue3、ui框架element antd、vjsf 使用版本说明

###  问题描述
对错误是什么的清晰简洁的描述。
按照文档示例，配置:formProps属性不能使表单布局配置生效。后在在线测试中console提示:
`[Vuetip]: Prop 'formprops' is passed to component <Anonymous>, but the declared prop name is 'formProps'. Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use 'form-props' instead of 'formProps'.` 
改成:form-props后生效了。建议更新文档示例。
### 如何复现
可以详细介绍你的复现场景或者相关代码。

必要时提供复现demo，如codepen，github 复现仓库，playground分享链接等

### 期望的结果
....

**Comment by lljj-x** [comment]
You should probably use 'form-props' instead of 'formProps'.

**Comment by lljj-x** [comment]
可以的 感谢反馈

**Comment by AlexanderJi** [comment]
> 可以的 感谢反馈
/抱拳
