### ISSUE TITLE
AutoCompleteWidget如何使用

### ISSUE THREAD

**Issue by qiaofenlin** [lljj-x/vue-json-schema-form#344]
反馈问题请先查看文档和务必提供详细的复现代码，遵循如下格式，描述不清楚的问题将会直接关闭。

### vue和ui框架
vue3、ui框架antd、

###  问题描述
如何使用AutoCompleteWidget呢？

**Comment by lljj-x** [comment]
使用antd 的 a-auto-complete 组件，具体参数对应组件库的文档 ，类似下面。

model:value 参考这个 https://vue-json-schema-form.lljj.me/zh/guide/#%E5%A4%9A%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9

```js
"ui:widget": "a-auto-complete",
"ui:options": [
    {
        "value": 11111,
        "text": "111111.11"
    },
    {
        "value": 22222,
        "text": "2222"
    }
]
```
