### ISSUE TITLE
input number默认失去焦点才更新form，如何修改这个行为？希望可以在用户输入的时候实时更新form数据

### ISSUE THREAD

**Issue by koalayuan0607** [lljj-x/vue-json-schema-form#345]
### vue和ui框架
使用 vue2、element ui

###  问题描述
业务场景中提交按钮一般在外层组件，需要监听form的变化 进行实时校验。但特例是input number框，总是在失去焦点才会更新form。导致如果用户修改了input number框的值，然后直接点击外层的提交按钮，这个时候form的内容还未更新，导致校验结果不符合预期。
想请问能否通过传递参数、配置 去修改这个默认行为？

### 期望的结果
可以通过配置让input number框在用户输入的时候实时更新form数据

**Comment by lljj-x** [comment]
这个是elementUi 的el-input-number 实现逻辑，它应该是为了避免输入非数字格式，所以失焦后才emit了value。

如果elemntUi 没有参数能及时触发，那就需要自己实现一个类似的widget

**Comment by joker-ssh** [comment]
input 的也改成  trigger: 'change'
