### ISSUE TITLE
关于Vue JSON Schema Form使用文本框加上的图标问题

### ISSUE THREAD

**Issue by Verdant-Grassland** [lljj-x/vue-json-schema-form#346]
Vue3+ELementPlus的

###  问题描述
对错误是什么的清晰简洁的描述。

Vue JSON Schema Form使用文本框加上的图标，我不知道如何加上的文本框的图标方法的
![image](https://github.com/lljj-x/vue-json-schema-form/assets/107308136/60e99a84-a85d-4194-96cc-01bf3020896b)
大佬们，我这个是新手的，不知道怎么操作解决这个文本框加上的图标？

**Comment by lljj-x** [comment]
没明白，是要加slot 还是传参数给组件
