### ISSUE TITLE
求助，map[string]string动态添加属性，如何生成schema

### ISSUE THREAD

**Issue by snguovo** [lljj-x/vue-json-schema-form#349]
想提交一个类似http请求的表单，像headers这种`map[string]string`的object，key和value都是不定的，该如何生成schema呢？
我观察到官方json schema文档里有`"additionalProperties": true`是可以支持动态增加属性的。

**Comment by angellala** [comment]
同问+1，另外有场景根据用户选填 实时动态增加 json里的属性配置
![image](https://github.com/lljj-x/vue-json-schema-form/assets/24931840/7a8da1f8-93ae-49d9-88e1-60c3d083a89e)

**Comment by lljj-x** [comment]
@snguovo 现在不支持 additionalProperties: true ，目前也不计划支持 。 

可以用尝试数组来代替，比如 items: [{key, value}, {key, value}]

**Comment by lljj-x** [comment]
@angellala 基于jsonschema的语法可以使用 [anyOf](https://form.lljj.me/#/demo?ui=VueElementForm&type=AnyOf%28%E8%81%94%E5%8A%A8%29) 

或者通过ui上的显示隐藏，可以使用 [ui hidden表达式](https://form.lljj.me/#/demo?ui=VueElementForm&type=uiSchema-ui-hidden%28%E8%81%94%E5%8A%A8%29) 等
