### ISSUE TITLE
是否支持patternProperties或者相关功能

### ISSUE THREAD

**Issue by SakuragiJump** [lljj-x/vue-json-schema-form#35]
是否支持在schema中指定value的类型，而不指定key，比如：
{
  “dict”: {
    "xxx": "str1",
    "yyy": "str2"
  }
}
能不能支持这种数据的展示，用户动态去增加键值对。

**Comment by lljj-x** [comment]
现在不支持，暂时应该也不会支持，后面会考虑

object `additionalProperties`  属性 `不支持配置 对象`

这里有不支持部分说明：https://vue-json-schema-form.lljj.me/zh/guide/todo.html#%E4%B8%8D%E6%94%AF%E6%8C%81-%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0
