### ISSUE TITLE
Vue3使用SelectWidget多选，插槽没起效果

### ISSUE THREAD

**Issue by xplloveyxl** [lljj-x/vue-json-schema-form#352]
statusValue: {
                type: "array",
                title: "流转状态",
                description: "需求状态" + "<br />筛选完后，子任务不会脱离父任务单独显示，除非没有权限看到父任务。",
                uniqueItems: true,
                items: {
                    type: "string",
                    enum: ["需求分析", "设计中", "开发中", "测试中", "已上线", "已关闭"],
                    enumNames: ["需求分析", "设计中", "开发中", "测试中", "已上线", "已关闭"]
                },
                "ui:widget": "SelectWidget",
                "ui:options": {
                    width: "250px",
                    attrs: {
                        placeholder: "状态",
                        collapseTags: true,
                        collapseTagsTooltip: true,
                    },
                    renderScopedSlots() {
                        // default没起效果
                        return {
                            default: (props) => h("span", ".com")
                        };
                    }
                }
            }

**Comment by lljj-x** [comment]
`SelectWidget` 组件不支持插槽
