### ISSUE TITLE
Amazon 创建商品的JsonSchema

### ISSUE THREAD

**Issue by SylvieManx** [lljj-x/vue-json-schema-form#356]
你好，尝试使用该工具渲染表单，表单是正常出现了，但是我这个JsonSchema太复杂了，哪些属性是联动必填的没有展示出来，我看着全都是必填的。有空可以帮忙分析一下，愿意给大佬捐赠咖啡支持
[ARTIFICIAL_PLANT-Validation.json](https://github.com/lljj-x/vue-json-schema-form/files/15147000/ARTIFICIAL_PLANT-Validation.json)

**Comment by lljj-x** [comment]
有requiured 红点标识的都是必填的 ，我看是没什么问题
