### ISSUE TITLE
schema的editor的安全问题考虑

### ISSUE THREAD

**Issue by MHappy135246** [lljj-x/vue-json-schema-form#36]
如果Playgroudf是自己项目里的界面，schema的editor的安全问题考虑，editor是否可识别js或别的，会吗，这样的话自己的后端服务数据会有危险的吧？

**Comment by lljj-x** [comment]
editor没做特殊处理。

这里安全主要是 xss 攻击，防范的核心是要服务器去做特殊字符的转义 。另外vue 在渲染的时都会做特殊字符转义，v-html除外
