### ISSUE TITLE
vue3+Element plus下如何手动调用validate()方法校验表单

### ISSUE THREAD

**Issue by bozhang01** [lljj-x/vue-json-schema-form#361]
我的表单定义如下
`<ElementForm
      ref="formRef"
      :schema="currentSchema"
      :ui-schema="currentUISchema"
      v-model="localFormData"
    />`
....
import ElementForm from "@lljj/vue3-form-element"

请问如何手动调用validate方法而不是通过点击提交按钮来调用？
我看文档写的 通过form-mounted可以来执行form组件的一些方法，如(validate)，没太明白要怎么用。
能否给我个示例代码？比如我在setup里定义了一个handlerSubmit，这个方法里怎么通过formRef调用表单校验方法？
const handlerSubmit = () => {
//麻烦给个示例
}
多谢。

**Comment by LukerSpringtree** [comment]
感觉没人维护了吧

**Comment by bozhang01** [comment]
已找到解决方案

**Comment by lljj-x** [comment]
文档有介绍
https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#on-form-mounted
