### ISSUE TITLE
Select组件添加required属性后默认值问题

### ISSUE THREAD

**Issue by timdincode** [lljj-x/vue-json-schema-form#366]
### vue和ui框架
vue3 antv

###  问题描述
当配置select组件为required属性时，会自动选择第一个option，但实际情况是默认值除非额外设置否则为空

### 如何复现
配置：
<img width="521" alt="image" src="https://github.com/user-attachments/assets/a79889fb-367b-4cba-8a9b-99841cdf0033">

效果：
<img width="593" alt="image" src="https://github.com/user-attachments/assets/337f0aec-6eed-4543-87e5-426ee957fba5">

### 期望的结果
应该默认为空

**Comment by lljj-x** [comment]
```
formProps: {
  defaultSelectFirstOption: false // 设置成false
}
```

**Comment by timdincode** [comment]
> ```
> formProps: {
>   defaultSelectFirstOption: false // 设置成false
> }
> ```

但是还是不会显示placeholder

**Comment by lljj-x** [comment]
我看你的截图 placeholder 是对的 ，不明白你说的哪里
