### ISSUE TITLE
自定义Widget prop只支持value

### ISSUE THREAD

**Issue by gitAda16** [lljj-x/vue-json-schema-form#368]
### vue和ui框架
vue2+elementui

###  问题描述
我的自定义组件修改了prop的值，如下，
model: {
    prop: 'data',
    event: 'change'
  },
组件无法接收到表单的数据了

### 期望的结果
希望可以支持自定义prop的组件

**Comment by lljj-x** [comment]
对 不支持修改，这部分建议可以自己转换下
