### ISSUE TITLE
活动编辑器编辑好的页面，发布，生成数组，之后数组怎么用的

### ISSUE THREAD

**Issue by MHappy135246** [lljj-x/vue-json-schema-form#37]
活动编辑器编辑好的页面，发布，生成数组，我有疑问，之后数组怎么用呢？是需要写循环遍历然后再渲染成页面？这个循环遍历数组的方法是应该在别的项目？生成别的网站？

**Comment by lljj-x** [comment]
是的，目前只是最基本的生成 配置json数据，至于是在哪里把json生成页面看你的场景了

**Comment by MHappy135246** [comment]
移动端和pc端为什么不能是一套,？还要切换M/PC,响应式的话不是更好？

**Comment by lljj-x** [comment]
这个看你的需求，如果你要响应式那你需要把所有的View组件都需要做成响应式。

编辑器现在基本是停止更新，目前也只是实现了最基础的数据生成，只是为了给表单应用场景举例子

**Comment by MHappy135246** [comment]
好的，十分感谢
