### ISSUE TITLE
活动编辑器的页面布局

### ISSUE THREAD

**Issue by MHappy135246** [lljj-x/vue-json-schema-form#38]
活动编辑器的页面布局若不是流式布局，比如是flex布局，是不是就会有点复杂了？有什么好的建议吗

**Comment by lljj-x** [comment]
那其实要实现嵌套，也就是递归你的容器组件。

在 [Schema生成器](https://form.lljj.me/schema-generator.html#/index) 中布局支持一行多列也是类似实现可以参考下。

**Comment by MHappy135246** [comment]
Schema生成器 中布局？那个是一列多行吧？

**Comment by lljj-x** [comment]
是支持配置多列和嵌套
![image](https://user-images.githubusercontent.com/6283929/106998321-44770f80-67bf-11eb-9817-93a184d2c863.png)

**Comment by MHappy135246** [comment]
懂了。感谢
