### ISSUE TITLE
活动编辑器的draggable

### ISSUE THREAD

**Issue by MHappy135246** [lljj-x/vue-json-schema-form#41]
活动编辑器的draggable 
  v-model的数组和draggable的子元素循环渲染的数组不应该是同一个吗？为什么分别是editComponentList和trueComponentList. 这个trueComponentList包含的editHeaderComponentList和editFooterComponentList的用意是什么呢？

**Comment by MHappy135246** [comment]
![Uploading 1613719174(1).png…]()

**Comment by lljj-x** [comment]
这里是为了实现置顶或置底的数据配置，如果不需要用一个即可
