### ISSUE TITLE
vue3 动态赋值数组渲染报错

### ISSUE THREAD

**Issue by lljj-x** [lljj-x/vue-json-schema-form#42]
vue3数组用v-for的时候，如果一开始是空数组，然后异步再复制，渲染会报错。

往空数组里面推数据就这样了

![image](https://user-images.githubusercontent.com/6283929/109443252-0ba42080-7a75-11eb-9a92-20f662085543.png)

-- 来自qq群

**Comment by Juken8104** [comment]
![image](https://user-images.githubusercontent.com/17696855/109578516-461fc300-7b32-11eb-97f8-1ff880ae11d7.png)
![image](https://user-images.githubusercontent.com/17696855/109578546-533cb200-7b32-11eb-952d-cd33e8f2e2d1.png)
异步赋值deviceOptions，deviceOptions不能初始化为空数组，不然再赋值对应结构的“{ id: "test", name: "test" }”的元素，渲染就会报这个错。这个好像是element ui的问题。

**Comment by lljj-x** [comment]
我试了，options的语法是没问题的，你可以再看看。

https://codepen.io/ljj/pen/gOLzWgY。

**Comment by Juken8104** [comment]
我自己试了下，https://codesandbox.io/s/peaceful-ritchie-kufnr?file=/src/components/HelloWorld.vue。这样就可以的。但是我从后台请求在更新就还是报错。我在自己看看吧。
![image](https://user-images.githubusercontent.com/17696855/109734139-74b5a080-7bfb-11eb-91eb-d586fc10dee1.png)

**Comment by Juken8104** [comment]
这个问题解决了。应该是vue3.0.0的bug。我看了官方的issue，升级了vue的版本就正常了

**Comment by lljj-x** [comment]
好嘞，那我先关掉了
