### ISSUE TITLE
vue3部分的description不显示

### ISSUE THREAD

**Issue by ChainsDW** [lljj-x/vue-json-schema-form#44]
widget.js里的todo，目前vue3已经修复此bug，希望这边可以更新一下

**Comment by lljj-x** [comment]
新版本计划会在本周末更新，目前 `feat/vue3-ant` 这个分支已经解决了

**Comment by lljj-x** [comment]
https://github.com/lljj-x/vue-json-schema-form/releases/tag/v1.1.0
新版本已发布
