### ISSUE TITLE
antd vue3在label左排列时，颜色选择器等宽度不足。

### ISSUE THREAD

**Issue by diyao** [lljj-x/vue-json-schema-form#46]
https://form.lljj.me/v3/#/demo?ui=VueAntForm&type=Widgets 
以上ant版本，在顶部工具栏，选择Label靠左时：

1. 颜色选择器宽度不足。
2. 没有默认值的下拉选择框宽度也不足。

**Comment by lljj-x** [comment]
这个是因为 antd vue表单布局是使用栅格布局来实现，而不是配置 `labelWidth`，playground 没做特殊处理。

实际使用要类似antdv 的官方文档，form-props 传递 `labelCol` `wrapperCol` 来控制布局。

如下：

```js
const formProps = {
    labelCol: {
        span: 10
    },
    wrapperCol: {
        span: 13
    },
    ...otherProps
}
```
![image](https://user-images.githubusercontent.com/6283929/110226606-cf1c6d00-7f2b-11eb-926d-3305a43d5bb1.png)

----
playground 页面我会对 antd ui 下调整界面也支持配置，不然可能产生歧义

**Comment by lljj-x** [comment]
在看这个的时候发现了两个 ： 的问题，之前有留意忘了记录这个也会一并处理。
