### ISSUE TITLE
上传文件可以配置上传时的请求头吗

### ISSUE THREAD

**Issue by ChainsDW** [lljj-x/vue-json-schema-form#47]

**Comment by lljj-x** [comment]
ui参数会透传给具体的ui库组件，比如elementPlus
ui: headers = {
token: 'xxxxx'
}

**Comment by ChainsDW** [comment]
嗯嗯，成功了，还有一个问题，就是如果需要整个form只读的话，可以加一个VueForm的props参数来控制，因为form提交后正常是显示只读的

**Comment by lljj-x** [comment]
多看文档啊 
https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#form-props

```js
form-props = {
...
disabled: true
}
```

**Comment by ChainsDW** [comment]
可以可以
