### ISSUE TITLE
Schema生成器中如何增加自定义的组件？

### ISSUE THREAD

**Issue by 66lizhenhua66** [lljj-x/vue-json-schema-form#48]
我想增加一个远程搜索的Select控件，但是看了几天有点没看明白，文档里也只是通过VueJsonForm组件传入uiSchema生成的，望指教，谢谢！

**Comment by lljj-x** [comment]
简单理解，`Widget` 就是一个 v-model 的用户输入组件即可，其它ui参数都会传给你自定义的这个组件。

看起来你这个远程搜索需要一个输入框，v-model 绑定输入的值，可配置下搜索的 url ...

---
你是说这个文档不太明白吗？可以详细描述下不明白的地方来调整下文档
https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89widget

**Comment by 66lizhenhua66** [comment]
> 简单理解，`Widget` 就是一个 v-model 的用户输入组件即可，其它ui参数都会传给你自定义的这个组件。
> 
> 看起来你这个远程搜索需要一个输入框，v-model 绑定输入的值，可配置下搜索的 url ...
> 
> 你是说这个文档不太明白吗？可以详细描述下不明白的地方来调整下文档
> https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89widget

![image](https://user-images.githubusercontent.com/37864411/111068814-42fade80-8505-11eb-9fd0-2f10670b24e4.png)
文档里使用的是vue-form，我看到您的ViewComponentWrap.vue里边用的是 SchemaField字段
![image](https://user-images.githubusercontent.com/37864411/111068885-83f2f300-8505-11eb-8d87-de069e54103f.png)，有点不理解该怎么传递我的 uiSchema

**Comment by 66lizhenhua66** [comment]
![image](https://user-images.githubusercontent.com/37864411/111069874-13020a00-850a-11eb-81fc-5c3d21e2f2a3.png)
我这么配置之后，渲染出来是空的，啥都没有呢

**Comment by lljj-x** [comment]
先确定下你的需求，你是改 schema 生成器是吗？ 想在里面加一个远程搜索的组件，同时嵌入到左侧的组件库中去 ？

----
如果是这里的话，那你第一步是要先注册一个全局组件，比如 `RemoteSelectWidget` 然后实现这个组件。

```js
Vue.component('RemoteSelectWidget', {
  name: 'RemoteSelectWidget',
  props: {
    value: {
      type: Array
    }
  },
  render(h) {
    // render xxx
  }
})

```

要保证这个组件可用，然后再嵌入到你的编辑器中去，嵌入编辑器的时候 `ui:widget: 'RemoteSelectWidget'` 使用组件名。

目前看起来你是卡在了第一步。

**Comment by 66lizhenhua66** [comment]
按照您的方法，可以了，谢谢！不过一开始我是按照这样子来
![image](https://user-images.githubusercontent.com/37864411/111096927-8859f300-857b-11eb-9e5e-afc5df26a6d5.png)
我是想问下这样子是不能实现吗？还是说目前在vue3有bug呢？

**Comment by lljj-x** [comment]
vue3 中异步组件是需要使用  `defineasynccomponent` ，文档demo 都是基于vue2 + elmentUi 的版本

文档：https://v3.cn.vuejs.org/api/global-api.html#defineasynccomponent

**Comment by lljj-x** [comment]
这里内部实际是直接调用 `createElement` 去创建 vnode，所以需要像我们平时使用组件一样

**Comment by 66lizhenhua66** [comment]
好的，非常感谢！

**Comment by monstereat** [comment]
> 我想增加一个远程搜索的Select控件，但是看了几天有点没看明白，文档里也只是通过VueJsonForm组件传入uiSchema生成的，望指教，谢谢！

有demo  按照文档示例出不来

**Comment by lljj-x** [comment]
可以给复现有时间帮你看看
