### ISSUE TITLE
上传文件，值为空仍然显示已上传文件；可以改一下，然后上传文件组件无法预览，点击没有反应

### ISSUE THREAD

**Issue by ChainsDW** [lljj-x/vue-json-schema-form#50]
`defaultFileList = isArrayValue ? curModelValue.map(function (item, index) {
        return {
          name: "\u5DF2\u4E0A\u4F20\u6587\u4EF6\uFF08".concat(index + 1, "\uFF09"),
          url: item
        };
      }) : (curModelValue ? [{
        name: '已上传文件',
        url: curModelValue
      }] : []);`

**Comment by lljj-x** [comment]
奈斯，两个问题

1. 值为空的我处理下
2. 无法预览是指文件名无法点击？ 如果是的话这个是和ui库有关，比如elementUi 不能点，antd 可以点

> 另外提示下，这里代码实际只是对 `modelValue` 做了 `fileList` 的转换，所以再组件外再直接改 modelValue 是不会直接更新内部的fileList

**Comment by ChainsDW** [comment]
嗯嗯，elementui有个on-preview 是点击文件列表中已上传的文件时的钩子，可以参考或者暴露一下，要是上传组件无法预览或者下载，就缺了核心啦

**Comment by lljj-x** [comment]
好建议 我看看。

如果ui传入了 onPreview  会覆盖默认行为
