### ISSUE TITLE
如果表单字段过多，能不能分组显示？

### ISSUE THREAD

**Issue by cong99** [lljj-x/vue-json-schema-form#53]
比如说，生成器中右侧的配置表单，这边是两个表单，但是如果这些数据是一个表单呢？
![image](https://user-images.githubusercontent.com/9216936/112107862-76ff8f00-8bea-11eb-9e62-7632b8d6591f.png)
我在想您能否为大型表单提供一种分组的机制，类似于折叠面板或者tabs的实现，还是说有其他的方式展示大型表单？

**Comment by lljj-x** [comment]
目前 [schema-form-components](https://github.com/lljj-x/schema-form-components) 这个仓库放一下通用的 Field、Widget，后续会完善

这里有一个`tabs` 的使用
https://github.com/lljj-x/schema-form-components/blob/main/packages/demo/src/pages/index/App.vue

**Comment by cong99** [comment]
前面没注意看关闭的issue，之前好像有人提过这个问题了，现在看到了，不好意思
但是我还有两个小疑问：

1. 现在的tab是作为field，也就是必须是一个节点，一般是object节点，那么如果是两个object如何使用一个tab？
比方说，
```javascript
const user = {
    address: {
        province: 440000,
        city: "广州市",
        area: "海珠区"
    },
    contact: {
        qq: 'xxxxxx',
        phone: '13xxxxxxxxxx'
    },
    name: {
        firstName: 'xxxxxx',
        lastName: 'xhjhuh'
    }
}
```

我想把`user.address`与`user.contact`放在一个tab里，把其他信息放到另一个tab里

2. 自定义widget与field好象是必须先引入组件，然后把它设置给`ui:filed`，能否注册为全局组件，后面shcma直接填上字符串，方便schema序列化？（这个问题我还没测试，不过看到大佬您刚回答我的问题，就顺便问下）

```javascript
// 详细描述下，查看例子中发现，自定义widget要这么用
import { MyField } from '@lljj/schema-form-components/src/index';
...
schema = {
    ...
    
    properties: {
        xxx: {
            'ui:filed': MyField
            ...
		}
    }
}

// 我想这么使用
schema = {
    ...
    
    properties: {
        xxx: {
            'ui:filed': 'MyField'
            ...
		}
    }
}

// MyField可能我会在main.js那边做全局注册，或者在VueForm暴露出方法让我提供自己项目定义的widget、field；一来方便序列化，而来也不用每次引入

```

**Comment by cong99** [comment]
关于第二个问题，我验证一下，全局注册是可以，非常方便

**Comment by lljj-x** [comment]
对的 ，是可以全局注册，也可以是异步组件都是ok的。
----

另外你说的 object 下平级属性做分组，`这个目前没有现成的 field`，实现的话和现在这个对key做分组类似，只是需要你传一个分组的配置进来 ，比如：
```js
{
    'ui:field': 'MyGroupField',
    'ui:fieldProps': {
        group:[{
            keys: ['address', 'contact'],
            title: 'group 1'
        }, {
            keys: ['*'],
            title: 'group 2'
        }]
    }
}
```
然后内部处理的时候不直接使用单个属性做分组

**Comment by cong99** [comment]
了解了，感谢
