### ISSUE TITLE
数组类型能否可支持maxItems,minItems动态修改，比如像'ui:hidden'一样

### ISSUE THREAD

**Issue by haolovewan** [lljj-x/vue-json-schema-form#55]
首先，vue-json-schema-form是我在vue组件中遇到的最优秀的json-schema转换器，感谢作者的贡献。
目前有一个需求，通过一个rootformdata的一个字段来控制数组的长度，想通过动态修改type: 'array' 的maxItems属性值；
如果maxItems和minItems能支持方法传入就方便很多了！
![image](https://user-images.githubusercontent.com/20748824/112412504-910baf80-8d59-11eb-9a47-63f39fa11dd5.png)

**Comment by lljj-x** [comment]
之前也有过类似的问题，可以 onChange 的时候去手动的重新赋值处理。

或者JSON Schema 可以通过 anyOf 直接配置出来

----

加 ui 配置这个可以先考虑下
