### ISSUE TITLE
[bug]单选控件配置uniqueItems: true后仍然可以设置重复值

### ISSUE THREAD

**Issue by againF** [lljj-x/vue-json-schema-form#56]

**Comment by againF** [comment]
![image](https://user-images.githubusercontent.com/26742290/113263064-ea4c8380-9303-11eb-86f0-6902cc30e552.png)
如图，单选设置重复值会有问题，我尝试在单选控件配置uniqueItems: true，仍然不行。

**Comment by lljj-x** [comment]
首先 `uniqueItems` 是 `array` 类型的属性，所以是肯定不行的

---

你这里开起来是配置 "ui:widget": "RadioWidget" ，通过 `enmuOptions` 配置了选项列表，保证不重复是需要你自己处理 `enmuOptions` 数据的
