### ISSUE TITLE
为什么包要使用源码分发的方式？

### ISSUE THREAD

**Issue by colgin** [lljj-x/vue-json-schema-form#62]
npm包使用源码分发的方式，要求开发者使用的时候都要自己去配置babel，让babel去处理这个三方包。这似乎和主流的方式有点不太一样？现在大部分npm包都是将源文件编译打包之后在分发。
想问下作者这样设计的原因是什么？

**Comment by lljj-x** [comment]
你说的应该是 core 的那个package ，这个包不是直接面向使用者的，是只有当你需要基于此再构建自己的库时才需要。

基于此那主要为了方便对照core源码，另一方面构建的lib本身也需要打包那就没处理的必要性了。
