### ISSUE TITLE
有vue2 antdv的开发计划吗？或者有二次开发文档吗？

### ISSUE THREAD

**Issue by blogwy** [lljj-x/vue-json-schema-form#64]
怎么添加vue2 antdv支持？

**Comment by lljj-x** [comment]
没有计划。

目前vue2版本都是基于此实，不过要自己看源码。
https://github.com/lljj-x/vue-json-schema-form/tree/master/packages/lib/vue2/vue2-core

**Comment by blogwy** [comment]
谢谢作者
