### ISSUE TITLE
希望能将提供validate方法

### ISSUE THREAD

**Issue by cong99** [lljj-x/vue-json-schema-form#66]
有些时候想用自己的footer，所以提交按钮是写在表单外面的
类似于element form的用法
```javascript
this.$refs[formName].validate((valid) => {
      if (valid) {
        alert('submit!');
      } else {
        console.log('error submit!!');
        return false;
      }
});
```
我看了一下源码，发现其实也是有的，只不过用的时候比较麻烦
```javascript
this.$refs.myForm.$refs.genEditForm.validate((isValid, resData) => {
   console.log('isValid', isValid, resData)
})
```

**Comment by cong99** [comment]
有简单的方法让 自定义按钮 实现 “校验数据” 动作吗？

**Comment by lljj-x** [comment]
https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#on-form-mounted

![image](https://user-images.githubusercontent.com/6283929/119447840-106e2d00-bd63-11eb-9518-f5df34c9b667.png)
