### ISSUE TITLE
在Playground中验证，选择vue3无效

### ISSUE THREAD

**Issue by LuciferJun1227** [lljj-x/vue-json-schema-form#68]
在Playground中验证，选择vue3，页面刷新了，但是还是显示vue2，而且UI库选择的内容也是只有vue2的，没有vue3的选择

**Comment by lljj-x** [comment]
我自己试过了，是没问题的 。

你是什么浏览器 ，ie的话目前没做特殊兼容。

**Comment by LuciferJun1227** [comment]
用的chrome稳定最新版

**Comment by lljj-x** [comment]
明白了，你是说本地环境，而不是 https://form.lljj.me/#/demo?type=Simple 

---

dev环境无法直接使用这个操作切换，项目vue2、vue3 是两个单独的package，会在构建之后合并在一起 

`yarn run demo3:dev`

启动本地 vue3 demo

**Comment by LuciferJun1227** [comment]
可以了，谢谢
