### ISSUE TITLE
如果ui:xxxx和err:xxxx也能支持写到schema里面就更好了

### ISSUE THREAD

**Issue by alicksnake22** [lljj-x/vue-json-schema-form#7]
如果ui:xxxx和err:xxxx也能支持写到schema里面就更好了，类似alibaba的ant form那样，比较方便

**Comment by lljj-x** [comment]
可以，很好的建议，下个版本加上去

**Comment by Wisgon** [comment]
我倒是觉得就这样分开来好，逻辑比较清晰，schema是纯的json schema，ui是ui，不过ui和error并到一起倒还可以

**Comment by lljj-x** [comment]
原本的设计也是这样，保持一份纯的JsonSchema，也方便同步给服务端做数据校验等。
可能有些场景或者习惯写在一起，这里会做一个升级，可以支持两边同时配置，只不过单独配置的优先级更高。

@Wisgon 另外ui和error实际使用完全相同的路径读取，合并在一起确实可行

**Comment by lljj-x** [comment]
@alicksnake22 

[v0.0.16](https://github.com/lljj-x/vue-json-schema-form/releases/tag/v0.0.16) 这个版本可以支持在schema中配置 `ui`、`error`

文档参见这里：[ui、error 配置在schema中](https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#uischema%E9%85%8D%E7%BD%AE%E5%9C%A8schema%E4%B8%AD)

**Comment by alicksnake22** [comment]
@lljj-x 高效
