### ISSUE TITLE
vue3-form-ant颜色选择器没有办法展示传入和选择的颜色值预览

### ISSUE THREAD

**Issue by huanyu** [lljj-x/vue-json-schema-form#71]
需要修改config/widgets/WIDGET_MAP.js

将formats部分修改为如下后正常。

`formats: {
        color: {
            setup(props, { attrs }) {
                return () => h(InputWidget, {
                    ...attrs,
                    style: {
                        ...attrs.style || {},
                        maxWidth: '180px'
                    }
                }, {
                    addonAfter: () => h(InputWidget, {
                        disabled: attrs.disabled,
                        readonly: attrs.readonly,
                        modelValue: attrs.modelValue,
                        'onUpdate:modelValue': attrs['onUpdate:modelValue'],
                        type: 'color',
                        style: {
                            padding: '0',
                            width: '50px',
                            color: attrs.modelValue,
                        }
                    })
                });
            }
        },
    },`

**Comment by lljj-x** [comment]
我怀疑是antd 调整了input，但没证据，后面type color改成直接原生input
