### ISSUE TITLE
vue3+antd，a-textarea等相关输入组件，v-model 不使用默认 modelValue update:modelValue 需要特殊转换

### ISSUE THREAD

**Issue by kkk-lab** [lljj-x/vue-json-schema-form#72]
"ui:widget": "a-textarea"也不能正常使用，请问有考虑适配更多antd组件吗

**Comment by lljj-x** [comment]
目前不考虑，因为适配组件其实只需要组件是  v-model: modelValue 即可，使用者可以很低成本的适配自己的 `业务 Widget`

----
[modelValue 转换可以看这里](https://vue-json-schema-form.lljj.me/zh/guide/#vue3-ant-v-model-%E7%89%B9%E6%AE%8A%E5%A4%84%E7%90%86)

```js
import { modelValueComponent } from '@lljj/vue3-form-ant';

// 返回一个接受 modelValue 和 update:modelValue v-model的组件
const TextareaWidget = modelValueComponent('a-textarea', {
    model: 'value' // 这里要根据ant组件 model的参数传递
});
```

**Comment by kkk-lab** [comment]
已解决，感谢

**Comment by JermaHuang** [comment]
请问一下，这种自己转换的widget怎么在注册到全局的widget呢，
使用的时候直接使用组件 `"ui:widget": TextareaWidget `是可以的，但是写成字符串就不行了 `"ui:widget": "TextareaWidget"`

**Comment by BiBiuBiu** [comment]
> 请问一下，这种自己转换的widget怎么在注册到全局的widget呢，
> 使用的时候直接使用组件 `"ui:widget": TextareaWidget `是可以的，但是写成字符串就不行了 `"ui:widget": "TextareaWidget"`

https://learnvue.co/2020/08/how-to-register-a-vue3-global-component/
