### ISSUE TITLE
数据联动场景，若枚举值是object，生成的input json在不选择此枚举时也会传一个空对象

### ISSUE THREAD

**Issue by sandyMYY** [lljj-x/vue-json-schema-form#74]
数据联动场景，若枚举值是object，生成的input json在不选择此枚举时也会传一个空对象：
你好，我的问题如下：
文件为schema json：
[schema.pdf](https://github.com/lljj-x/vue-json-schema-form/files/6653006/schema.pdf)
页面选项如图：
![image](https://user-images.githubusercontent.com/56913882/121997499-0c22b600-cddd-11eb-8cd1-7103fa72ab03.png)
生成的json如下：
![image](https://user-images.githubusercontent.com/56913882/121997587-2c527500-cddd-11eb-81c1-9eccfdc74b9e.png)
"userInput":{"msg_body":{"parameter_item":[{"attr":"main_service_port","main_service_port":8888,"rrcislosms":{},"electric_fence_config":{}},{"attr":"rrcislosms","rrcislosms":{"rrct":1,"rrci":1},"electric_fence_config":{}},{"attr":"electric_fence_config","rrcislosms":{},"electric_fence_config":{"blue_point_enable":1,"no_parking_type":1,"electric_fence_report_enable":1,"after_close_max_scan_time":1,"blue_point_type":1,"a_blue_point_rssi_threshold":1,"a_blue_point_name":"111","b_blue_point_rssi_threshold":1,"b_blue_point_name":"1"}}]},"msg_head":{"device_id":"146387346594","msg_serial_number":1}}
辛苦看下~感谢！

**Comment by lljj-x** [comment]
这个是这样的，因为你使用 ui:hidden 来配置显示隐藏，并不会移掉不显示的formData 的值。 

--- 

如果想不产生冗余数据，可以使用 jsonSchema anyOf 来配置 .

https://form.lljj.me/#/demo?ui=VueElementForm&type=AnyOf%28%E8%81%94%E5%8A%A8%29
