### ISSUE TITLE
可以单独设置一行两列，下一行还是维持一列这种布局吗？

### ISSUE THREAD

**Issue by blogwy** [lljj-x/vue-json-schema-form#75]
schema生成器设置一行两列所有的行都变成两列了

**Comment by blogwy** [comment]
在API文档里面找到了

**Comment by anlia260** [comment]
好心人给一下地址，没找到呀

**Comment by blogwy** [comment]
> 
应该是这个，好久没用了，我都忘记了。重新找了一下
https://vue-json-schema-form.lljj.me/zh/guide/layout-config.html#layoutcolumn
