### ISSUE TITLE
大佬，有个问题想请问下，form-footer是否自定义配置按钮以及对应的样式，而是当前版本的取消/保存

### ISSUE THREAD

**Issue by liuk123456789** [lljj-x/vue-json-schema-form#76]

**Comment by lljj-x** [comment]
没太明白你的意思，不过看起来这里有你要的答案。

* [form-footer props](https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#form-footer)
* [插槽 Scope-Slot](https://vue-json-schema-form.lljj.me/zh/guide/basic-config.html#%E6%8F%92%E6%A7%BD-scope-slot)

**Comment by liuk123456789** [comment]
好的，谢谢大佬，我去看下文档
