### ISSUE TITLE
array类型无法使用"ui:options"的style

### ISSUE THREAD

**Issue by Wisgon** [lljj-x/vue-json-schema-form#8]
schema：
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "vjsf",
  "description": "vue-json-schema-form示例",
   "properties": {
        "listOfStrings": {
            "type": "array",
            "title": "A list of strings",
            "items": {
                "type": "string",
                "default": "bazinga"
            }
        }
}
```

ui-schema:
```
{
    "listOfStrings": {
        "ui:options": {
             "style": {
                    "boxShadow": "0 0 6px 2px #2b9939"
               }
        },
        "items": { ... }
    }
}
```

设置好后运行，这个listOfStrings的整体并没有带颜色的框出现，还有，设置"class"也无效

**Comment by lljj-x** [comment]
对的，目前版本确实不支持这样设置 

所有的 `ui:xx` 配置（props、attrs、style、class...）都只支持传给 `Widget` 组件，也就是输入数据交互的组件。而不能配置在 `field` 组件，也就是你说的 array 级。

如果有场景需要的话也可以支持对 `field组件` 传参（style/class/attrs）。

---
**临时方案：**

可以通过class类名 `__pathRoot_listOfStrings` 来匹配，这是根据数据结构解析出来的唯一路径。

这里有文档：[根据表单渲染的节点类名重置样式](https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E6%A0%B9%E6%8D%AE%E5%BD%93%E5%89%8D%E8%A1%A8%E5%8D%95%E6%B8%B2%E6%9F%93%E7%9A%84%E8%8A%82%E7%82%B9%E7%B1%BB%E5%90%8D%E9%87%8D%E7%BD%AE%E6%A0%B7%E5%BC%8F)

**Comment by Wisgon** [comment]
好的，谢谢。其实我的需求场景是，array中有array，这样的话，如果都是灰色的框，增加的item多了会变得眼花缭乱，如果父array的颜色框和子array的颜色框有明显的区分，这样的话就很清晰了

**Comment by lljj-x** [comment]
哈 不客气，明白了你的需要 ，就算有拼出来的 class 类名这里也不好处理。

最近我会升级下，这里只接收（style/class/attrs），因为传其它props可能存在不可控的副作用

**Comment by lljj-x** [comment]
[v0.1.0](https://github.com/lljj-x/vue-json-schema-form/releases/tag/v0.1.0)版本  uiSchema 支持任意节点配置 `fieldStyle`、`fieldClass`、`fieldAttrs`  

如：

```js
{
    "listOfStrings": {
        "ui:options": {
            "fieldStyle": {
                "boxShadow": "0 0 6px 2px #2b9939"
            }
        }
    }
}
```
