### ISSUE TITLE
考虑添加一些接口调用相关的配置

### ISSUE THREAD

**Issue by lljj-x** [lljj-x/vue-json-schema-form#81]
参考 amis 的一些配置方法，主要是在一些options接口返回数据，多级动态列表等相关

**Comment by wanjidong** [comment]
支持你，这样就更强大了。

**Comment by shurong2199** [comment]
太好了，目前是否支持异步校验：类似失去焦点时，接收 api 返回提示"用户名已存在"。
应该也属于这次更新内~

**Comment by lljj-x** [comment]
对，这个没支持是因为 ，内部还需要实现一个mini的xhr请求库，显得有些多余 。


你描述的这个场景，可以在自定义校验规则中实现
