### ISSUE TITLE
VueForm貌似不支持v-model绑定在setup中创建的reactive对象

### ISSUE THREAD

**Issue by huanyu** [lljj-x/vue-json-schema-form#82]
在vue3中，按照文档提供的使用方式可以正常使用，v-model绑定store里的值也能正常使用。就是在setup里创建一个reactive对象，然后v-model绑定这个值，不能正常使用。
代码如下：timer更改pageData没有正常更新到表单输入框中，在表单输入框输入东西后，提交表单也提示表单项数据为空值，过不了校验

    <VueForm
      @submit="handleSubmit"
      :schema="schemas"
      v-model="pageData"
    />

    setup() {
      const { createSuccessModal } = useMessage();

      const schemas = {
        description: '文章标题和内容不能为空',
        type: 'object',
        properties: {
          id: {
            title: 'none',
            type: 'number',
            'ui:hidden': true,
            default: undefined,
          },
          title: {
            title: '标题',
            type: 'string',
          },
          content: {
            title: '文章内容',
            type: 'string',
            format: 'richtext',
            'ui:options': {
              placeholder: '请输入文案',
              rows: 5,
            },
          },
        },
        required: ['title', 'content'],
      };
      let pageData: PageDetailModel = reactive({
        id: undefined,
        title: '',
        content: '',
      });

      async function loadData(id: number) {
        setTimeout(() => {
          pageData.id = 1;
          pageData.title = '1111';
          pageData.content = '2222';
        }, 2000);
      }
      loadData();

      function clear() {
        pageData.title = '';
        pageData.content = '';
        pageData.id = undefined;
      }

      async function handleSubmit() {
        console.log('handleSubmit', pageData);
      }

      return { pageData, schemas, handleSubmit, onUpdate };
    },

**Comment by lljj-x** [comment]
你试试把 `reactive` 换成 `ref` ，或者 使用 `pageData.formData` 这个结构来 reactive
```js
{
 formdata: {
    id: undefined,
    title: '',
    content: '',
 }
}
```

reactive 的值是不能直接被重新赋值的，v-mode 语法糖包含了重新赋值， 而ref 会加包 .value

**Comment by huanyu** [comment]
试了reactive和ref都不行，我自己也看看源码找找原因

**Comment by huanyu** [comment]
试了使用reactive嵌套解构和换成ref，两种方式都不能达到双向绑定。我自己也看看源码找找原因

**Comment by huanyu** [comment]
哦 应该是我的问题。pageData的解构和属性列表没有和schema里定义的完全一致
