### ISSUE TITLE
请问一下Vue3有可视化的Schema 生成器嘛

### ISSUE THREAD

**Issue by LuciferJun1227** [lljj-x/vue-json-schema-form#85]
找了一圈，只看到vue2有可视化的生成器，Vue3有Ant desgin vue的嘛

**Comment by lljj-x** [comment]
没有的，生成器只做了vue elementui 的demo

**Comment by LuciferJun1227** [comment]
@lljj-x 你好，后面会有作这个打算嘛

**Comment by lljj-x** [comment]
目前没有计划，直接使用 options api vue2/3 可以自行迁移
