### ISSUE TITLE
对于object不确定有多少个key的object如何实现

### ISSUE THREAD

**Issue by longli61990** [lljj-x/vue-json-schema-form#96]
有个需求是需要一个object，object里的key是不确定有哪些key的，key对应的value是固定的格式

**Comment by xxfan** [comment]
有同样的需求

**Comment by lljj-x** [comment]
目前不支持 additionalProperties 里面配置一个schema

只能通过 ui:field 自己实现添加key和value的逻辑

**Comment by lljj-x** [comment]
https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties
