### ISSUE TITLE
关于vue3+antdv在drawer里渲染vueform耗时问题

### ISSUE THREAD

**Issue by thousandsNight** [lljj-x/vue-json-schema-form#98]
![image](https://user-images.githubusercontent.com/11659929/132643935-8570491e-b52e-47ce-88be-34404471f196.png)
<img width="411" alt="image" src="https://user-images.githubusercontent.com/11659929/132644014-23601758-bb85-4b95-b3be-c821f6be9acd.png">
抽屉打开时间有点久了，跟schema复杂度成正比，是我哪用得不对吗

**Comment by lljj-x** [comment]
你这个 schema是有几千行 ?  首次渲染需要逐个节点递归，肯定是和你的schema复杂度成正比。

如果这样你可以考虑把组延迟渲染，比如 抽屉打开之后。

-- 
另外问下你的 devtools 做了什么配置可以看到 渲染时间呢 ？我用的最新6.0 beta版没有

**Comment by thousandsNight** [comment]
> 你这个 schema是有几千行 ? 首次渲染需要逐个节点递归，肯定是和你的schema复杂度成正比。
> 
> 如果这样你可以考虑把组延迟渲染，比如 抽屉打开之后。
> 
> 另外问下你的 devtools 做了什么配置可以看到 渲染时间呢 ？我用的最新6.0 beta版没有

![image](https://user-images.githubusercontent.com/11659929/132788937-02c64a20-6096-48d1-9510-fe715a35b09d.png)
感谢回复，devtool的话没配置啥

schema长这样子，没多少行，估摸着得3秒后才弹出抽屉2333
const HttpListener = {
  type: 'object',
  properties: {
    base: {
      type: 'object',
      title: '基本配置',
      properties: {
        path: {
          title: '监听路径',
          type: 'string',
          default: '/',
        },
        method: {
          title: '监听路径',
          type: 'string',
          enum: [
            'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD',
          ],
          enumNames: [
            'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD',
          ],
        },
      },
    },
    response: {
      type: 'object',
      title: '响应配置',
      properties: {
        normal: {
          type: 'object',
          title: '正常响应',
          properties: {
            code: {
              title: '状态码',
              type: 'string',
            },
            header: {
              title: '响应头',
              type: 'string',
            },
            body: {
              title: '响应体',
              type: 'string',
            },
          },
        },
        error: {
          type: 'object',
          title: '错误响应',
          properties: {
            code: {
              title: '状态码',
              type: 'string',
            },
            header: {
              title: '响应头',
              type: 'string',
            },
            body: {
              title: '响应体',
              type: 'string',
            },
          },
        },
      },
    },
    advanced: {
      type: 'object',
      title: '高级配置',
      properties: {
        attribute: {
          title: '消息属性',
          type: 'string',
          default: '',
        },
        type: {
          title: '类型选择',
          type: 'string',
          default: '空',
          enum: [
            '空', 'any', 'string', 'int', 'float', 'bool',
          ],
          enumNames: [
            '空', 'any', 'string', 'int', 'float', 'bool',
          ],
        },
        format: {
          title: '数据消费格式',
          type: 'string',
          enum: [
            'repeatable', 'non-repeatable',
          ],
          enumNames: [
            'repeatable', 'non-repeatable',
          ],
        },
      },
    },
  },
};

**Comment by thousandsNight** [comment]
> 你这个 schema是有几千行 ? 首次渲染需要逐个节点递归，肯定是和你的schema复杂度成正比。
> 
> 如果这样你可以考虑把组延迟渲染，比如 抽屉打开之后。
> 
> 另外问下你的 devtools 做了什么配置可以看到 渲染时间呢 ？我用的最新6.0 beta版没有

![image](https://user-images.githubusercontent.com/11659929/132789869-f25b8fda-4d7f-4184-832b-2861602a929e.png)
感谢回复，devtool没配置啥

schema就100行，但是估摸着得3秒后抽屉才弹出，就很奇怪
`const HttpListener = {
  type: 'object',
  properties: {
    base: {
      type: 'object',
      title: '基本配置',
      properties: {
        path: {
          title: '监听路径',
          type: 'string',
          default: '/',
        },
        method: {
          title: '监听路径',
          type: 'string',
          enum: [
            'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD',
          ],
          enumNames: [
            'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD',
          ],
        },
      },
    },
    response: {
      type: 'object',
      title: '响应配置',
      properties: {
        normal: {
          type: 'object',
          title: '正常响应',
          properties: {
            code: {
              title: '状态码',
              type: 'string',
            },
            header: {
              title: '响应头',
              type: 'string',
            },
            body: {
              title: '响应体',
              type: 'string',
            },
          },
        },
        error: {
          type: 'object',
          title: '错误响应',
          properties: {
            code: {
              title: '状态码',
              type: 'string',
            },
            header: {
              title: '响应头',
              type: 'string',
            },
            body: {
              title: '响应体',
              type: 'string',
            },
          },
        },
      },
    },
    advanced: {
      type: 'object',
      title: '高级配置',
      properties: {
        attribute: {
          title: '消息属性',
          type: 'string',
          default: '',
        },
        type: {
          title: '类型选择',
          type: 'string',
          default: '空',
          enum: [
            '空', 'any', 'string', 'int', 'float', 'bool',
          ],
          enumNames: [
            '空', 'any', 'string', 'int', 'float', 'bool',
          ],
        },
        format: {
          title: '数据消费格式',
          type: 'string',
          enum: [
            'repeatable', 'non-repeatable',
          ],
          enumNames: [
            'repeatable', 'non-repeatable',
          ],
        },
      },
    },
  },
};`

**Comment by lljj-x** [comment]
看起来没问题，你可以详细展开看看是哪些具体组件耗时。

这个schema比playground的都要简单 你可以去那边看看渲染时间

**Comment by thousandsNight** [comment]
> 看起来没问题，你可以详细展开看看是哪些具体组件耗时。
> 
> 这个schema比playground的都要简单 你可以去那边看看渲染时间

<img width="378" alt="image" src="https://user-images.githubusercontent.com/11659929/132840252-5abac1d4-eb6e-45c2-9bdb-ea273ccf8855.png">
直接渲染没有问题的，我甚至试了用上面v-if包一下，showDrawer由false变为true，就不是秒渲染了
方便的话我发一份demo给你，大佬帮我瞅瞅

**Comment by thousandsNight** [comment]
> > 看起来没问题，你可以详细展开看看是哪些具体组件耗时。
> > 这个schema比playground的都要简单 你可以去那边看看渲染时间
> 
> <img alt="image" width="378" src="https://user-images.githubusercontent.com/11659929/132840252-5abac1d4-eb6e-45c2-9bdb-ea273ccf8855.png">
> 
> 直接渲染没有问题的，我甚至试了用上面v-if包一下，showDrawer由false变为true，就不是秒渲染了 方便的话我发一份demo给你，大佬帮我瞅瞅

<img width="507" alt="image" src="https://user-images.githubusercontent.com/11659929/132840771-79d24335-5258-4970-bbb0-92407ba28c27.png">

**Comment by lljj-x** [comment]
你可以提供一个最小复现仓库，我看看

**Comment by thousandsNight** [comment]
> 你可以提供一个最小复现仓库，我看看

感谢回复，找到原因了，我这个devtools的问题，关了就好了
